### ISSUE TITLE
各URIのページで、それに関連するだけのttlをダウンロードできるように

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#103]
すごく便利にもなるとおもう。
デバッグや、例を書くのにも便利だし、あるとすごくうれしい。

そのリソースへ矢印を挿しているリソース
そのリソースが矢印を挿しているリソース

あたりがあるといいのかも。

**Comment by yegusa** [comment]
まずは、個別の教科書のページから実現する

例： https://w3id.org/jp-textbook/小学校/2010/国語/101

**Comment by yegusa** [comment]
https://w3id.org/jp-textbook/小学校/2010/国語/101.ttl としたら、ダウンロードできるように。

**Comment by masao** [comment]
テストスクリプト:

```ruby
#!/usr/bin/env ruby

require_relative "util.rb"
require "sparql"

include Textbook
file = find_turtle("z.ttl")
STDERR.puts "loading #{file}..."
data = load_turtle(file)
g = RDF::Graph.load(file, format:  :turtle)

data.each do |key, val|
  next if not key =~ /\Ahttps:\/\/w3id.org\/jp-textbook\//
  p key
  sparql = SPARQL.parse("
  prefix textbook:  <https://w3id.org/jp-textbook/>
  DESCRIBE <#{key}>
  ")
  p sparql
  g2 = sparql.execute(g)
  puts g2.dump(:turtle)
end
```

**Comment by masao** [comment]
教科書リソースについては、Tutle形式のデータを生成して追加しました。

**Comment by masao** [comment]
https://github.com/jshttp/mime-db/pull/128 PRも取り込まれ、日本語が一部文字化けしていた問題も対応済みとなりました。

**Comment by yegusa** [comment]
できていることを確認しました。

![2018-06-05 10 18 22](https://user-images.githubusercontent.com/1328499/40949623-e012c83e-68a9-11e8-9737-c25f111350c5.png)

クローズします。
