### ISSUE TITLE
教科に英語名をつける

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#104]
参考 http://www.mext.go.jp/a_menu/shotou/new-cs/youryou/eiyaku/__icsFiles/afieldfile/2011/04/11/1298353_0.pdf

**Comment by yegusa** [comment]
英語名の出典を付けたいけど、リソースにしないと無理だよね。どうしたらよいかしら。とりあえず、作業的には、Excelには出典をつけておきますが。

**Comment by yegusa** [comment]
現行の指導要領は、「仮訳」があるので、そこから、英語名を引っ張ってこれそうです。ただし、全部ない。

小学校（社会なし）：
http://www.mext.go.jp/a_menu/shotou/new-cs/youryou/eiyaku/1298356.htm

中学校：
http://www.mext.go.jp/a_menu/shotou/new-cs/youryou/eiyaku/1298356.htm

高等学校（一般科目のみ教科名の英訳あり）：
http://www.mext.go.jp/a_menu/shotou/new-cs/youryou/eiyaku/1298353.htm

**Comment by yegusa** [comment]
英語名の正式名称があるかどうか、教育図書館にレファレンスをしました。教科書課につとめていた方にもアクセスし、文部科学省の関連課の職員にも問い合わせてもらいましたが、学習指導要領の仮訳以外には、ないようでした（例えば、白書などにもないようです）。図書館がさがしてくれた、文部科学省が出している英語のガイド（？　あとで書誌情報追加します）には、教科名が少しあるようでしたので、そちらは使えそう。

**Comment by yegusa** [comment]
出典情報については、Excelのほうに書いておきましたが、とりあえず、英語名だけでも、あるといいとおもいましたので、作成しておきました。5.0系のフォルダにttlファイルを置いておきますので、確認ください。

例：  schema:name "Japanese Language "@en;

以下のようなかんじで。

```
<https://w3id.org/jp-textbook/curriculum/中学校/1993/国語> a <https://w3id.org/jp-textbook/curriculum/SubjectArea>;
  schema:name "国語"@ja;
  schema:name "こくご"@ja-Hira;
  schema:name "Japanese Language "@en;
  textbook:school <http://ja.dbpedia.org/resource/中学校>;
  qb:order 1.
```

**Comment by yegusa** [comment]
関連 #65

**Comment by masao** [comment]
確認しました。ひとまずクローズします。
