### ISSUE TITLE
aboutページに目次等のナビゲーションを追加

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#105]
aboutページの説明が長くなってきたので、全体の見通しが悪い。
* https://jp-textbook.github.io/about.html

### 案1: 目次を付ける。

HTMLの見出しから自動で目次を作ってくれるツールがあるので、それを利用するのが楽そう：
* https://afeld.github.io/bootstrap-toc/
* http://gregfranko.com/jquery.tocify.js/

### 案2: 各リソース説明を別ページするか最初は隠しておく等

教科書以外のリソース説明は別のページに移すか、
もしくは、アコーディオンUIで最初は閉じておいてクリックすると説明が開く等の方式を検討すること。

**Comment by masao** [comment]
目次追加しました。

**Comment by yegusa** [comment]
見ました。良いとおもます。クローズします。
