### ISSUE TITLE
プロパティ・リソースの説明ページを作る

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#106]
``textbook:grade`` など、独自名前空間で作成しているプロパティの説明を行えるようにすること。
about に転送するページとしてしまってもよいかも???

基本的な情報リソースについてはだいたいできてきたので、そろそろ用意してもよいかも。

**Comment by yegusa** [comment]
#182 と関連。

**Comment by yegusa** [comment]
#182 のほうが先。そしたら、できるかも？

**Comment by masao** [comment]
今度は #359 に依存。

**Comment by masao** [comment]
#357 時点でできているようなので、クローズしてしまいましょうか。
https://w3id.org/jp-textbook/grade 自動生成するようにしています。

**Comment by yegusa** [comment]
できてますね。クローズします。
