### ISSUE TITLE
対象学年に空白となっている教科書データがある

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#107]
以下の3件のみ：

* https://w3id.org/jp-textbook/高等学校/2008/英R/039
* https://w3id.org/jp-textbook/高等学校/2008/英R/043
* https://w3id.org/jp-textbook/高等学校/2008/英W/043

ひとまずプログラム側で修正する。
データ修正すべきかは要確認。

**Comment by masao** [comment]
ひとまずプログラム側は対応済み。

**Comment by yegusa** [comment]
高等学校って、学年にデータはないのでは？空白スペース文字が入っているということ？

**Comment by masao** [comment]
はい、学年フィールドに半角空白が入っていたようです。

**Comment by yegusa** [comment]
教育図書館に先ほど連絡し、図書館のほうの元データは、修正済みです。
今後、同様のことがあったときのために、可能であれば、プログラム側でワーニングが出るようにして、知らせてもらえると助かります。

**Comment by yegusa** [comment]
参考：
教育図書館のシステムでは、この状況（学年に半角スペースが入っている）と、
検索でヒットしない、検索結果が表示されないレコードになってしまうようです。

**Comment by masao** [comment]
確認したところ、上記の3件のみだったようです。クローズしておきます。
