### ISSUE TITLE
スクリプト作成： ttl変換のrubyスクリプトを作る

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#11]
- [x] スクリプト作成
- [x] #35 重複レコード処理をやる

現在は、ttl変換は、Excelでやっているが、今後、元データ(TSV）から、
すぐに変換できるようにするために、ruby で作り直す。

1. 抽出しないフラグを除去 #10
2. 種目の正規化（半角・全角、アルファベット・ローマ数字など）
3. ttl 変換

が少なくとも必要

**Comment by yegusa** [comment]
新しいやり方メモ

1. 教育図書館からデータをExcelでもらう
2. 既存データから、vlookupを使って、指導要領のURIをとってきて移行する
3. 新規追加データについては、手で指導要領のURIを入れる
4. TSVを書きだす
5. rubyスクリプトにかけてttl変換

（ruby スクリプトでは、種目の正規化もやる予定）

**Comment by yegusa** [comment]
#35 がおわれば、これもクローズできるはず。

**Comment by yegusa** [comment]
種目の正規化メモ

- A,B,C,(,) の全角は半角にする
- 1, １（全角）は I
- 2, ２（全角）は II
- 3, ３（全角）は III
- I（全角）は半角にする

**Comment by masao** [comment]
一通り作成したのでひとまず完了とします。

**Comment by yegusa** [comment]
参考：教育図書館には、 2017-05-04 にメールで正規化後の種目を送付ずみ。プログラムで処理することにしたので、無理に修正されてなくてもいいが、一応、教育図書館には連絡した。古い教科書の種目については、単純変換するとおかしくなるものや、対応できない揺れ（漢字の数字など）もあるので、もし、古い教科書を対象にするようにする場合は注意すること。

一括変換に注意が必応なもの：

化学（５単位）
化学（３単位）
解析１（昭和２６年発行の目録）
解析１（昭和２７年発行の目録）
解析２（昭和２６年発行の目録）
解析２（昭和２７年発行の目録）
古典（漢文・一単位用）
古典（漢文・二単位用）
古典（古文・一単位用）
古典（古文・二単位用）
古典２（漢文・一単位用）
古典２（漢文・二単位用）
古典２（古文・一単位用）
古典２（古文・二単位用）
数学１（６単位）
数学１（９単位）
生物（５単位）
物理（５単位）
物理（３単位）
理科(第一分野)
理科（第一分野）
理科(第二分野)
理科（第二分野）
