### ISSUE TITLE
重複レコードで同一年に同一URIを持つ状態のもの

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#110]
2017年度使用教科書データにおいて、下記の所蔵IDの3つが同一のURIとなる。

URI: https://w3id.org/jp-textbook/高等学校/2014/古A/309

* "EB16336158" (2015-2016)
* "EB20036186" (2017)
* "EB20036576" (2017-)

入力ミスなどが疑われる...

**Comment by yegusa** [comment]
https://nieropac.nier.go.jp/ebopac/EB16336158
https://nieropac.nier.go.jp/ebopac/EB20036186
https://nieropac.nier.go.jp/ebopac/EB20036576

"EB20036186" (2017)と"EB20036576" (2017-)が重複レコードのようにみえます。
備考のない、EB20036576のほうを削除するほうがよさそう。

教育図書館に連絡しておきました。

参考：
教科書センター目録番号：320140009　http://textbook-rc-lib.net/dl/SsaOkobBIBy2ftPelVbXwTJqTVi?free_word=320140009
教科書センター目録番号：320160034　　http://textbook-rc-lib.net/dl/SsaOkobBIBy2ftPelVbXwTJqTVi?free_word=320160034

**Comment by yegusa** [comment]
教育図書館から、修正連絡きました。

古A309
○ https://nieropac.nier.go.jp/ebopac/EB20036186
× https://nieropac.nier.go.jp/ebopac/EB20036576

これのほかにも、同様のまちがいがあったので、一緒に修正したそうです。

古A303
○ https://nieropac.nier.go.jp/ebopac/EB20036181
× https://nieropac.nier.go.jp/ebopac/EB20036574

古A304
○ https://nieropac.nier.go.jp/ebopac/EB20036183
× https://nieropac.nier.go.jp/ebopac/EB20036575

古A311
○ https://nieropac.nier.go.jp/ebopac/EB20036188
× https://nieropac.nier.go.jp/ebopac/EB20036577

古B319
○ https://nieropac.nier.go.jp/ebopac/EB20036190
× https://nieropac.nier.go.jp/ebopac/EB20036578

**Comment by yegusa** [comment]
教育図書館の本体データが修正されていることは、確認しました。データ貰っておきますね。

**Comment by yegusa** [comment]
データ入手しました(2017-10-03版)

**Comment by masao** [comment]
修正を確認しました。クローズします。
