### ISSUE TITLE
検定年が不正なデータ: "EB16209452"

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#112]
https://w3id.org/jp-textbook/高等学校/2011/数A/306

検定年：「2011 2016」となっており、入力ミスと思われる。

**Comment by yegusa** [comment]
検定年：「2011 2016」ですが、
検定年は、2011年っぽいですね。

使用年を入れようとしたときに、何か間違えたのかもですね。

https://w3id.org/jp-textbook/高等学校/2011/数A/306
https://nieropac.nier.go.jp/ebopac/EB16209452

参考：教科書センターのデータベース 320110037 で検索
http://textbook-rc-lib.net/dl/SsaOkobBIBy2ftPelVbXwTJqTVi?free_word=320110037

教育図書館に連絡しておきました。

**Comment by yegusa** [comment]
教育図書館から修正の連絡きました。

2011
https://nieropac.nier.go.jp/ebopac/EB16209452

に修正したそうです。

教育図書館のシステムのほうでは修正されていることを確認しました。
データ貰っておきますね。

**Comment by yegusa** [comment]
データ入手しました（2017-10-03版）

**Comment by masao** [comment]
修正データを確認しました。クローズします。
