### ISSUE TITLE
一部の補助漢字の文字が出力されない

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#113]
20170920の新規データにて、一部の補助漢字相当の文字が出力されていない。
元の出力を要確認のこと。

所蔵レコードID： EB10015306
出力されている著者名：「斎藤能 高橋健夫 ほか16名」

OPACでの表示：「斎藤歖能 高橋健夫 ほか16名」 https://nieropac.nier.go.jp/ebopac/EB10015306

**Comment by yegusa** [comment]
#46 とはまた、別の問題なんですね。ちなみに、今は、普通に出力されてますね。 #46 のほうは。

**Comment by yegusa** [comment]
これですね。　https://w3id.org/jp-textbook/中学校/2001/保体/701

初版の時はOKだったのに、今回はだめだったと。
確かに、手元にある、No.78_戦後教科書リスト_20170427.xlsx では、

![image](https://user-images.githubusercontent.com/1328499/31080286-3548c86a-a7c3-11e7-8337-c95fc2996d78.png)

となっていますね。

このときは、ExcelでもらっていたからOKだったということでしょうかね。。。

UTF8でもらうのがいいでしょうか・・・。

教育図書館に連絡しておきました。
こちらは、業者マターになるので、少し時間がかかるかと思います。

**Comment by yegusa** [comment]
2017-10-17に入手できるはず。

**Comment by yegusa** [comment]
入手しました。

**Comment by yegusa** [comment]
学習指導要領URIをくっつけたデータも用意済みです。 5.2系フォルダにいれてあります

**Comment by yegusa** [comment]
2017-11-16 教育図書館から新しいデータとして入手しました(list_EB20171116.txt)。まだ、ttlにできるデータの準備はできていません。

**Comment by yegusa** [comment]
ttlにできる準備終了。 6.0系フォルダにいれておきました。

**Comment by yegusa** [comment]
2017-11-30 の打ち合わせにより、やはり、5.2系としてリリースすることに
5.2系_新フォルダにいれておきました。

**Comment by yegusa** [comment]
Excelでは表示されているが、csvやtsvに落としたときにおかしくなるようです。
詳細は @masao より。

a)  Excelでインポート&エクスポートに困るので、こわれないデータをもらう
b) tsvでデータをもらっているので、Excelに入れずに使う。

のどちらか、かなと。

**Comment by masao** [comment]
c) Excelから直接読み込む。

ライブラリ https://github.com/roo-rb/roo を用いると、Excelファイルを直接読み込めるので、こちらで対応しようかと思います。
簡単に試してみて、以下のように正しい文字が取得できることは確認しました：

```ruby
z=Roo::Spreadsheet.open "test.xlsx"
z.first
=> ["EB", "EB10015306", "0", "1", "1", "新しい保健体育", nil, nil, "斎藤歖能 高橋健夫 ほか16名", "東京書籍株式会社", "2", "東書", "K260.49||T8P||01/02", "2001", "2002-2005", "平成14-平成17", "2002 2005", "2001", "平成13", "中学校", "保健体育", "保健体育", "保健体育", "保健体育", "1,2,3", "1 2 3", "保体", "701", "142; B5", nil, "01", "20081010", nil, "https://w3id.org/jp-textbook/curriculum/中学校/2002", "保健体育", "https://w3id.org/jp-textbook/中学校/2001/保体/701"]
```

**Comment by masao** [comment]
c) の方式の拡張で実施。いったん xlsx → tsv 形式変換して中間ファイル生成したうえで、 tsv → ttl 変換を行うこととした。

**Comment by yegusa** [comment]
表示できていることを確認しました。ので、クローズします。

![image](https://user-images.githubusercontent.com/1328499/33512135-fbd602da-d76c-11e7-9cd6-6da0042105b1.png)
