### ISSUE TITLE
検定年などで元号を併記する

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#115]
検定年など、教科書本体には元号表記されているので、データ確認などの際に元号表記があるとうれしいとの要望あり。
公開系の変換プログラム側で一律に変換した内容を併記するようにする。

**Comment by masao** [comment]
一通り、表記に元号（平成～年）を追加するように機能追加しました。
確認願います。

**Comment by yegusa** [comment]
確認しました。クローズします。

![image](https://user-images.githubusercontent.com/1328499/30956403-2cc2b0a6-a472-11e7-9c6f-e87c0f956c53.png)
