### ISSUE TITLE
検定年度は誤り（検定年に修正する）

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#116]
サイト上のラベルを修正すること：
誤：検定年度
正：検定年

**Comment by masao** [comment]
修正しました。確認願います。

**Comment by yegusa** [comment]
検定年　になっていることを確認しました。のでクローズします

![image](https://user-images.githubusercontent.com/1328499/30956358-0bdea05c-a472-11e7-96e6-3553e4df4233.png)
