### ISSUE TITLE
種目ページのHTML検証

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#118]
いくつかのページでHTML検証が通らない箇所が残っている模様。

cf. 種目: https://jp-textbook.github.io/curriculum/%E5%B0%8F%E5%AD%A6%E6%A0%A1/2011/%E5%9B%BD%E8%AA%9E/%E5%9B%BD%E8%AA%9E

**Comment by masao** [comment]
修正済み。要確認。
cf. https://validator.w3.org/nu/?doc=https%3A%2F%2Fjp-textbook.github.io%2Fcurriculum%2F%25E5%25B0%258F%25E5%25AD%25A6%25E6%25A0%25A1%2F2011%2F%25E5%259B%25BD%25E8%25AA%259E%2F%25E5%259B%25BD%25E8%25AA%259E

**Comment by yegusa** [comment]
確認しました。no error ってなってますね。クローズします。
