### ISSUE TITLE
ページ数・大きさをHTMLに表示

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#119]
#7 にともない、ページ数、大きさがttlに追加されたので、HTMLでの表示にも反映すること

**Comment by masao** [comment]
追加しました。確認願います

**Comment by yegusa** [comment]
大きさとページ数が表示されていることを確認しましたので、クローズします。

![image](https://user-images.githubusercontent.com/1328499/31130221-c8bd784c-a891-11e7-8088-97b15a987b75.png)
