### ISSUE TITLE
LODクラウドへの掲載

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#12]
[LODクラウド](http://lod-cloud.net/)の一部に掲載してもらい、LOD情報としての可視性を高めたい。
本家または日本語版のLODクラウドに加えてもらうこと。

掲載条件は以下の6点です：
1. 解決可能なURIを付与していること
2. RDFデータ形式を提供していること
3. 1000トリプル以上のデータセットであること
4. LODクラウドにすでに掲載されている他のデータセットへのリンクを50件以上含むこと
5. データセット全体にアクセスできること
6. [DataHub](https://datahub.io/)に掲載されていること

現状では6番のDataHubへの掲載が満足されれば問題なく掲載可能となります。

**Comment by yegusa** [comment]
DataHub に申請した

アカウントとってねっていわれて出したのだけど、無視された

という状況

**Comment by masao** [comment]
勘違いでした。いま見たら、投稿が見当たりませんので、ミスで投稿しそびれていたのかもしれません。
https://discuss.okfn.org/t/creating-a-dataset-on-the-datahub/1627 にある通り、 Datahub に投稿するには、 Organization を作る必要があり、それを作るためには、個別に okfn フォーラムにて Organization 作成依頼を出す必要があるとのこと。

**Comment by masao** [comment]
うーん、やはり寝ぼけていた。
https://datahub.io/organization/jp-textbook
Organization作成まではできているので、データセットを入力する。

**Comment by masao** [comment]
というわけで、Datahubにデータセットを追加しました：
https://datahub.io/dataset/jp-textbook

**Comment by masao** [comment]
こちらでできることは完了済み。http://lod-cloud.net/ の更新を待つのみ。
現時点の最新版は 2017-02-20 付。

**Comment by masao** [comment]
2018年4月版が公開されたが、データセット追加方法はメンテナにメール連絡ということに替わってしまった模様。。。

**Comment by masao** [comment]
新しい登録サイトが動き始めたようなので、登録してみました：
https://lod-cloud.net/dataset/jp-textbook

**Comment by yegusa** [comment]
確認しました！長かったですね。クローズします。

![40253127_2003191576406960_6235191937012334592_n](https://user-images.githubusercontent.com/1328499/44767963-aec10a00-ab9a-11e8-80c4-4b4bad3b36e0.png)
