### ISSUE TITLE
教科の英語名をHTMLで表示する

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#120]
#104 で教科に英語名を付けたので、HTMLでも表示してほしい

現在：
https://w3id.org/jp-textbook/curriculum/小学校/2011/国語
![image](https://user-images.githubusercontent.com/1328499/31153138-666c18e4-a8da-11e7-9c50-d2f2d0da5f36.png)

**Comment by masao** [comment]
#251 にともなって、完了のはず。

**Comment by yegusa** [comment]
確認しました。クローズします。
