### ISSUE TITLE
教科のよみをHTMLで表示する

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#121]
#65 で教科に「よみ」を付けたので、HTMLでも表示してほしい

現在：
https://w3id.org/jp-textbook/curriculum/小学校/2011/国語
![image](https://user-images.githubusercontent.com/1328499/31153138-666c18e4-a8da-11e7-9c50-d2f2d0da5f36.png)

**Comment by masao** [comment]
教科ページによみを表示するようにしました。

**Comment by yegusa** [comment]
確認しました。クローズします。

![linked open data lod](https://user-images.githubusercontent.com/1328499/31303948-dab99a5e-ab51-11e7-840e-014ad48ab157.png)
