### ISSUE TITLE
種目のよみをHTMLで表示する

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#122]
#66 で種目に「よみ」を付けたので、HTMLでも表示してほしい

現在：
https://w3id.org/jp-textbook/curriculum/小学校/2011/国語/書写
![image](https://user-images.githubusercontent.com/1328499/31153374-e07d42ec-a8db-11e7-8a24-0be5ba2e410e.png)

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
確認しました。クローズします。

![image](https://user-images.githubusercontent.com/1328499/31314753-e62ef8f0-ac43-11e7-8fce-9e1016af0ab2.png)
