### ISSUE TITLE
種目の英語名をHTMLで表示する

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#124]
#123 で種目に「英語名」を付けたので、HTMLでも表示してほしい

現在：
https://w3id.org/jp-textbook/curriculum/小学校/2011/国語/書写
![image](https://user-images.githubusercontent.com/1328499/31153374-e07d42ec-a8db-11e7-8a24-0be5ba2e410e.png)

**Comment by masao** [comment]
#252 にあわせて英語部分は対応済み。

**Comment by yegusa** [comment]
確認しました。クローズします。
