### ISSUE TITLE
高等学校の専門教科（商業など）の「種目」の英語名を追加する

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#125]
（優先度：低い？）

現在、高等学校の専門の「種目」の英語名は、

典拠がない
量が多い

ため、入力できていません。

ただ、教科書書誌データで、当該種目は空欄となっている種目のため、
トップページにも表示されません（教科を表示につかっています）
ですので、優先度は低いかと思いますが、備忘録として登録しておきます。

**Comment by yegusa** [comment]
いいのを見つけました。

「幼稚園、小学校、中学校、高等学校及び特別支援学校の学習指導要領等の改善について（答申）」の英訳
　→「 Concerning improvements to the courses of study for elementary, lower secondary and upper secondary schools」
https://www.nier.go.jp/04_kenkyu_annai/pdf/improvement_of_the_courses_of_study.pdf

これの、8章に教科や科目がある！新しいのはこれが使えそう！

ref. 新しい学習指導要領の英訳がみたい
http://crd.ndl.go.jp/reference/detail?page=ref_view&id=1000067720

**Comment by yegusa** [comment]
上のコメントの答申から作成したデータを追加しました。また、残りは100強だったため、江草が独自に翻訳して英語データを追加したものを作成しました。

subject-20180729.ttl として7.2系フォルダに入れてあります。
@masao 確認ください。

**Comment by masao** [comment]
以下の種目の英語名の先頭に改行記号が入っていて、手元のパーサではエラーになってしまいます。

* https://w3id.org/jp-textbook/curriculum/高等学校/1994/農業/林業経営 
* https://w3id.org/jp-textbook/curriculum/高等学校/1994/農業/農業水利
* https://w3id.org/jp-textbook/curriculum/高等学校/2003/工業/ソフトウェア技術
* https://w3id.org/jp-textbook/curriculum/高等学校/2003/工業/社会基盤工学

**Comment by yegusa** [comment]
@masao 7.2系/subject-20180730.ttl 修正し直したものを作りました。確認ください。

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
subject-20180730.ttlですね。
あとは、htmlも　例： https://w3id.org/jp-textbook/en/curriculum/高等学校/2013/福祉/社会福祉基礎
確かめました。

クローズします。
