### ISSUE TITLE
recordedBy を直す

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#14]
- 現在 textbook:recordedBy <https://w3id.org/jp-textbook/catalogue/中学校/2004>
- 新 textbook:catalogue <https://w3id.org/jp-textbook/catalogue/中学校/2004>

**Comment by masao** [comment]
Turtle生成までは確認した。
あとは、ウェブサイトのほうの再構築できることをしたら、リリースする。

**Comment by yegusa** [comment]
textbook:catalogue <https://w3id.org/jp-textbook/catalogue/中学校/1992>;

というように修正されたのを確認したので、クローズする。
