### ISSUE TITLE
教科書目録のページ（HTML）の年は和暦も載せてほしい

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#143]
確認時など、実物には、和暦が載っているので、和暦が表示されていると助かる。

現状：
https://w3id.org/jp-textbook/catalogue/高等学校/2012
![image](https://user-images.githubusercontent.com/1328499/31324486-eedb5df4-aced-11e7-8e8c-3c11729915d8.png)

**Comment by masao** [comment]
和暦を追加しました。

**Comment by yegusa** [comment]
確認しました。クローズします。

![image](https://user-images.githubusercontent.com/1328499/31605021-14d7cfa8-b2a0-11e7-9da7-2225c43f2a7e.png)
