### ISSUE TITLE
教科書目録のラベルは「教科書目録掲載年度」が使用年度なのか発行年なのか分かりやすいラベルにしてほしい

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#144]
使用年度なのか、発行年なのか、わかりずらいので、わかりやすいラベルにしてほしい。

案：
- 掲載教科書目録発行年
- 初出の教科書目録の発行年

現在：
https://w3id.org/jp-textbook/高等学校/2012/国総/301
![image](https://user-images.githubusercontent.com/1328499/31324558-d163ba9a-acee-11e7-830d-95c83fe601e1.png)

**Comment by masao** [comment]
「初出教科書目録の発行年」というラベルに修正しました。

**Comment by yegusa** [comment]
確認しました。クローズします。

![image](https://user-images.githubusercontent.com/1328499/31604974-e88f985e-b29f-11e7-849d-29d9afaa9c7c.png)
