### ISSUE TITLE
学習指導要領のページ（HTML)に和暦も表示してほしい

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#145]
実物は和暦なので、確認時などにつらいので、和暦も表示してほしい

現在：
https://w3id.org/jp-textbook/curriculum/高等学校/2013
![image](https://user-images.githubusercontent.com/1328499/31324587-2bae3534-acef-11e7-8805-9fd726192ad5.png)

**Comment by masao** [comment]
詳細セクションを作って、そこに入れ込む。

**Comment by masao** [comment]
追加しました。

**Comment by masao** [comment]
一部データ更新忘れていた分を、追加しました。

**Comment by yegusa** [comment]
確認しました。できていると思うので、クローズします。

![image](https://user-images.githubusercontent.com/1328499/33513424-ebeca2c0-d785-11e7-819b-698c23be208b.png)
