### ISSUE TITLE
教科のページ(HTML)に和暦も表示してほしい

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#146]
和暦を確認したいことが多いの表示しておいてほしい

https://w3id.org/jp-textbook/curriculum/高等学校/2013/国語
![image](https://user-images.githubusercontent.com/1328499/31324679-28ffabf0-acf0-11e7-95d1-c75a5e9a359f.png)

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
確認しました。よいとおもいます。クローズします。

![image](https://user-images.githubusercontent.com/1328499/31572477-0708fec0-b0e2-11e7-9263-e41e9d7ddbce.png)
