### ISSUE TITLE
教科書研究センターの「目録レコード番号」をttlに追加する

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#152]
教科書研究センターからいただいた書誌からttlに追加可能です。
@prefix textbook-rc: <http://dl.nier.go.jp/library/vocab/textbook-rc>.
textbook-rc:recordID "120040001"

ってかんじでしょうか？

ちなみに、教育図書館の場合：
@prefix nier: <http://dl.nier.go.jp/library/vocab/>.
  nier:recordID "EB10012535"

また、教科書研究センターのOPACの検索結果へは、以下のようなリンクができるっぽいです。

以下のどちらか
a) http://textbook-rc-lib.net/dl/SsaOkobBIBy2ftPelVbXwTJqTVi?free_word=120040001
b) http://textbook-rc-lib.net/Opac/search.htm?s=SsaOkobBIBy2ftPelVbXwTJqTVi&ncid=120040001

a) のほうがよさそう。

**Comment by yegusa** [comment]
とりあえず、データは5.3系フォルダにいれておきます

**Comment by yegusa** [comment]
ttlにできる準備終了。 6.0系フォルダにいれておきました。

**Comment by masao** [comment]
データ処理の方針：
1. Turtle生成スクリプトは教育図書館とは別にしておく。
2. （場合によっては）Turtleファイルも別にしてしまってよい。

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
こんなかんじですね。いいと思います。確認しましたので、クローズします。

@prefix textbook-rc: <http://dl.nier.go.jp/library/vocab/textbook-rc/>.

<https://w3id.org/jp-textbook/中学校/2005/保体/704> a schema:Book;
  textbook:item [
  textbook-rc:callNumber "B2|600|H17/18";
  textbook-rc:recordID "220050110"
  ];
  schema:isbn "4-487-12120-5".
