### ISSUE TITLE
HTML:教科書研究センターの「目録レコード番号」にリンクを張る

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#153]
#152 の次にやる

**Comment by yegusa** [comment]
a) 目録レコード番号の検索結果（詳細画面）
![image](https://user-images.githubusercontent.com/1328499/31695174-eea121fa-b3e3-11e7-9c95-bd8b86fc57dd.png)

b) 目録番号で検索した結果（検索結果一覧）
![image](https://user-images.githubusercontent.com/1328499/31695132-9a8ae88a-b3e3-11e7-9f11-a4d37a58d585.png)

c) 個々の所蔵レコード
http://textbook-rc-lib.net/dl/SsaOkobBIBy2ftPelVbXwTJqTVi?free_word=220150089
![image](https://user-images.githubusercontent.com/1328499/31695219-3c414782-b3e4-11e7-9d99-dad57da990d6.png)

a) にリンクを張れるとよいのだけど、パーマリンクができるか不明
b) でもよい。
c) ならできる。

参考：
教科書研究センターの検索ページ　ここで、「目録レコード番号」を「フリーワード」の
ところに入れて検索とするとよい
http://textbook-rc-lib.net/Opac/search.htm?s=-cKZ-xZqMVYzA_3dOR9fO1zB6wh

**Comment by yegusa** [comment]
現在、 a) の方法を教育図書館から問い合わせ中。

**Comment by yegusa** [comment]
a), b) はできないそうです。
c) にするしかないかな。

**Comment by yegusa** [comment]
url はこういうのもあるのか。
http://textbook-rc-lib.net/Opac/search.htm?s=SsaOkobBIBy2ftPelVbXwTJqTVi&ncid=220150089

**Comment by masao** [comment]
ひとまず追加しました。

**Comment by yegusa** [comment]
確認しました。良いと思いますので、クローズします。

https://w3id.org/jp-textbook/高等学校/2012/国総/301

の場合は、

http://textbook-rc-lib.net/Opac/search.htm?s=SsaOkobBIBy2ftPelVbXwTJqTVi&ncid=320120001

ってかんじですね。

![image](https://user-images.githubusercontent.com/1328499/33537715-71c53ba2-d900-11e7-971e-3a82282f0b81.png)
