### ISSUE TITLE
書誌データ（タイトル）誤り?「古典 漢文編」→「古典B 漢文編」？

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#162]
- [x] 教育図書館に連絡
- [x] 元データ修正
- [x] データ修正確認
- [x] データ入手

https://jp-textbook.github.io/高等学校/2013/古B/311 において
タイトルが「古典 漢文編」となっているが、実際の書籍をみると、「古典B 漢文編」となっているように見える。

**Comment by masao** [comment]
https://jp-textbook.github.io/高等学校/2013/古B/312
https://jp-textbook.github.io/高等学校/2013/古B/313 においても同様と思われる。。。

**Comment by julia0402** [comment]
![2017-10-30 20 56 38](https://user-images.githubusercontent.com/25675929/32259959-cc19e6ce-bf07-11e7-872d-b18f8d533567.jpg)
![2017-10-30 21 25 04](https://user-images.githubusercontent.com/25675929/32259960-cf00a0b2-bf07-11e7-9b21-6285556bf1ed.jpg)
![2017-10-30 21 31 31](https://user-images.githubusercontent.com/25675929/32259962-d240ae0c-bf07-11e7-9d60-07fbdf6be217.jpg)

すみませんが、遅くなっておりますが、
教科書coverの写真をアップロードしております。
よろしくお願いします。

**Comment by yegusa** [comment]
教育図書館に連絡しておきました。 2017-11-14

**Comment by yegusa** [comment]
全て、タイトルに B を追加したそうです。

**Comment by yegusa** [comment]
NIEROPAC上で、全て、タイトルに B を追加されたことを確認しました。

https://nieropac.nier.go.jp/ebopac/EB16240840
https://nieropac.nier.go.jp/ebopac/EB16240841
https://nieropac.nier.go.jp/ebopac/EB16240842

**Comment by yegusa** [comment]
2017-11-16 教育図書館からデータ入手しました(list_EB20171116.txt)。まだ、ttlにできるデータの準備はできていません。

**Comment by yegusa** [comment]
ttlにできる準備終了。 6.0系フォルダにいれておきました。

**Comment by yegusa** [comment]
2017-11-30 の打ち合わせにより、やはり、5.2系としてリリースすることに
5.2系_新フォルダにいれておきました。

**Comment by yegusa** [comment]
全て、B が追加されていることを確認しました。ので、クローズします。

https://jp-textbook.github.io/高等学校/2013/古B/311
https://jp-textbook.github.io/高等学校/2013/古B/312
https://jp-textbook.github.io/高等学校/2013/古B/313
