### ISSUE TITLE
ISBNとopenurlを使ってCiNii Books にリンク

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#168]
#166 と関連

http://ci.nii.ac.jp/books/openurl/query?isbn=9784487100118

HTMLで表示するときに、openurlを使ってリンクはる。
ttlファイルにデータ変更はなし データ追加的な話は　#166

**Comment by yegusa** [comment]
つまり、 a) も b) も検定年は 2005年にし、
b) は、教育図書館のレコードとは違う、初出の教科書目録とは違う、現物を優先の旨、注記に書く感じで。

a) 教育図書館：検定年2005年
https://w3id.org/jp-textbook/高等学校/2006/理A/014
https://w3id.org/jp-textbook/高等学校/2006/理A/015
https://w3id.org/jp-textbook/高等学校/2006/理A/016
https://w3id.org/jp-textbook/高等学校/2006/理B/016
https://w3id.org/jp-textbook/高等学校/2006/理B/017
https://w3id.org/jp-textbook/高等学校/2006/理A/011
https://w3id.org/jp-textbook/高等学校/2006/理A/012
https://w3id.org/jp-textbook/高等学校/2006/理A/013
https://w3id.org/jp-textbook/高等学校/2006/理B/018
https://w3id.org/jp-textbook/高等学校/2006/理B/019


b) 教育図書館：検定年2006年 & 注記で現物は2005年
https://w3id.org/jp-textbook/高等学校/2006/理A/017
https://w3id.org/jp-textbook/高等学校/2006/理A/018
https://w3id.org/jp-textbook/高等学校/2006/理A/019
https://w3id.org/jp-textbook/高等学校/2006/理B/013
https://w3id.org/jp-textbook/高等学校/2006/理B/014
https://w3id.org/jp-textbook/高等学校/2006/理B/015
https://w3id.org/jp-textbook/高等学校/2006/理A/020
https://w3id.org/jp-textbook/高等学校/2006/理A/021
https://w3id.org/jp-textbook/高等学校/2006/理B/010
https://w3id.org/jp-textbook/高等学校/2006/理B/011
https://w3id.org/jp-textbook/高等学校/2006/理B/012

**Comment by masao** [comment]
リンクを追加しました。

**Comment by yegusa** [comment]
確認しました。良いと思いますので、クローズします。

https://w3id.org/jp-textbook/高等学校/2012/国総/301

の場合は、

http://ci.nii.ac.jp/books/openurl/query?isbn=978-4-487-18701-0

ってかんじですね。

![image](https://user-images.githubusercontent.com/1328499/33537715-71c53ba2-d900-11e7-971e-3a82282f0b81.png)
