### ISSUE TITLE
書名が半角カタカナになっているもの

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#170]
- [x] 教育図書館に連絡
- [x] NIEROPACデータ修正
- [x] NIEROPAC 修正確認
 
以下の教科書情報において、書名に半角カナがはいっている：

* https://w3id.org/jp-textbook/高等学校/2003/商業/016
* https://w3id.org/jp-textbook/高等学校/2003/地図/007
* https://w3id.org/jp-textbook/高等学校/2003/日A/007

**Comment by yegusa** [comment]
教育図書館に連絡して修正してもらうことにします。

**Comment by yegusa** [comment]
教育図書館に連絡しておきました。

NIER　OPAC へのリンク
https://nieropac.nier.go.jp/ebopac/EB10026114
https://nieropac.nier.go.jp/ebopac/EB10025955
https://nieropac.nier.go.jp/ebopac/EB10025922

**Comment by yegusa** [comment]
修正連絡きました。NIEROPACのデータは、修正されていることを確認ずみです。

**Comment by yegusa** [comment]
データを2018-02-08に入手しました。6.1系のフォルダに置いていますのでいつでもupOKです。
→ @masao よろしく。

**Comment by yegusa** [comment]
できていることを確認したのでクローズします。
