### ISSUE TITLE
文字化けと思われる著者名データあり

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#173]
#113 からの派生。

- [x] 教育図書館に連絡
- [x] NIEROPACデータ修正
- [x] NIEROPAC 修正確認

以下、教育図書館OPAC上でも文字化けている著者名データあり：

* https://nieropac.nier.go.jp/ebopac/EB10026059
* https://nieropac.nier.go.jp/ebopac/EB10026060
* https://nieropac.nier.go.jp/ebopac/EB10026061
* https://nieropac.nier.go.jp/ebopac/EB10026005
* https://nieropac.nier.go.jp/ebopac/EB10026006
* https://nieropac.nier.go.jp/ebopac/EB10026007
* https://nieropac.nier.go.jp/ebopac/EB10026008
* https://nieropac.nier.go.jp/ebopac/EB10026009
* https://nieropac.nier.go.jp/ebopac/EB10026010
* https://nieropac.nier.go.jp/ebopac/EB10026011

**Comment by yegusa** [comment]
教育図書館に連絡しておきました　2017-12-02

**Comment by yegusa** [comment]
https://w3id.org/jp-textbook/高等学校/2003/工業/069
https://w3id.org/jp-textbook/高等学校/2003/工業/074
https://w3id.org/jp-textbook/高等学校/2003/工業/077
https://w3id.org/jp-textbook/高等学校/2003/数B/001
https://w3id.org/jp-textbook/高等学校/2003/数B/002
https://w3id.org/jp-textbook/高等学校/2003/数C/001
https://w3id.org/jp-textbook/高等学校/2003/数C/002
https://w3id.org/jp-textbook/高等学校/2003/数II/001
https://w3id.org/jp-textbook/高等学校/2003/数II/002
https://w3id.org/jp-textbook/高等学校/2003/数II/003

**Comment by yegusa** [comment]
![image](https://user-images.githubusercontent.com/1328499/33511920-7733bae4-d768-11e7-84e4-9bb8d74ddd3f.png)

**Comment by yegusa** [comment]
修正連絡きました。

崎
高

だったようですね。

NIEROPACでは修正されたようです。確認済みです。

**Comment by yegusa** [comment]
データを2018-02-08に入手しました。6.1系のフォルダに置いていますのでいつでもupOKです。
→ @masao よろしく。
