### ISSUE TITLE
【学習指導要領ttl】学習指導要領の施行年が年月日になっている、年だけにするか検討→年月日のまま

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#18]

**Comment by yegusa** [comment]
もう一度確認して、「年月日」のままでいいことにする。

- [ ] データの確認

**Comment by yegusa** [comment]
2012年施行の指導要領が4月2日になっているのでこれでいいかどうか確かめる

**Comment by masao** [comment]
@yegusa http://www.mext.go.jp/a_menu/shotou/new-cs/youryou/1304424.htm こちらです。

**Comment by yegusa** [comment]
http://www.mext.go.jp/a_menu/shotou/new-cs/youryou/chu/__icsFiles/afieldfile/2010/12/16/121504.pdf

iiiページなどに「附 則
この省令は、平成二十年四月一日から施行する。ただし、第五十条、第五十一
条及び別表第一の改正規定は平成二十三年四月一日から、第七十二条、第七十三
条、第七十六条、第百七条、別表第二及び別表第四の改正規定は平成二十四年四
月一日から施行する。」とあるので、4月1日で正しいはず。

**Comment by yegusa** [comment]
Excelデータは修正してあるのを確認済み。

**Comment by yegusa** [comment]
年月日のままとするので、こちらはクローズする。
