### ISSUE TITLE
語彙スキーマを機械可読として書く

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#182]

**Comment by yegusa** [comment]
参考： 2018-07-27 FRBR&RDA勉強会 https://docs.google.com/document/d/14QvftD3Zm7ZZLhO7RZoIFGgNxMdh0nvm1D8dYhIT88k/edit

**Comment by masao** [comment]
追加しました。

**Comment by masao** [comment]
HTML表現も追加しました:

* http://w3id.org/jp-textbook/Textbook
* http://w3id.org/jp-textbook/school

**Comment by yegusa** [comment]
https://jp-textbook.github.io/schema-20180913.ttl
は確認しました。

- http://w3id.org/jp-textbook/Textbook
- http://w3id.org/jp-textbook/school

も確認しました。

良いと思います。
これ、どこからもリンクされてないから、aboutあたりからリンクしておくといいですね。
別issueにあげておきましょう。
