### ISSUE TITLE
個別の教科書のページの英語UIを考える

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#188]
#90 から派生

**Comment by yegusa** [comment]
翻訳

詳細情報
More Information 
 
編著者  Author or Editor
教科 / 種目 Subject Area / Subject
使用学年 Grade
大きさ Dimensions
ページ数 Extent
ISBN ISBN
使用年度 Usage Year
検定年 Authorized Year
初出教科書目録の発行年 the First Year of Catalogue
学習指導要領 Curriculum Guideline
 
関連リンク Links


国立教育政策研究所 教育図書館 OPAC K260.8||T8||2011
NIER Library of Education OPAC

教科書研究センター附属教科書図書館 OPAC B2|111|H23/24
Textbook Library, Japan Textbook Research Center OPAC

国立国会図書館サーチ NDL Search

CiNii Books

カーリル Calil

© 2017 教科書LODプロジェクト
© 2017 Japanese Textbook LOD Project

**Comment by masao** [comment]
一通り追加しました。

**Comment by yegusa** [comment]
確認しました。

https://w3id.org/jp-textbook/小学校/2010/国語/101
![japanese textbook linked open data lod](https://user-images.githubusercontent.com/1328499/42899868-489908e4-8b02-11e8-9fb2-4cf58726bf48.png)
