### ISSUE TITLE
請求記号を表示してほしい

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#19]
https://jp-textbook.github.io/%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1/2012/%E3%82%B3I/306

例えば、↑の関連リンクの下あたりに。

データ確認や、デバッグに、請求記号が表示されていると助かるため。

![image](https://cloud.githubusercontent.com/assets/1328499/25059437/b3a8b2b6-21c1-11e7-9b3f-82b929410439.png)

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
ありがとうございます！

できたことを確認しましたので、クローズします。
