### ISSUE TITLE
教科のページの英語UIを考える

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#190]
#90 から派生

例
https://jp-textbook.github.io/curriculum/%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1/2013/%E6%B0%B4%E7%94%A3/

**Comment by yegusa** [comment]
翻訳

詳細情報
Other Information 

学校種別　School Type
学習指導要領 Curriculum guideline
教科 Subject Area
出典 Reference

教科書一覧 List of Textbooks


© 2017 教科書LODプロジェクト
© 2017 Japanese Textbook LOD Project

**Comment by masao** [comment]
一通り英語ページを追加しました。

**Comment by yegusa** [comment]
確認しました

https://jp-textbook.github.io/en/curriculum/%E5%B0%8F%E5%AD%A6%E6%A0%A1/2011/%E5%9B%BD%E8%AA%9E/

![japanese textbook linked open data lod](https://user-images.githubusercontent.com/1328499/42900028-c8116576-8b02-11e8-9428-6e4459b28497.png)
