### ISSUE TITLE
Turtleリソースの展開：種目、科目、指導要領、教科書目録

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#192]
#103 からの派生

* [x] 学習指導要領
* [x] 種目
* [x] 科目
* [x] 教科書目録

**Comment by masao** [comment]
プログラム側の対応は完了。 7.0リリース時にあわせて確認すること。

**Comment by yegusa** [comment]
チェック例

- [ ] 学習指導要領 https://w3id.org/jp-textbook/curriculum/小学校/2011.ttl
- [ ] 種目 https://w3id.org/jp-textbook/curriculum/高等学校/2013/地理歴史/世界史A.ttl
- [ ] 教科 https://w3id.org/jp-textbook/curriculum/高等学校/2013/地理歴史.ttl
- [ ] 教科書目録 https://w3id.org/jp-textbook/catalogue/小学校/2010.ttl

**Comment by yegusa** [comment]
確認しました。クローズします。
