### ISSUE TITLE
INFOSTA論文を機関リポジトリに登録

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#196]
江草由佳, 高久雅生. 教科書Linked Open Data（LOD）の構築と公開. 情報の科学と技術, vol.68, no.7, pp.361-367 (2018-07)
DOI https://doi.org/10.18919/jkg.68.7_361

**Comment by masao** [comment]
さきほど筑波大学附属図書館にリポジトリ登録を依頼しました。

**Comment by masao** [comment]
http://hdl.handle.net/2241/00152209 登録されました。

**Comment by yegusa** [comment]
確認しました。
