### ISSUE TITLE
教科・種目の詳細ページを追加

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#2]
- [x] 教科：データの作成(excel)
- [x] 教科：プロパティの検討・決定
- [x] 教科：ttlの作成
- [x] 教科：プログラム開発
- [x] 種目：データの作成(excel)
- [x] 種目：プロパティの検討・決定
- [x] 種目：ttlの作成
- [x] 種目：プログラム開発
https://jp-textbook.github.io/curriculum/小学校/2012/%E5%B0%8F%E5%AD%A6%E6%A0%A1/2002/%E7%90%86%E7%A7%91 などの種目に関する詳細ページを追加すること

以下、とりあえず、今は、科目はやらない
<s>
- 科目：データの作成(excel)
- 科目：プロパティの検討・決定
- 科目：ttlの作成
- 科目：プログラム開発
</s>

**Comment by yegusa** [comment]
URIは、「種別」と「科目」と共通とする

**Comment by yegusa** [comment]
- 教科 -- skos:narrower --> 科目
- 教科 -- skos:narrower --> 種目　（保険体育についても、意味的には気持ち悪いがnarrower でよいことにする）

**Comment by yegusa** [comment]
検討事項で残っていることメモ

- 科目の rdf:type はどうするか？
- 種目の rdf:type はどうするか？

**Comment by yegusa** [comment]
科目の「共通」や「専門」を表すプロパティやリソースURIについては、
種目 -- textbook:subjectType --> textbook:curriculum/Subject/Common （もしくは Special）
でとりあえずいこうと打ち合わせ(2017-05-08）できめた

**Comment by yegusa** [comment]
2017-05-15 打ち合わせ結果

- 科目をつくるかどうか再検討
- 種目はできればトップダウンでつくりたいが、情報源の入手が困難そうなら、しかたなくボトムアップでつくるしかないだろう
- もし、科目を作る場合は、互換性に気を付けつつ、科目と種目がわけわからないようにする

**Comment by yegusa** [comment]
「種目」は「教科用図書検定申請受理種目」という公文書があるので、それからトップダウンで作れることが判明。古いものも、「官報」でみることができる。

教育図書館にレファレンスして、古い「教科用図書検定申請受理種目」を入手しました。

- 前々回の学習指導要領に対応　(1989年6月）; 官報　平成元年 6月9日 114号; 文部省告示 第89号
- 前回の学習指導要領に対応（1999年7月）教科用図書検定申請受理種目 http://www.mext.go.jp/a_menu/shotou/kyoukasho/kentei/990701.htm
- 現行の学習指導要領に対応 （2010年5月）教科用図書検定申請受理種目http://www.mext.go.jp/a_menu/shotou/kyoukasho/kentei/1293732.htm

**Comment by yegusa** [comment]
種目：例：古典I -- see also --> 教科書図書検定申請受理種目表リソース　とする　2017-05-23 打ち合わせで決めた

**Comment by yegusa** [comment]
教科用図書検定申請受理種目（表由来）

教科 -- hasSubject --> 受理種目　

2017-05-23 打ち合わせできめた

**Comment by masao** [comment]
Github Pages上のページ配置としては以下のようにすることで対応予定：

* 教科： curriculum/小学校/1992/国語/index.html
* 種目： curriculum/小学校/1992/国語/国語.html

**Comment by masao** [comment]
一通り種目ページを追加しました。あわせて、これまでの教科書ページ一覧を廃止して、種目ページで代用することとします。

**Comment by yegusa** [comment]
教科のページ、種目のページ両方とも、問題ないことを確認したのでクローズする

教科： curriculum/小学校/1992/国語/index.html
![image](https://user-images.githubusercontent.com/1328499/30509735-63f5e32e-9af2-11e7-8731-ad00eef481b0.png)

種目： curriculum/小学校/1992/国語/国語.html
![image](https://user-images.githubusercontent.com/1328499/30509738-76f118e0-9af2-11e7-8fb9-57a853cd05f0.png)
