### ISSUE TITLE
HTTPS対応: 画像差し替え

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#201]
PDアイコンが http 経由なため、URL欄にて「保護されていない接続」という警告がでるブラウザあり。

![image](https://user-images.githubusercontent.com/38825/42507284-8b9a4cc2-847f-11e8-8f61-4753922c5494.png)

**Comment by masao** [comment]
対応しました。

**Comment by yegusa** [comment]
これ、どのブラウザ使えば確かめられます？

**Comment by masao** [comment]
どのブラウザでも大丈夫です。

**Comment by yegusa** [comment]
保護された通信　と出たので大丈夫かと思います。クローズします。

![2018-07-20 16 45 03](https://user-images.githubusercontent.com/1328499/42989972-4fe2df9a-8c3c-11e8-9b15-b8b5f9d0b037.png)
