### ISSUE TITLE
教科書目録の「NCID」をttlに追加

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#206]
教科書目録の教科書目録. 特別支援学校用(小・中学部)のNCIDが10件ほど間違えていたので、修正する（ただ、今の教科書LODには関連する教科書レコードはない）

**Comment by yegusa** [comment]
修正しました。7.0系フォルダに入れておきました。

**Comment by yegusa** [comment]
@masao catalogue-20180713.ttl です。確認よろしく。

**Comment by yegusa** [comment]
NCIDはそもそもttlに書き出していなかったので、このissueは、教科書目録にNCIDを書き出すissueに変更する。

**Comment by yegusa** [comment]
どう表現すれば良いか？

**Comment by yegusa** [comment]
こんな感じで良いことにした

rdfs:seeAlso https://ci.nii.ac.jp/ncid/BA79414612

**Comment by yegusa** [comment]
作成しました。curriculum-20180723.ttl として、7.1系フォルダに入れています。
@masao 確認ください。

**Comment by masao** [comment]
#207 とあわせて対応させました。

**Comment by yegusa** [comment]
catalogue-20180727.ttl ですね。確認しましたので、クローズします。
