### ISSUE TITLE
教科書目録の「JP番号」をttlに追加 

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#207]
#206 と類似。JP番号の方も同様に修正する

**Comment by yegusa** [comment]
@masao 確認よろしく。

**Comment by yegusa** [comment]
あー、JP番号は、ttlに書き出してなかったのですね。では、JP番号をttl に書き出すっていうissueに変更することにします。

**Comment by yegusa** [comment]
どう表現すれば良いか？

http://dl.nier.go.jp/library/vocab/ndl/recordID とか？
http://dl.nier.go.jp/library/vocab/ndl/JPNO とか？

**Comment by yegusa** [comment]
これで良いことにしました：

rdfs:seeAlso http://id.ndl.go.jp/jpno/21857937

ref: 
http://www.ndl.go.jp/jp/dlib/standards/meta/dcndl_examples.html
全国書誌番号（JP番号）

**Comment by yegusa** [comment]
作成しました。curriculum-20180723.ttl として、7.1系フォルダに入れています。
@masao 確認ください。

**Comment by masao** [comment]
入っている値がJP番号ではなく、NDL書誌IDになっているようです。

例：https://ndlonline.ndl.go.jp/#!/detail/R300000001-I000008553025-00 
* JPNO: 01015610
* 国立国会図書館書誌ID: 000008553025

**Comment by yegusa** [comment]
修正しました。7.1系フォルダに入れておきました。
catalogue-20180727.ttl です。 @masao 確認等よろしく。

**Comment by masao** [comment]
対応しました。

**Comment by yegusa** [comment]
catalogue-20180727.ttl ですね。確認しましたので、こちらクローズします。
