### ISSUE TITLE
学校種別のリソースを作る（英語化対応関係）

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#210]
昨日すこし確認したところでは、学校種別に英語名を付けるのが意外と面倒かも
別リソースをつくってしまうほうがよさげ、、かも。
Textbook ---(textbook:school)---> dbpedia-ja:高等学校 ---(owl:sameAs)---> dbpedia:High_school
みたいな構造。
dbpedia側の情報を取り出さないといけない。

 by @masao

**Comment by yegusa** [comment]
URI: textbook:school/高等学校

dbpedia とはowl:saveAs としておく

**Comment by yegusa** [comment]
作りました。7.0系フォルダに school-20180713.ttl として置いています

**Comment by masao** [comment]
school-20180713.ttlを追加しました。
