### ISSUE TITLE
学校種別のURIを変更：「教科書」 textbook.ttlを修正

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#215]
#210 から派生。

**Comment by yegusa** [comment]
textbook-2018-07-15.ttl を確認しました。できていると思います。
クローズします。

例：
  textbook:school <https://w3id.org/jp-textbook/school/中学校>;
これですね。

レコード全体例：
<https://w3id.org/jp-textbook/中学校/1992/保体/701> a schema:Book;
  schema:name "新しい保健体育(中学校全)";
  schema:editor "秋山 房雄，笠井 恵雄，斎藤 キ能，ほか１４名";
  schema:publisher "東京書籍株式会社";
  textbook:item [
  nier:callNumber "K260.49||T8N||92/93";
  nier:recordID "EB10012620"
  ];
  textbook:catalogue <https://w3id.org/jp-textbook/catalogue/中学校/1992>;
  textbook:school <https://w3id.org/jp-textbook/school/中学校>;
  textbook:subjectArea <https://w3id.org/jp-textbook/curriculum/中学校/1993/保健体育>;
  textbook:subject <https://w3id.org/jp-textbook/curriculum/中学校/1993/保健体育/保健体育>;
  textbook:grade "1,2,3";
  textbook:curriculum <https://w3id.org/jp-textbook/curriculum/中学校/1993>;
  textbook:authorizedYear "1992";
  textbook:usageYear "1993-1996";
  bf:extent "160";
  bf:dimensions "B5";
  textbook:textbookSymbol "保体";
  textbook:textbookNumber "701".
