### ISSUE TITLE
英語ページのタイトル修正：教科書 Linked Open Data (LOD)

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#216]
- [x] トップ
- [x] about
- [x] 教科書
- [x] 教科書目録
- [ ] 学習指導要領
- [ ] 教科
- [x] 種目

titleタグ内が「（ページタイトル） | 教科書 Linked Open Data (LOD)」となっているので、サイト名称を Japanese Textbook Linked Open Data (LOD) に変更する

**Comment by yegusa** [comment]
再オープンしましたが、別の問題（サイト名は英語になってる、個別ページ名が日本語）だったことに気づいたので、別issueとします。こちらはクローズします。
