### ISSUE TITLE
種目名の誤り「オーラルコミュニケーションI」

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#217]
- [x] 教育図書館に連絡 (2018-07-15メールにて連絡ずみ、2018-09-29に図書館にリマインドメール済み)
- [x] 教育図書館修正
- [x] 確認
- [x] データ入手

https://w3id.org/jp-textbook/高等学校/2002/オI/014 などに中黒抜きの「オーラルコミュニケーションI」となっているものあり。

正確には、「オーラル・コミュニケーションI」

（ #331 のチェックでも出現）

**Comment by yegusa** [comment]
以下の19件ですね。教育図書館に連絡しておきます。

https://nieropac.nier.go.jp/ebopac/EB10025723
https://nieropac.nier.go.jp/ebopac/EB10025722
https://nieropac.nier.go.jp/ebopac/EB10025721
https://nieropac.nier.go.jp/ebopac/EB10025720
https://nieropac.nier.go.jp/ebopac/EB10025732
https://nieropac.nier.go.jp/ebopac/EB10025731
https://nieropac.nier.go.jp/ebopac/EB10025729
https://nieropac.nier.go.jp/ebopac/EB10025728
https://nieropac.nier.go.jp/ebopac/EB10025730
https://nieropac.nier.go.jp/ebopac/EB10025726
https://nieropac.nier.go.jp/ebopac/EB10025727
https://nieropac.nier.go.jp/ebopac/EB10025725
https://nieropac.nier.go.jp/ebopac/EB10025738
https://nieropac.nier.go.jp/ebopac/EB10025737
https://nieropac.nier.go.jp/ebopac/EB10025724
https://nieropac.nier.go.jp/ebopac/EB10025736
https://nieropac.nier.go.jp/ebopac/EB10025734
https://nieropac.nier.go.jp/ebopac/EB10025735
https://nieropac.nier.go.jp/ebopac/EB10025733

**Comment by yegusa** [comment]
教科書LOD のURI

https://w3id.org/jp-textbook/高等学校/2002/オI/004
https://w3id.org/jp-textbook/高等学校/2002/オI/003
https://w3id.org/jp-textbook/高等学校/2002/オI/002
https://w3id.org/jp-textbook/高等学校/2002/オI/001
https://w3id.org/jp-textbook/高等学校/2002/オI/013
https://w3id.org/jp-textbook/高等学校/2002/オI/012
https://w3id.org/jp-textbook/高等学校/2002/オI/010
https://w3id.org/jp-textbook/高等学校/2002/オI/009
https://w3id.org/jp-textbook/高等学校/2002/オI/011
https://w3id.org/jp-textbook/高等学校/2002/オI/007
https://w3id.org/jp-textbook/高等学校/2002/オI/008
https://w3id.org/jp-textbook/高等学校/2002/オI/006
https://w3id.org/jp-textbook/高等学校/2002/オI/019
https://w3id.org/jp-textbook/高等学校/2002/オI/018
https://w3id.org/jp-textbook/高等学校/2002/オI/005
https://w3id.org/jp-textbook/高等学校/2002/オI/017
https://w3id.org/jp-textbook/高等学校/2002/オI/015
https://w3id.org/jp-textbook/高等学校/2002/オI/016
https://w3id.org/jp-textbook/高等学校/2002/オI/014

**Comment by yegusa** [comment]
教育図書館のデータ修正がされました、確認済みです。まだ、データはもらってません。

**Comment by yegusa** [comment]
教育図書館からデータを入手しました。2018-10-25付のデータです。list_EB20181025.txt です。まだ、学習指導要領URIをつけるなどの作業はしていません。

**Comment by masao** [comment]
修正を反映しました。

**Comment by yegusa** [comment]
確認しました。クローズします。
