### ISSUE TITLE
日英ページの双方向リンク化

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#219]
公開サイト英語化の初期実装では、「日本語」「English」リンクはそれぞれのトップページへのリンクになっているが、これを対応するページ間への双方向リンク化する。

- [x] トップ https://w3id.org/jp-textbook/
- [x] about https://w3id.org/jp-textbook/about
- [x] 教科書 https://w3id.org/jp-textbook/高等学校/2012/世A/301
- [x] 教科 https://w3id.org/jp-textbook/curriculum/高等学校/2013/地理歴史
- [x] 種目 https://w3id.org/jp-textbook/curriculum/高等学校/2013/地理歴史/世界史A
- [x] 学習指導要領 https://w3id.org/jp-textbook/curriculum/高等学校/2013
- [x] 教科書目録 https://w3id.org/jp-textbook/catalogue/高等学校/2012
- [ ] 学校（ #236 の後で） 

#90 からの派生。

**Comment by yegusa** [comment]
@masao これがされてないと、確認作業が厳しいので、早めにやってもらえると嬉しいです。

**Comment by masao** [comment]
一通り実装しました。

**Comment by yegusa** [comment]
確認しました。学校はまた後でやるので、とりあえずいいことにして、一旦クローズにします。
