### ISSUE TITLE
学習指導要領のページの英語版の<title>のページ名を英語化

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#220]
「小学校学習指導要領」を　Elementary School Curriculum Guideline　に
学習指導要領のページ　<title>小学校学習指導要領 - Japanese Textbook Linked Open Data (LOD)</title>
https://jp-textbook.github.io/en/curriculum/%E5%B0%8F%E5%AD%A6%E6%A0%A1/2011/

#216 から派生

**Comment by masao** [comment]
修正しました。
実際には https://github.com/jp-textbook/jp-textbook.github.io/commit/bb73d6809ab1e0169f06156a65d3f591a75b7225#diff-2f19567fd76b948b75ea06a40d6d73e2 にて。

**Comment by yegusa** [comment]
確認しました。クローズします。

例：
<title>Elementary School Curriculum Guideline - Japanese Textbook Linked Open Data (LOD)</title>
