### ISSUE TITLE
個別教科書のページの、教科書目録へのリンク先がenになっていない

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#222]
#216 をチェクしていて気づきました。

例：

https://w3id.org/jp-textbook/小学校/2010/国語/101 の英語ページ
https://w3id.org/jp-textbook/en/小学校/2010/国語/101
First issued catalogue の　2010　のリンク先が　en のページじゃない。

![japanese textbook linked open data lod 1](https://user-images.githubusercontent.com/1328499/42901600-f7ec5b44-8b06-11e8-825e-75cd57c3cadc.png)

**Comment by masao** [comment]
修正しました。

**Comment by yegusa** [comment]
確認しました。OKでした。クローズします。
