### ISSUE TITLE
トップページの種目一覧には、対応教科書を持つ教科も表示させるように変更

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#225]
#224 #83 からの派生。
トップページのリンク一覧は、種目を優先するため、種目が直接対応づいている教科書が存在する場合はその種目名を、種目に直接対応する教科書が無い場合は教科名を表示している。

この場合、両者が並存するケースで、教科が表示できない。

これを解決するため、いずれにしても対応づく教科書を持つ場合には、教科と種目のいずれをも表示するように修正する。

**Comment by masao** [comment]
ひとまずこちらに対応させました。

**Comment by yegusa** [comment]
家庭　だと、こんな感じね。　いいと思います。クローズします。

![linked open data lod](https://user-images.githubusercontent.com/1328499/42991312-288e5e70-8c40-11e8-854b-61dde54ea771.png)
