### ISSUE TITLE
詳細に全てのプロパティ情報を記載する（教科書リソース）

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#229]
タイトル、著者、出版社など、ヘッダ部で表示している内容も、詳細に書いておく。

- [ ] 教科書リソース　例 https://w3id.org/jp-textbook/高等学校/2012/国総/301
- [ ] 学習指導要領　例 https://w3id.org/jp-textbook/curriculum/高等学校/2013
- [ ] 教科書目録　例 https://w3id.org/jp-textbook/catalogue/高等学校/2012
- [ ] 教科　例 https://w3id.org/jp-textbook/curriculum/高等学校/2013/国語
- [ ] 種別　例 https://w3id.org/jp-textbook/curriculum/高等学校/2013/国語/国語総合

**Comment by masao** [comment]
まずは教科書リソースから。

**Comment by masao** [comment]
ひとまず、教科書について、すべてのプロパティ（item除く）を詳細セクションに表示するようにしました。

**Comment by yegusa** [comment]
教科書リソースについて、注記（備考）以外は、全て表示されていることを確認しました。英語版も確認しました。（注記（備考）は別issueあり #171 )

一旦クローズします。他のリソースは、それぞれissueを立てておきますね。

**Comment by yegusa** [comment]
補足：
プログラムで自動的に作成した注記が表示されてることは確認しました。

https://w3id.org/jp-textbook/中学校/2005/公民/910
