### ISSUE TITLE
英語化：教科書の関連リンク先を英語インタフェースのものにする

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#230]
- [x] NIER Library of Education OPAC （英語インタフェースないので、必要なし）
- [x] Textbook Library, Japan Textbook Research Center OPAC（英語インタフェースないので、必要なし）
- [ ] NDL Search 例： http://iss.ndl.go.jp/api/openurl?locale=en&isbn=978-4-487-10301-0
- [ ] CiNii Books　例：https://ci.nii.ac.jp/books/search/?advanced=true&isbn=978-4-487-10301-0&l=en
- [x] Calil （英語インタフェースないので、必要なし）

例：https://w3id.org/jp-textbook/en/小学校/2010/国語/101
![japanese textbook linked open data lod 2](https://user-images.githubusercontent.com/1328499/43018409-8e554954-8c94-11e8-894b-0d71bcf7ece3.png)

**Comment by masao** [comment]
NDLサーチ、CiNii Booksいずれも、一度そのサイト内で「English」を選択しておけば、同じURLであっても英語版が表示されるので、このリンク先の書き換えはやめておこうかと思います。
いかがでしょうか。

**Comment by yegusa** [comment]
そうですね。それでも良いと思います。では、一旦クローズします。
