### ISSUE TITLE
英語：about のデータセットの説明の英文を直したい

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#232]
The dataset is compiled from a collection of textbooks held and organized by NIER Education Library and Textbook Research Center Library for several decades. These catalogs can be searched through Textbook Database at the NIER Edution Library website.

をできれば直したい。

教育図書館の目録がベースになっていて、教科書センターからISBN部分をもらっていると表現できたらより正確（教科書センターにはあるが、教育図書館にはないものがあるため）。

**Comment by yegusa** [comment]
@masao こんな感じでどうでしょう。

The dataset is based on a collection of textbooks held and organized by NIER Library of Education for several decades. These catalogs can be searched through Textbook Database at the NIER Library of Education website. ISBNs of the dataset are from Textbook Research Center Library catalogs.

**Comment by masao** [comment]
確認。
