### ISSUE TITLE
学校リソースのWebページを作る

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#236]
- [x] https://w3id.org/jp-textbook/school/小学校
- [x] https://w3id.org/jp-textbook/school/中学校
- [x] https://w3id.org/jp-textbook/school/高等学校
- [x] https://w3id.org/jp-textbook/school/特別支援学校
- [x] https://w3id.org/jp-textbook/school/特殊教育諸学校

**Comment by masao** [comment]
ひとまず各ページを作成しました。

**Comment by yegusa** [comment]
良いと思います。クローズします。

例：
![linked open data lod](https://user-images.githubusercontent.com/1328499/43467524-cd680614-951c-11e8-9cae-7554487d9eb7.png)
