### ISSUE TITLE
各ページから学校種別へのリンクをはる

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#237]
#236 (学校ページの作成)の後になるかと思いますが、各ページから学校種別へのリンクをはる

- [x] 教科書リソース　例 https://w3id.org/jp-textbook/高等学校/2012/国総/301
- [x] 学習指導要領　例 https://w3id.org/jp-textbook/curriculum/高等学校/2013
- [x] 教科書目録　例 https://w3id.org/jp-textbook/catalogue/高等学校/2012
- [x] 教科　例 https://w3id.org/jp-textbook/curriculum/高等学校/2013/国語
- [x] 種別　例 https://w3id.org/jp-textbook/curriculum/高等学校/2013/国語/国語総合

**Comment by masao** [comment]
全てのページから、リンクを追加しました。

**Comment by yegusa** [comment]
全て確認しました。クローズします。
