### ISSUE TITLE
種目の出典にリンクを張ってほしい

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#239]
webに出典があるものは、種目の出典にリンクを張ってほしい。データとしては、seeAlsoで入っている。

例：https://w3id.org/jp-textbook/curriculum/小学校/2011/国語/国語
![linked open data lod](https://user-images.githubusercontent.com/1328499/43053179-3b108d02-8e66-11e8-9a62-a6f20bcfad48.png)

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
確認しました。クローズします。

![linked open data lod 1](https://user-images.githubusercontent.com/1328499/43357237-604f3526-92b9-11e8-9a86-491c55f379a0.png)
