### ISSUE TITLE
教科書目録のページにJP番号とNCIDを使った関連リンクを追加

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#241]
#207 #206 から派生。

- [x] 国立国会図書館サーチ
- [x] CiNii Books

例： https://w3id.org/jp-textbook/catalogue/小学校/2010
![23 linked open data lod](https://user-images.githubusercontent.com/1328499/43054947-eb311ee2-8e6e-11e8-9119-f8e6ea2e0732.png)

**Comment by masao** [comment]
対応しました。

**Comment by yegusa** [comment]
確認しました。クローズします。

例：https://w3id.org/jp-textbook/catalogue/小学校/2010

![23 linked open data lod 1](https://user-images.githubusercontent.com/1328499/43353283-50b81e9c-926f-11e8-8c31-9183f30da169.png)
