### ISSUE TITLE
議論：curriculum.ttl: 学習指導要領の改正情報と対応した本文参照情報の表現方法

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#242]
#54  をやっていて気づいたのですが、学習指導要領は、一部改正が行われていることがあります。

キリの良い（？）改正ごとに、本文Webページも存在するようです。逆に言うと、載っていない改正のものもあります。

ですので、せっかくですので、それらを表現したいとおもっていますが、どうするのが良いでしょうか？
議論したいです。

最低でも、本文URLをrdfs:seeAlsoで、改正後かどうか関係なく、書いておくことはできますが。

改正あり | 学習指導要領リソース | 改正情報
-- | -- | --
なし| https://w3id.org/jp-textbook/curriculum/小学校/1992 | 平成元年3月(1989-03)告示（改正なし）
なし| https://w3id.org/jp-textbook/curriculum/中学校/1993 | 平成元年3月(1989-03)告示（改正なし）
なし| https://w3id.org/jp-textbook/curriculum/高等学校/1994 | 平成元年3月(1989-03)告示（改正なし）
改正| https://w3id.org/jp-textbook/curriculum/小学校/2002 | 平成10年12月(1998-12)告示、平成15年12月(2003-12)一部改正）
改正| https://w3id.org/jp-textbook/curriculum/中学校/2002 | 平成10年12月(1998-12)告示、平成15年12月(2003-12)一部改正）
改正| https://w3id.org/jp-textbook/curriculum/高等学校/2003 | 平成11年3月(1999-3)告示、平成14年5月(2002-05)、平成15年4月(2003-04)、平成15年12月(2003-12)　一部改正
 改正| https://w3id.org/jp-textbook/curriculum/小学校/2011 | 平成20年3月（2008-03）告示、平成27年3月（2015-03）一部改正
改正| https://w3id.org/jp-textbook/curriculum/中学校/2012 | 平成20年3月（2008-03）告示、平成22年11月（2010-11）一部改正、平成27年3月（2015-03）一部改正
なし| https://w3id.org/jp-textbook/curriculum/高等学校/2013 | 平成21年3月（2009-03）告示、（平成30年7月現在改正はない）

**Comment by yegusa** [comment]
こんな感じで表現するのはどうだろうか？

```
@prefix schema:    <http://schema.org/>.
@prefix textbook:  <https://w3id.org/jp-textbook/>.
@prefix textbook-rc:  <http://dl.nier.go.jp/library/vocab/textbook-rc/>.
<https://w3id.org/jp-textbook/curriculum/高等学校/2003> a <https://w3id.org/jp-textbook/CurriculumGuideline>;
  rdfs:seeAlso [
  schema:version "改正:平成27年3月";
  schema:url <http://www.mext.go.jp/a_menu/shotou/new-cs/youryou/1356251.htm>;
  ].
<https://w3id.org/jp-textbook/curriculum/高等学校/2003> a <https://w3id.org/jp-textbook/CurriculumGuideline>;
  rdfs:seeAlso [
  schema:version "告示:平成21年3月";
  schema:url <http://www.mext.go.jp/a_menu/shotou/new-cs/youryou/1304427.htm>;
  schema:url <http://www.nier.go.jp/guideline/h20h/index.htm>;
  ].
```

**Comment by masao** [comment]
```turtle
@prefix schema:    <http://schema.org/>.
@prefix textbook:  <https://w3id.org/jp-textbook/>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
<https://w3id.org/jp-textbook/curriculum/小学校/2002> a <https://w3id.org/jp-textbook/CurriculumGuideline>;
  rdfs:seeAlso [
    schema:version "平成10年12月 告示";
    schema:url <http://www.mext.go.jp/a_menu/shotou/cs/1319941.htm>;
    schema:url <http://www.nier.go.jp/guideline/h10e/index.htm>;
  ], [
  schema:version "平成15年12月 一部改正";
    schema:url <http://www.mext.go.jp/a_menu/shotou/cs/1320008.htm>;
    schema:url <http://www.nier.go.jp/guideline/h15e/index.htm>;
  ].
```

**Comment by yegusa** [comment]
あと、覚書として、これに追加して、WayBackMachine, WARP, ISBN, JPNO, NCID, NIERの所蔵ID,NIERの書誌ID, NIERの請求記号, あたりをつけたいと思っている。

**Comment by yegusa** [comment]
dcterm:hasVersion

```turtle
@prefix schema:    <http://schema.org/>.
@prefix textbook:  <https://w3id.org/jp-textbook/>.
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix dct: <http://purl.org/dc/terms/> .
<https://w3id.org/jp-textbook/curriculum/小学校/2002> a <https://w3id.org/jp-textbook/CurriculumGuideline>;
  dct:hasVersion [
    schema:name "平成10年12月 告示";
    schema:url <http://www.mext.go.jp/a_menu/shotou/cs/1319941.htm>;
    schema:url <http://www.nier.go.jp/guideline/h10e/index.htm>;
    refs:seeAlso <http://waybachmachine/>;
  ], [
    schema:name "平成15年12月 一部改正";
    schema:url <http://www.mext.go.jp/a_menu/shotou/cs/1320008.htm>;
    schema:url <http://www.nier.go.jp/guideline/h15e/index.htm>;
  ].
```

**Comment by yegusa** [comment]
では、この線でttlを作ってみたいと思います。

**Comment by yegusa** [comment]
話し合って方針が決まったので、議論のこのissueはクローズします。
