### ISSUE TITLE
外部へのリンクを明示する

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#243]
Wikipediaなどでやっているように、CSSにて、リンクの右端にアイコンを付けて区別する。

文科省サイトや教育図書館、NDL、カーリルなど、リンクが増えてきたので、カーソルを合わせなくても、外部へのリンクなのかがわかるように。

**Comment by masao** [comment]
機能追加しました。

**Comment by yegusa** [comment]
確認しました。クローズします。

例：
https://w3id.org/jp-textbook/小学校/2010/国語/101

![linked open data lod](https://user-images.githubusercontent.com/1328499/43357219-0cdc4a28-92b9-11e8-98bb-0d78ad559869.png)
