### ISSUE TITLE
種目英語ページからも、出典リンクをはる

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#246]
#125 の確認作業していて気づきました。
#239 の作業もれで、英語ページでのリンクをしていなかったので。。

**Comment by yegusa** [comment]
確認しました。クローズします。

https://w3id.org/jp-textbook/en/curriculum/高等学校/2013/福祉/社会福祉基礎

![social welfare foundations in upper secondary school japanese textbook linked open data lod](https://user-images.githubusercontent.com/1328499/43378569-b2d7a176-9402-11e8-94b8-cc0ab4bd3768.png)
