### ISSUE TITLE
版情報が登録されていない

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#247]
現状、教科書の版情報（schema:bookEdition）の登録がゼロ。。。

おそらく、データ処理に抜け落ちがありそうなので、要確認。

**Comment by yegusa** [comment]
いや、多分、あっているはず。古い教科書にしか、版情報は載っていないはずなので。

**Comment by masao** [comment]
確かに、、、今のところ無いのですね。なるほど。
