### ISSUE TITLE
教科書一覧の簡易表示に、「使用年」も表示するようにする

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#248]
そうすれば、新しく追加した教科書かどうかもわかりやすくて良い

現在は、タイトルと発行者のみ。これに、「使用年」も追加する。

例： https://w3id.org/jp-textbook/curriculum/小学校/2011/国語/国語
![linked open data lod 2](https://user-images.githubusercontent.com/1328499/43495186-8c93f01c-9571-11e8-80fe-a284ab72e8b5.png)

**Comment by masao** [comment]
対応しました。

**Comment by yegusa** [comment]
確認しました。いいですね！
クローズします。

![linked open data lod 3](https://user-images.githubusercontent.com/1328499/43498384-aca28aac-9581-11e8-8769-d8b71d947406.png)
