### ISSUE TITLE
教科書目録リソース：詳細に全てのプロパティ情報を記載する

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#250]
#229 から派生

- [x] すでにできているか、できていないか確認、できていたらクローズ
- [ ] 日本語版
- [ ] 英語版

教科書目録　リソース例：
- https://w3id.org/jp-textbook/catalogue/小学校/1991
- https://w3id.org/jp-textbook/catalogue/中学校/2001
- https://w3id.org/jp-textbook/catalogue/高等学校/2012

**Comment by yegusa** [comment]
できていないことを確認したので、開発よろしく@masao

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
確認しました。クローズします。
