### ISSUE TITLE
教科リソース：詳細に全てのプロパティ情報を記載する

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#251]
#229 から派生

- [x] すでにできているか、できていないか確認、できていたらクローズ
- [x] 日本語版
- [x] 英語版

教科　リソース例：
- https://w3id.org/jp-textbook/curriculum/小学校/1992/算数
- https://w3id.org/jp-textbook/curriculum/中学校/2002/保健体育
- https://w3id.org/jp-textbook/curriculum/高等学校/2013/国語

**Comment by yegusa** [comment]
できていないことを確認したので開発よろしく @masao

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
良いと思います。クローズします。表示順序の件は別イシューにします。
