### ISSUE TITLE
種目リソース：詳細に全てのプロパティ情報を記載する

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#252]
#229 から派生

- [ ] すでにできているか、できていないか確認、できていたらクローズ
- [ ] 日本語版
- [ ] 英語版
  
種目　リソース例：
  
- https://w3id.org/jp-textbook/curriculum/小学校/1992/算数/算数
- https://w3id.org/jp-textbook/curriculum/中学校/2002/音楽/音楽(一般)
- https://w3id.org/jp-textbook/curriculum/高等学校/2013/国語/国語総合

**Comment by yegusa** [comment]
できてないことを確認したので開発よろしく @masao

**Comment by masao** [comment]
たぶんできたはず。

**Comment by yegusa** [comment]
qb:order がない。

**Comment by yegusa** [comment]
別issueにして、一旦クローズにします。
