### ISSUE TITLE
教科と種目の教科種別・科目種別のURIを変更する（旧：教科種別のラベル基準）

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#254]
#151 からの派生。

2つの教科種別それぞれのラベルには以下の2通りがある：

* textbook:curriculum/SubjectArea/Common: 「各学科に共通する各教科」「普通教育に関する各教科」
* textbook:curriculum/SubjectArea/Special: 「主として専門学科において開設される各教科」「専門教育に関する各教科」

名称は基本的には学習指導要領に応じて変わるようだが、どちらの名称がどの年度にひもづいているのでしょうか。

**Comment by yegusa** [comment]
すみません、元々の、
> textbook:curriculum/SubjectArea/Common: 「各学科に共通する各教科」「普通教育に関する各教科」
> textbook:curriculum/SubjectArea/Special: 「主として専門学科において開設される各教科」「専門教育に関する各教科」

をどうやって考えたか、すでに覚えていないのですが、今、新たに調べて見たところ、こんな感じになりそうなのですが、どうしましょう？

- https://w3id.org/jp-textbook/curriculum/高等学校/2013
  - Common: 各学科に共通する各教科
  - Special: 主として専門学科において開設される各教科
  - 出典：   [学習指導要領](http://www.mext.go.jp/component/a_menu/education/micro_detail/__icsFiles/afieldfile/2011/03/30/1304427_002.pdf)の章タイトルなど（「第２章 **各学科に共通する各教科**」「第３章 **主として専門学科において開設される各教科**」）や、学習指導要領冒頭の「学 校 教 育 法 施 行 規 則（抄）」の表題（pp. iii-iv ）など
- https://w3id.org/jp-textbook/curriculum/高等学校/2003
  - Common: 普通教育に関する各教科・科目
  - Special: 専門教育に関する各教科・科目
  - 学習指導要領の章：[総則](http://www.mext.go.jp/a_menu/shotou/cs/1320147.htm)の「第2款　各教科・科目及び単位数等」の表題など（「2　**普通教育に関する各教科・科目**及び標準単位数」「3　**専門教育に関する各教科・科目**」）
- https://w3id.org/jp-textbook/curriculum/高等学校/1994
  - Common: すべての生徒に履修させるもの及び普通科における各教科・科目
  - Special: 専門教育を主とする学科における各教科・科目 
  - 出典：学習指導要領の[総則](http://www.nier.go.jp/guideline/h01h/chap1.htm)の「第3款　各教科・科目の履修」の本文で「1 次の各教科・科目は、**すべての生徒に履修させるもの**とし、」「2　**普通科における各教科・科目**の履修については、上記1のほか次のとおりとする。」「3　**専門教育を主とする学科における各教科・科目**の履修については、上記1のほか次のとおりとする。」

ふと思ったのですが、textbook:curriculum/SubjectArea/Common　やSpecial のリソースの情報を書いたttlファイルがいる？

それで、提案ですが、ラベルは、とりあえず、全部、

- textbook:curriculum/SubjectArea/Common: 　共通する科目
- textbook:curriculum/SubjectArea/Special: 　専門の科目

あたりでどうでしょうか？

**Comment by yegusa** [comment]
そうか、学習指導要領ごとにURIをつけるのでもいいのね。
どっちがいいか、少し検討しましょう。

**Comment by yegusa** [comment]
2018-08-03 打ち合わせ結果：

以下のように、学習指導要領ごとにリソースを作ることにする。

https://w3id.org/jp-textbook/curriculum/高等学校/2013/Common　
https://w3id.org/jp-textbook/curriculum/高等学校/2013/Special 
https://w3id.org/jp-textbook/curriculum/高等学校/2003/Common　
https://w3id.org/jp-textbook/curriculum/高等学校/2003/Special 
https://w3id.org/jp-textbook/curriculum/高等学校/1994/Common　
https://w3id.org/jp-textbook/curriculum/高等学校/1994/Special 

学習指導要領によって変遷する可能性がたかそうなので。

**Comment by yegusa** [comment]
種目でも同様なのがあるのですが、
教科と同じURIで良いですか？

例：
```turtle
<https://w3id.org/jp-textbook/curriculum/高等学校/1994/国語/国語II> a <https://w3id.org/jp-textbook/curriculum/Subject>;
  schema:name "国語II"@ja;
  schema:name "こくごII"@ja-Hira;
  schema:name "Japanese Language II"@en;
  textbook:school <https://w3id.org/jp-textbook/school/高等学校>;
  qb:order 2;
  textbook:subjectType <https://w3id.org/jp-textbook/curriculum/Subject/Common>;
  schema:citation "『教科用図書検定申請受理種目』平成元年6月9日文部省告示第89号".
```

**Comment by yegusa** [comment]
とりあえず、一旦、同じURIで作っておきますね。

- [ ] 教科 ttlの修正
  - [ ] HTML
  - [ ] about
- [ ] 種別 ttlの修正
  - [ ] HTML
  - [ ] about の修正

**Comment by yegusa** [comment]
ttlを作成しました。aboutも先行して修正しています。 HTML開発よろしく。7.2系フォルダに入れてあります。subject-20180804.ttl, subjectArea-20180804.ttlです。 @masao

**Comment by masao** [comment]
追加しました。確認ねがいます。

**Comment by yegusa** [comment]
確認しました。クローズします。
