### ISSUE TITLE
学習指導要領: 発行年（yyyy） → 告示日(yyyy-mm-dd)に

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#256]
https://github.com/jp-textbook/jp-textbook.github.io/issues/255#issuecomment-409819998 より。

* [x] HTML
* [x] 説明文書（about）

**Comment by yegusa** [comment]
(yyyyからyyyy-mm-ddに変更したことに伴う）

**Comment by yegusa** [comment]
先行して、aboutは修正しておきました。

**Comment by masao** [comment]
一通り直しました。

**Comment by yegusa** [comment]
確認しました。クローズします。

**Comment by yegusa** [comment]
追加：aboutのLOD概念図も修正しておきました。
