### ISSUE TITLE
typo: ぎょぎょう?

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#258]
https://w3id.org/jp-textbook/curriculum/高等学校/2013/水産/漁業

- [x] HTML

**Comment by yegusa** [comment]
修正しておきました。他にも同系列の間違いを修正しています。5件くらい？。
7.2系フォルダに入れてあります。 subject-20180804.ttl @masao

**Comment by masao** [comment]
修正を確認したのでクローズします。
