### ISSUE TITLE
subjectArea.ttl 教科ttl：教科・科目種別のURIを変える

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#260]
#259 より派生

**Comment by yegusa** [comment]
作成しました。
7.2系フォルダに入れています。
subjectArea-20180806.ttl

@masao よろしく

**Comment by yegusa** [comment]
プロパティは、教科も種目も、どちらも、textbook:subjectType　で統一。（教科のtextbook:subjectAreaType　はやめる）　の件は、先行してaboutを修正しておきました。

**Comment by masao** [comment]
確認したのでクローズします。
