### ISSUE TITLE
about: schoolプロパティ例の修正

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#262]
schoolリソースを修正したため、学校種別プロパティ例をすべてなおすよう、ドキュメントも修正が必要そうです。

* [x] textbook
* [x] curriculum
* [x] subjectArea
* [x] subject
* [x] catalogue

**Comment by yegusa** [comment]
about 修正しました。@masao 確認よろしく。

**Comment by masao** [comment]
確認したのでクローズします。
