### ISSUE TITLE
aboutの修正：高等学校の専門教科（商業など）の「種目」の英語名の出典

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#263]
#125 から派生です。

出典については、https://github.com/jp-textbook/jp-textbook.github.io/issues/125#issuecomment-407985162 を参照

**Comment by yegusa** [comment]
追加しました。 @masao 確認よろしく。

**Comment by masao** [comment]
確認したのでクローズします。
