### ISSUE TITLE
curriculum-version.ttl 学習指導要領改正情報ttl の英語名称や出典

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#268]
#54 からの派生です

- [x] ttl
- [ ] HTML
- [x] about

英語版のHTML表示に使えるように、英語の名称などをttlにつける

- 平成10年12月 告示 →　1998-12 Notification
- 平成15年12月 一部改正 → 2003-12 Notification of Partial Revision
- 『平成10年 文部省告示第百七十五号』（官報. 平成10年12月14日, 号外第261号, pp.10-45）
→ "Notification No. 175 in 1998 of the Ministry of Education, Science and Culture." (Official Gazette, 1998-12-14, Extra Edition No. 261, pp10-45)
 
![elementary school curriculum guideline japanese textbook linked open data lod](https://user-images.githubusercontent.com/1328499/43853019-c8065f6e-9b79-11e8-92b2-8e5bdd8c3924.png)

**Comment by yegusa** [comment]
修正しました。8.1系フォルダに curriculum-versions-20180811.ttl です。 @masao 確認等よろしく。

  schema:name --> schema:name@ja
  schema:name@en
  chema:citation  --> chema:citation@ja
  chema:citation@en

```turtle
@prefix dct: <http://purl.org/dc/terms/>.
@prefix schema: <http://schema.org/>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix nier: <http://dl.nier.go.jp/library/vocab/>.
<https://w3id.org/jp-textbook/curriculum/小学校/1992>
  dct:hasVersion [
  schema:name@ja "平成元年3月 告示";
  schema:name@en "1989-03 Notification";
  schema:datePublished "1989-03-15";
  schema:citation@ja "『平成元年 文部省告示第二十四号』（官報. 平成元年3月15日, 号外特第4号, pp.9-50）";
  schema:citation@en "\"Notification No. 24 in 1989 of the Ministry of Education, Science and Culture\" (Official Gazette, 1989-03-15, Special Extra Edition No. 4, pp.9-50)";
  schema:url <http://www.mext.go.jp/a_menu/shotou/old-cs/1322235.htm>;
  schema:url <http://www.nier.go.jp/guideline/h01e/index.htm>;
  rdfs:seeAlso <http://id.ndl.go.jp/jpno/89034331>;
  rdfs:seeAlso <https://ci.nii.ac.jp/ncid/BN03844525>;
  schema:isbn "4171533104";
  nier:itemID "071221843";
  nier:callNumber "375.92||1||1989d";
  nier:recordID "BB80025218";
  ].
```

**Comment by yegusa** [comment]
先行して、about も修正しておきました。 @masao 
HTML開発よろしく。

**Comment by masao** [comment]
一通り追加しました。

**Comment by yegusa** [comment]
確認しました。いい感じです。クローズします。
![upper secondary school curriculum guideline japanese textbook linked open data lod](https://user-images.githubusercontent.com/1328499/43988257-7e4818a0-9d6c-11e8-9043-1e2cf3c646e9.png)
