### ISSUE TITLE
HTML: 種目リソース: 種目の表示順序（qb:order）を表示

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#271]
#252 から派生

教科用図書検定申請受理種目掲載順 
qb:order　表示順を決める場合などで利用する値の表示。

- https://w3id.org/jp-textbook/curriculum/小学校/1992/算数/算数
- https://w3id.org/jp-textbook/curriculum/中学校/2002/音楽/音楽(一般)
- https://w3id.org/jp-textbook/curriculum/高等学校/2013/国語/国語総合

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
確認しました。クローズしました。
