### ISSUE TITLE
最新の更新履歴をトップに載せて欲しい

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#273]
最新の更新履歴をトップに載せて欲しい。

「過去の更新履歴の一覧」リンクを今の場所からは削除し、
public domainの下あたりに以下のような内容をおく感じ。

# 最近のお知らせ
## 2018年8月9日

バージョン8.0を公開。 学習指導要領の改正情報を追加しました。 教科種別、種目種別について、各学習指導要領別のURIとなるよう修正し、あわせて各教科・種目からの関連プロパティも変更しました。 全てのリソースの詳細情報を全てのプロパティ分表示するようにしました。 その他、更新内容の詳細はGithubの[マイルストーン8.0](https://github.com/jp-textbook/jp-textbook.github.io/milestone/14?closed=1)をご覧ください。

[過去の更新履歴の一覧](過去の更新履歴の一覧)

**Comment by masao** [comment]
実装します。
* 見出しは「最近のお知らせ」とする。
* データセットの下につける。

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
確認しました！いいと思います。クローズします。
![linked open data lod 1](https://user-images.githubusercontent.com/1328499/43987420-5c60babe-9d5b-11e8-963d-a782be8e8d8b.png)
