### ISSUE TITLE
bf:noteプロパティへの変更

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#274]
- [x] ttl
- [x] HTML
- [x] about

#171 の派生。

例： https://w3id.org/jp-textbook/中学校/2005/公民/910

現在、備考情報として、独自プロパティ textbook:note を使っているが、これをBIBFRAME由来の note プロパティに変更したい。

cf. http://id.loc.gov/ontologies/bibframe.html#p_note

**Comment by masao** [comment]
修正しました。

**Comment by yegusa** [comment]
textbook-20180811.ttl を確認しました。残りは、HTML対応とaboutですね。

例：
```turtle
  bf:note "2009年度より出版社を「日本文教出版株式会社」に変更。".
```

**Comment by yegusa** [comment]
about は修正しておきました。残りは、HTML対応だけです　→ @masao

**Comment by yegusa** [comment]
HTML対応やってるのね。なので、クローズします。
