### ISSUE TITLE
Poorman's Toolkit文書化

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#275]
aboutからも事例報告論文からも外したため、別途に文書化すること。

https://qiita.com/ などで公開するのでもよい。

**Comment by yegusa** [comment]
qiita.com は共著で書けるの？

**Comment by yegusa** [comment]
a) MS Excel + MS Word + Terapad(CodEditor)
b) Google Spreadsheet + Google Docs (テキストとして出力）

どっちがいいかな？まあ、a) でいいか。

**Comment by yegusa** [comment]
b) は、7000とかレコード数が多くなった時にどうかわからないし、やったことのある a) でやることにする

**Comment by yegusa** [comment]
Excelで1行1レコードのデータを作成
![excel-school](https://user-images.githubusercontent.com/1328499/43992762-12a417a0-9dbe-11e8-8f47-70d162536717.png)

**Comment by yegusa** [comment]
![excel-school-make-ttl](https://user-images.githubusercontent.com/1328499/43992908-85642b34-9dc0-11e8-98ca-0afa57ca58da.png)

**Comment by yegusa** [comment]
![excel-school-cp-ttl](https://user-images.githubusercontent.com/1328499/43993112-aca9ad60-9dc3-11e8-8247-239106e96667.png)

**Comment by yegusa** [comment]
![word-school-p](https://user-images.githubusercontent.com/1328499/43993146-3695257c-9dc4-11e8-8584-28ccc604cac4.png)

**Comment by yegusa** [comment]
![word-school-cp](https://user-images.githubusercontent.com/1328499/43993205-d723ee42-9dc4-11e8-973f-5aed6888721a.png)

**Comment by yegusa** [comment]
[school-20180713.xlsx](https://github.com/jp-textbook/jp-textbook.github.io/files/2280351/school-20180713.xlsx)

**Comment by yegusa** [comment]
書きました！ https://github.com/jp-textbook/jp-textbook.github.io/wiki/Toolkit
@masao 確認よろしく。

**Comment by masao** [comment]
確認しました。クローズします。
