### ISSUE TITLE
about Poorman’s Linked Data Toolkitへリンク貼る

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#277]
Poorman’s Linked Data Toolkit
https://github.com/jp-textbook/jp-textbook.github.io/wiki/Toolkit

**Comment by masao** [comment]
英語版も追加したので、ひとまずお知らせに載せました。
https://github.com/jp-textbook/jp-textbook.github.io/wiki/Toolkit.en

**Comment by yegusa** [comment]
確認しました。お知らせ以外にも載せたい気がするのだけど。
概要の「教科書LODの構築と公開の詳細については下記論文等を参照してください。」のところを
「教科書LODの構築と公開の詳細については下記文書等を参照してください。」
ってしてリストアップがいいかな。

**Comment by yegusa** [comment]
aboutの概要に追加してみました。 @masao 確認ください。

**Comment by masao** [comment]
ついでに英語版にも追加しました。

**Comment by yegusa** [comment]
確認しました。クローズします。
