### ISSUE TITLE
教科書LODのロゴが欲しい

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#279]

**Comment by yegusa** [comment]
こんな感じ？

![textbooklod-logo](https://user-images.githubusercontent.com/1328499/43998882-93412222-9e3b-11e8-9f3f-f95ac61043c0.png)

**Comment by yegusa** [comment]
覚書：
サイズ：750 × 285
本のアイコン： http://icooon-mono.com/14120-%E8%AA%AD%E6%9B%B8%E3%82%A2%E3%82%A4%E3%82%B3%E3%83%B3/
背景色：#0f254d
フォント： hiragino kaku gothic pro / 85

**Comment by yegusa** [comment]
iconのみのも作っておきました
サイズ：285 × 285
![textbooklod-logo-icon](https://user-images.githubusercontent.com/1328499/43998938-3e3867f8-9e3c-11e8-9c7e-0cac1ec7b654.png)

**Comment by yegusa** [comment]
メモ：元データは、logo フォルダに入れています。

**Comment by yegusa** [comment]
アイコンだけ（白線、背景透明化）のものも置いておきます。

![icon-white](https://user-images.githubusercontent.com/1328499/43999094-ff80af62-9e3f-11e8-87aa-cc3993af83ec.png)

（何もないように見えますがこの上にあります）

**Comment by yegusa** [comment]
ついでに、アイコンと文字だけで背景透明化のも置いておきます

![textbooklod-logo-no-bg](https://user-images.githubusercontent.com/1328499/43999105-6627cf66-9e40-11e8-9e63-5a81d5679faf.png)

（何もないように見えますがこの上にあります）

**Comment by masao** [comment]
一通り追加しました。

**Comment by yegusa** [comment]
英語のHome は、画像が　not found
英語のabout はなんか、アイコンが左にくっついてる
ヘッダーの背景色は、 できれば、#0f254d がいいなー。

**Comment by masao** [comment]
一通り修正しました。

**Comment by yegusa** [comment]
確認しました。クローズします。

**Comment by yegusa** [comment]
すみません、指定した色番号が違いました。。。
ロゴ画像も、今から直します。

濃藍（こいあい）
#0f2350

これのつもりでいたんです。

**Comment by yegusa** [comment]
良いと思います。クローズします。
