### ISSUE TITLE
subjectArea.ttl 英語の教科名の出典を明記する

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#280]
- [x] ttl
- [x] html
- [x] about

自分でも忘れる（忘れた）ので、出典をもう一度確認して、データ入力する。

**Comment by yegusa** [comment]
データは入れて見たものの、ttlでどう書いたらいいのか。。。

**Comment by yegusa** [comment]
作成しました。10.1系フォルダに入れています。subjectArea-20180821.ttl です。ご確認ください。 @masao

**Comment by masao** [comment]
一通り追加しました。

**Comment by yegusa** [comment]
確認しました。

![japanese language in elementary school japanese textbook linked open data lod 1](https://user-images.githubusercontent.com/1328499/44406715-491bbf00-a597-11e8-9d90-bf7f172fbc04.png)

**Comment by yegusa** [comment]
残りはaboutですね。一旦、私に戻します。

**Comment by yegusa** [comment]
画像間違い。こっちです。

![japanese language japanese textbook linked open data lod](https://user-images.githubusercontent.com/1328499/44406913-c0515300-a597-11e8-8d12-8fe8a16cb9d6.png)

**Comment by yegusa** [comment]
about 書きました。確認よろしく　-> @masao

**Comment by masao** [comment]
確認しました。クローズします。
