### ISSUE TITLE
種目ページから学校種別へのリンク（英語版）

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#284]
英語版にて、種目ページから学校種別ページへのリンクがおかしい。

https://jp-textbook.github.io/en/curriculum/%E5%B0%8F%E5%AD%A6%E6%A0%A1/2011/%E9%9F%B3%E6%A5%BD/%E9%9F%B3%E6%A5%BD のリンクは

https://jp-textbook.github.io/en//school/%E5%B0%8F%E5%AD%A6%E6%A0%A1

「//」が含まれるリンクになってしまっている。。

**Comment by masao** [comment]
修正しました。

**Comment by yegusa** [comment]
確認しました。クローズします。
