### ISSUE TITLE
twitter card対応

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#292]
#285 の派生。Twitter上のプレビュー対応。
```html
<meta name="twitter:card" content="summary" />
```

**Comment by masao** [comment]
追加しました。
https://cards-dev.twitter.com/validator から確認できます。

**Comment by yegusa** [comment]
確認しました。クローズします。

![1 twitter](https://user-images.githubusercontent.com/1328499/44072208-6e6d3b32-9fc8-11e8-8696-f3b7a5087ce8.png)
