### ISSUE TITLE
データ誤り: https://w3id.org/jp-textbook/curriculum/高等学校/2013/商業/財務会計

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#293]
種目が「財務会計」となっている教科書データあり。
正確には、「財務会計I」または「財務会計II」のいずれかのはず。。

**Comment by masao** [comment]
例：https://w3id.org/jp-textbook/高等学校/2017/商業/347

**Comment by yegusa** [comment]
本来は、空になっているはずのものですね。

#224 と重複なので、こちらは、クローズします。
