### ISSUE TITLE
twitter用のロゴ画像を作成

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#294]
端が切れてしまってカッコ悪いので、
「縦144px×横144px以上でサイズの比は1：1」を作成する

- [x] 画像作成
- [ ] HTML

**Comment by yegusa** [comment]
640x640で作りました。
HTML反映よろしく。
<meta name="twitter:image" content="Twitter用の画像URL" />
こんな風に書くらしい。
https://www.sakurasaku-labo.jp/blogs/facebook-og-image
![textbook-lod-logo-twitter](https://user-images.githubusercontent.com/1328499/44073392-9b3b8942-9fce-11e8-9770-a3c672bbe02c.png)

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
なってなかった。
![1 twitter 1](https://user-images.githubusercontent.com/1328499/44088209-522621fc-9ffd-11e8-936f-70cacc84a661.png)

**Comment by masao** [comment]
おそらくCDNキャッシュが残っているのではないかと思われ。
検証ツールでの確認はうまくいっています： https://cards-dev.twitter.com/validator
少し時間を置く必要があるのかもしれません。。

**Comment by yegusa** [comment]
なんと、既存の投稿も差し変わるのね。できていることを確認したので、クローズします。

![yuka egusa yegusa twitter](https://user-images.githubusercontent.com/1328499/44124006-f121089a-a065-11e8-8f68-d6050d840712.png)
