### ISSUE TITLE
FB用の画像を作成

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#295]
切れてしまってカッコ悪いので。

縦630px×横1200px

- [x] 画像作成
- [ ] HTML

**Comment by yegusa** [comment]
作りました。HTML反映よろしく。 @masao 

![textbook-lod-logo-fb](https://user-images.githubusercontent.com/1328499/44073315-59fd0f46-9fce-11e8-9271-9794a97ac73b.png)

**Comment by yegusa** [comment]
参考にしたサイト：https://www.sakurasaku-labo.jp/blogs/facebook-og-image

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
変わってなかった。。。
![facebook](https://user-images.githubusercontent.com/1328499/44088341-b6e9a352-9ffd-11e8-8f58-559c928e3eae.png)

**Comment by masao** [comment]
こちらもCDNキャッシュが残っているだけと思われる。開発ツールでは新しい画像に直っている。。
https://developers.facebook.com/tools/debug/og/object?q=https%3A%2F%2Fjp-textbook.github.io%2F

**Comment by yegusa** [comment]
できていることを確認しましたので、クローズします。

![fb-image-test](https://user-images.githubusercontent.com/1328499/44124710-844403ae-a069-11e8-9a39-8a087a3a1a5c.png)
