### ISSUE TITLE
三省堂出版株式会社→三省堂かもしれない

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#299]
textbook:publisher/2001/三省堂
textbook:publisher/2005/三省堂

三省堂出版株式会社　となっているが、三省堂かもしれないので確認すること
（教科書目録の発行者一覧を確認する）

**Comment by yegusa** [comment]
メモ：
平成13年 2001年
平成17年2005年

**Comment by yegusa** [comment]
どちらも、教科書目録の発行者一覧では、「株式会社 三省堂」と書いてありました。

**Comment by yegusa** [comment]
ついでに、三省堂は一通り他の年も確認して、発行者名を発行者一覧の記載の通りに、Excelデータに、転記しておきました。（三省堂→ 株式会社 三省堂にする; 2017年発行の教科書目録から、株式会社の後に空白を入れなくなったのでその通りに修正）

10.2系フォルダの publisher-20180825-2.ttl に置いておきます。

**Comment by masao** [comment]
修正を追加しました。

**Comment by yegusa** [comment]
確認しました。クローズします。
