### ISSUE TITLE
publisher.ttl: 出版者情報に「法人番号」を入れる

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#301]
- [x] ttl
- [ ] HTML
- [x] about

国税庁　法人番号　公表サイト
https://www.houjin-bangou.nta.go.jp/

なるものがあったので、こちらで、法人番号を探して入れる。

基本は、「教科書目録」の最後のページにある「発行者一覧」の「発行者」と「住所」で同定する。
住所が異なるものは、追加で検索などして同定する（例：発行者一覧には現在の本社の住所が載っているが、国税庁のサイトに登録された情報には、昔の本社住所のママになっていることがある）

要議論：プロパティはなんにするか？

**Comment by yegusa** [comment]
議論の結果：NDLAなどと同様に、リンクにしちゃって、これでいいかも。

```turtle
  rdfs:seeAlso https://www.houjin-bangou.nta.go.jp/henkorireki-johoto.html?selHouzinNo=7011501003104
```

**Comment by masao** [comment]
https://hojin-info.go.jp/hojin/pdf/API.pdf より：
![image](https://user-images.githubusercontent.com/38825/44379624-d6342900-a541-11e8-906d-4bf50ba5bdfb.png)

URLとしては法人インフォの公式サイトのURIが一応あるので、そちらがよさそうだが。。。
なぜかHTML等は返戻しないのが難点…。

**Comment by yegusa** [comment]
で、URIどうします？とりあえず、wikipediaの真似して、私の案でいきます？

**Comment by masao** [comment]
URIはこちらのほうが情報が多そう:
https://hojin-info.go.jp/hojin/ichiran?hojinBango=7011501003104

**Comment by yegusa** [comment]
じゃあ、とりあえず、それを生成することにします。

**Comment by yegusa** [comment]
一通り追加して、10.2系フォルダに publisher-20180826-3.ttl として置いておきました。

**Comment by masao** [comment]
法人インフォへのリンクデータを追加しました。

**Comment by yegusa** [comment]
確認しました。クローズします。

![linked open data lod](https://user-images.githubusercontent.com/1328499/44760756-47479200-ab7b-11e8-9ceb-e53172e78467.png)
