### ISSUE TITLE
publisher.ttl 「発行者」の名称：教科書目録の最後のページの「発行者一覧」を底本にする

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#302]
最初に作成したのは、教育図書館からTSVでもらった教科書の書誌データの

- ★教科書目録掲載年度
- 発行者略称
- 発行者
- 発行者番号

を抜き出して、sort | uniq して作成した。

「発行者」について、いくつか「教科書目録の最後のページ」にある「発行者一覧」の情報と照らし合わせてみたところ、「発行者一覧」とは矛盾のあるデータが散見された。

発行者名は、「発行者一覧」の方を底本にした方が良いと思うがどうか？

**Comment by yegusa** [comment]
話し合って、発行者一覧のデータを底本にすることにしたので、タイトル変更。

**Comment by yegusa** [comment]
なかなかしんどい作業で、一気にするのは難しいかもです。とりあえず、発行者番号が2桁のものはやりました。10.2系フォルダの publisher-20180826.ttl に置いておきます。

**Comment by yegusa** [comment]
一通り、やりました。10.2系フォルダ publisher-20180826-3.ttl です。

**Comment by yegusa** [comment]
参考：基本、底本に書かれたものを転記しています。「株式会社」などもそのまま転記しています。また、株式会社をくっつけたり、空白を入れたりもそのまま転記しています（基本的に、2017年からはくっつけるようになったみたいです）。住所の表記もなるべくそのまま転記していて、年によって表記に揺れがある場合もそのまま転記しています。

また、空白がある、ない、株式会社があるないなどの、細かな表記の違いなどの修正はいちいちissueにあげていませんが、大きく発行者名が変わるなどの修正の影響の大きそうなものは個別にissueにあげておきました。ttlにはしていませんが、住所も一応Excelnには入力しておきました。

**Comment by masao** [comment]
一通り修正を追加しました。

**Comment by yegusa** [comment]
確認しました。クローズします。
