### ISSUE TITLE
HTML: English 版の出版者情報の冒頭のはローマ字のほうがよくない？

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#307]
ここに使われることを想定して、頑張って、ローマ字表記を入力したので、
ここに表示されると嬉しい。

![linked open data lod](https://user-images.githubusercontent.com/1328499/44318526-8128e200-a471-11e8-9cb0-41c439752a36.png)

**Comment by masao** [comment]
修正しました。

**Comment by yegusa** [comment]
確認しました。クローズします。

https://w3id.org/jp-textbook/publisher/2011/東書
![japanese textbook linked open data lod](https://user-images.githubusercontent.com/1328499/44320053-9c4c1f80-a47a-11e8-89ff-7cad89205974.png)
