### ISSUE TITLE
URI.ttl: 発行者のWeb ページのttlが存在しない

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#309]
例：
https://jp-textbook.github.io/publisher/2009/%E6%97%A5%E6%96%87.ttl

![page not found github pages](https://user-images.githubusercontent.com/1328499/44319206-6ce6e400-a475-11e8-90c2-1c7944be3c5a.png)

**Comment by yegusa** [comment]
（ちなみに、教科書リソースのページは、個別ttlでpublisherプロパティがちゃんとあるのは確認しました）

**Comment by masao** [comment]
一通り追加しました

**Comment by yegusa** [comment]
できていることを確認しましたのでクローズします。
