### ISSUE TITLE
HTML: 出版社ページ英語版の言語切り替えがEnglishになっている

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#310]
テンプレートが日本語用のものを使ってしまっている。

**Comment by masao** [comment]
修正しました。

**Comment by yegusa** [comment]
英語になっていると思うので、クローズします。

https://w3id.org/jp-textbook/publisher/2011/東書
![japanese textbook linked open data lod](https://user-images.githubusercontent.com/1328499/44320053-9c4c1f80-a47a-11e8-89ff-7cad89205974.png)

**Comment by yegusa** [comment]
全体のスクリーンショット
https://w3id.org/jp-textbook/publisher/2015/教出

![japanese textbook linked open data lod](https://user-images.githubusercontent.com/1328499/44320134-0ebcff80-a47b-11e8-9750-1a33bcfd2859.png)
