### ISSUE TITLE
publisher.ttl: 発行者番号：189： 教育図書株式会社→教育図書出版社

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#316]
教育図書株式会社→教育図書出版社
NDLAのリンクも修正

https://w3id.org/jp-textbook/publisher/1993/教図出
https://w3id.org/jp-textbook/publisher/2003/教図出

関連: 教育図書館のレコード修正のissue #317

**Comment by yegusa** [comment]
修正しまいた。10.1 系フォルダ publisher-20180825-2.ttl に置いておきました。

**Comment by masao** [comment]
修正を追加しました。

**Comment by yegusa** [comment]
確認しました。クローズします。
