### ISSUE TITLE
発行者略称つけ間違え？：189 教図出 or 6 教図

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#317]
- [x] 教育図書館に連絡
- [x] 修正確認
- [x] データ入手

189 教図出 教育図書株式会社 or 6 教図 教育図書株式会社？

https://w3id.org/jp-textbook/高等学校/2003/家庭/029    教図出
https://w3id.org/jp-textbook/高等学校/2003/家庭/028    教図出
https://w3id.org/jp-textbook/高等学校/1993/看護/502    教図出
https://w3id.org/jp-textbook/高等学校/1993/看護/501    教図出

教図出はどれも、「教育図書出版社」だった。
当該教科書目録を確認すること。

教育図書館と、教科書センター両方とも「教育図書出版社」としていた。
ただし、教科書センターは、発行者番号：6、略称：教図　だったので、
教育図書館のレコードの発行者略称が間違えているのかも？
であれば、教科書LODにも影響する修正。

https://nieropac.nier.go.jp/ebopac/EB10026079
https://nieropac.nier.go.jp/ebopac/EB10026078
https://nieropac.nier.go.jp/ebopac/EB10020571
https://nieropac.nier.go.jp/ebopac/EB10020570

publisher.ttl は #316 で修正

**Comment by yegusa** [comment]
https://w3id.org/jp-textbook/高等学校/2003/家庭/029 教図出
https://w3id.org/jp-textbook/高等学校/2003/家庭/028 教図出

請求記号、発行者略称、発行者番号は先行して連絡、修正済み（のはず）

**Comment by yegusa** [comment]
少なくとも、「請求記号」は「K23」が「K8」に直っていたので、修正された模様。
「発行者略称」、「発行者番号」は、教育図書館の公開システムの情報では表示されておらず、確認不明なので、データをもらってからチェックすることになる。

**Comment by yegusa** [comment]
教育図書館からデータを入手しました。2018-10-25付のデータです。list_EB20181025.txt です。まだ、学習指導要領URIをつけるなどの作業はしていません。

**Comment by yegusa** [comment]
確認しました。まだ修正されていませんでした。ので、もう一度、言います。

- OK: 請求記号の2段目： K23 -> K8
- NG: 発行者略称： 教図出 -> 教図
- NG: 発行者番号：189 -> 6

**Comment by yegusa** [comment]
まだデータはもらえてませんが、直したそうです。

**Comment by yegusa** [comment]
データもらいました。まだ確認はしてません。 list_EB20181108.txt です。

**Comment by yegusa** [comment]
確認しました。修正されていました。
また、学習指導要領URI付与しました。10.5系/textbook-NIER20181108由来_JTRC20180622由来.xls にデータを置いておきます。

**Comment by masao** [comment]
修正を反映しました。

**Comment by yegusa** [comment]
確認しました。クローズします。
