### ISSUE TITLE
publisher.ttl: 信教:社団法人信濃教育会出版部　→ 一般社団法人 信州教育出版社

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#320]
信教:
publisher.ttl: 社団法人信濃教育会出版部　→ 一般社団法人 信州教育出版社
https://w3id.org/jp-textbook/publisher/2014/信教

#319 に関連

空白が入ったり、入らなかったりの修正もあり。
全て、発行者一覧からの転記。

**Comment by yegusa** [comment]
修正しました。10.2系フォルダの publisher-20180826.ttl に置いておきます。確認よろ。 @masao

**Comment by masao** [comment]
修正を追加しました。

**Comment by yegusa** [comment]
確認しました。クローズします。
