### ISSUE TITLE
publiser.ttl: 光村：光村図書→光村図書出版株式会社、法人番号追加

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#321]
光村

- 法人番号の追加
- 2001〜2017 光村図書→光村図書出版株式会社 
  - https://w3id.org/jp-textbook/publisher/2001/光村
  - https://w3id.org/jp-textbook/publisher/2017/光村

**Comment by yegusa** [comment]
修正しました。10.2系フォルダの publisher-20180826.ttl に置いておきます。確認よろ。 @masao

**Comment by masao** [comment]
修正を追加しました。

**Comment by yegusa** [comment]
確認しました。クローズします。
