### ISSUE TITLE
textbook.ttl修正: 発行者略称：啓林 --> 啓林館　（発行者番号：61）

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#323]
発行者URIに関わるので教育図書館に修正してもらう必要あり。

- [x] 教育図書館へ連絡（2018-10-04）
- [x] データ入手
- [x] 確認

発行者番号：61の発行者略称：啓林 --> 啓林館
https://w3id.org/jp-textbook/高等学校/1994/英II/570

https://nieropac.nier.go.jp/ebopac/EB10024181

publiser.ttl 修正は #324

**Comment by yegusa** [comment]
教育図書館からデータを入手しました。2018-10-25付のデータです。list_EB20181025.txt です。まだ、学習指導要領URIをつけるなどの作業はしていません。

**Comment by yegusa** [comment]
発行者番号：61の発行者略称：啓林 --> 啓林館
https://nieropac.nier.go.jp/ebopac/EB10024181

となっていることを確認しました

**Comment by yegusa** [comment]
学習指導要領URI付与しました。10.5系/textbook-NIER20181108由来_JTRC20180622由来.xls にデータを置いておきます。

**Comment by masao** [comment]
修正を反映しました。

**Comment by yegusa** [comment]
確認しましたので、クローズします。
