### ISSUE TITLE
publisher.ttl修正: 発行者略称：啓林 --> 啓林館　（発行者番号：61）

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#324]
- [x] 1. #323 でtextbook.ttlを作成
- [x] 2. publisher.xlsx の Excelのデータを修正　（textbook:publisher/1994/啓林の行を消す）
- [x] 3. publisher.ttl を作成

発行者略称：啓林 --> 啓林館　（発行者番号：61）
https://w3id.org/jp-textbook/publisher/1994/啓林 （これを消す）
--> https://w3id.org/jp-textbook/publisher/1994/啓林館  （この行はすでにある）

教科書リソースtextbook.ttl は #323

**Comment by yegusa** [comment]
修正しました。10.2系フォルダの publisher-20180826.ttl に置いておきます。確認よろ。 @masao

**Comment by masao** [comment]
#323 と同時でないと、相互リンクがずれるため、両者を同時に修正する必要あり。

**Comment by yegusa** [comment]
一旦、元に戻したものを作成しておきます。教育図書館が教科書書誌データを直したものを入手した後に修正します（まあ、二重にできちゃってるので最悪直さなくても大丈夫だったりしますが。。。）。

10.2系フォルダ 20180826-3.ttlです。

**Comment by yegusa** [comment]
教育図書館からデータを入手しました。2018-10-25付のデータです。list_EB20181025.txt です。まだ、学習指導要領URIをつけるなどの作業はしていません。

**Comment by yegusa** [comment]
作成しました。10.5系/publisher-20181108.ttl に置いておきました。

**Comment by masao** [comment]
修正を反映しました。

**Comment by yegusa** [comment]
確認しましたので、クローズします。
