### ISSUE TITLE
publisher.ttl 発行者名の修正：新興出版啓林館--> 株式会社 新興出版社啓林館など　（発行者番号：61）

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#326]

**Comment by yegusa** [comment]
修正しました。10.2系フォルダの publisher-20180826.ttl に置いておきます。確認よろ。 @masao

**Comment by masao** [comment]
修正を追加しました。

**Comment by yegusa** [comment]
https://w3id.org/jp-textbook/publisher/2001/啓林館

確認しました。クローズします。
