### ISSUE TITLE
publisher.ttl 発行者名修正：発行者名の修正：山川出版 → 株式会社 山川出版社

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#328]

**Comment by yegusa** [comment]
修正しました。10.2系フォルダの publisher-20180826.ttl に置いておきます。確認よろ。 @masao

**Comment by masao** [comment]
修正を追加しました。

**Comment by yegusa** [comment]
https://w3id.org/jp-textbook/publisher/2006/山川
確認しました。クローズします。
