### ISSUE TITLE
publisher.ttl:発行者番号の修正：158 -> 199 現美

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#329]
現美 
発行者番号の修正：158 -> 199 
https://w3id.org/jp-textbook/publisher/1991/現美

**Comment by yegusa** [comment]
10.2系フォルダに publisher-20180826-2.ttl として置いておきました

**Comment by masao** [comment]
修正を追加しました。

**Comment by yegusa** [comment]
確認しました。クローズします。
