### ISSUE TITLE
subject.ttl and subjectArea.ttl: URI違い?

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#332]
各版で見られる英訳出典リンクの textbook:curriculum/小学校/2012 は 末尾「/2011」の誤りでは?
#331 のチェックから。

**Comment by yegusa** [comment]
おっとそうでしたね。修正しておきました。

10.2系フォルダの subject-20180827.ttl, subjectArea-20180827.ttl です。

**Comment by masao** [comment]
修正を追加しました。

**Comment by yegusa** [comment]
確認しました。クローズします。
例：https://w3id.org/jp-textbook/curriculum/小学校/2011/国語/国語
