### ISSUE TITLE
publiser.ttl 発行者名、dbpdia修正 桐原書店→ピアソン桐原（発行者番号 212）

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#336]
publiser.ttl 発行者名、dbpdia修正 桐原書店→ピアソン桐原（発行者番号 212）

https://w3id.org/jp-textbook/publisher/2012/桐原
https://w3id.org/jp-textbook/publisher/2013/桐原

**Comment by yegusa** [comment]
修正しました。10.2系フォルダに publisher-20180826-3.ttl として置いておきました。

**Comment by masao** [comment]
修正を追加しました。

**Comment by yegusa** [comment]
確認しました。クローズします。
