### ISSUE TITLE
学習指導要領リソースURIに対応したページを作成する

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#34]
メタデータとして、施行年等の情報、プラス教科と種目の一覧がほしい。

- [x] 本文URLデータの作成
- [x] 教科のデータの作成 #53 （バージョン2）で完了
- [x] 科目データの作成 #2 も参照
- [x] ttl 変換プログラムの開発 #2も参照

**Comment by yegusa** [comment]
ttl化するときのプロパティのメモ

学習指導要領 -- textbook:hasSubject --> 科目
教科 -- skos:narrower --> 科目

**Comment by masao** [comment]
学習指導要領 -- textbook:hasSubjectArea --> 教科

**Comment by yegusa** [comment]
学習指導要領に、「種目」の一覧って？「教科」だけでなく、「種目」も？

**Comment by masao** [comment]
一通り開発しました。確認願います。

**Comment by yegusa** [comment]
よさそうです。クローズします。
