### ISSUE TITLE
publisher.ttl 発行者番号の修正：　288-> 228 （発行者略称：山下）

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#342]
発行者番号の修正：　288-> 228 （発行者略称：山下）

https://w3id.org/jp-textbook/publisher/2012/山下

**Comment by yegusa** [comment]
修正しました。10.2系フォルダに publisher-20180826-3.ttl として置いておきました。

**Comment by masao** [comment]
修正しました。

**Comment by yegusa** [comment]
確認しました。クローズします。
