### ISSUE TITLE
textbook.ttl と publisher.ttl: 発行者略称：秀文--> 秀文館 （発行者番号：214）

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#344]
https://w3id.org/jp-textbook/publisher/2001/秀文
  --> https://w3id.org/jp-textbook/publisher/2001/秀文館

発行者URIに関わるので、
- [x] 1. 教育図書館に連絡(2018-10-04)
- [x] 2. 教科書書誌データを入手
- [x] 3. 確認　
- [x] 4. textbook.ttl の元データxlsxを作成
- [x] 4. publisher.ttlを修正

発行者略称：秀文--> 秀文館
https://nieropac.nier.go.jp/ebopac/EB10015332
https://nieropac.nier.go.jp/ebopac/EB10015331
https://nieropac.nier.go.jp/ebopac/EB10015333

https://w3id.org/jp-textbook/中学校/2001/英語/807
https://w3id.org/jp-textbook/中学校/2001/英語/707
https://w3id.org/jp-textbook/中学校/2001/英語/907

https://w3id.org/jp-textbook/publisher/2001/秀文館

**Comment by yegusa** [comment]
教育図書館から修正連絡きたが、データをもらわないと確かめられないので、データもらってから確かめる。

**Comment by yegusa** [comment]
教育図書館からデータを入手しました。2018-10-25付のデータです。list_EB20181025.txt です。まだ、学習指導要領URIをつけるなどの作業はしていません。

**Comment by yegusa** [comment]
発行者略称：秀文--> 秀文館
https://nieropac.nier.go.jp/ebopac/EB10015332
https://nieropac.nier.go.jp/ebopac/EB10015331
https://nieropac.nier.go.jp/ebopac/EB10015333

となっていることを確認しました。

**Comment by yegusa** [comment]
教科書書誌データの方の修正はやりました。学習指導要領URI付与しました。10.5系/textbook-NIER20181108由来_JTRC20180622由来.xls にデータを置いておきます。

**Comment by yegusa** [comment]
作成しました。10.5系/publisher-20181108.ttl に置いておきました。

**Comment by masao** [comment]
ttlデータに関係ない、古い出版社データが含まれてしまっているようです。
https://w3id.org/jp-textbook/publisher/1947/実教 など。

**Comment by yegusa** [comment]
Excelデータは、教科書目録の発行者一覧から作成しているデータですので、
教科書のレコードがない発行者情報については、ruby プログラムの方で弾いたものを作成するようにしてもらえると助かります。

最初にpublisher.ttlのデータを作った時は、教科書のレコードがあるかどうか、vlookupやピボットテーブルなどを駆使して、確かめて、あるものだけを、publisher.ttlに出していたみたいなのですが、
教科書レコードがある発行者URIかどうかをExcelの方でやるとなると、できなくはないですが、手間がが多すぎて、今回のような改定のタイミングで作り直すのを失敗しそう（ピボットテーブルやvlookupを駆使する必要があるので）。

現在の対象教科書は、1992年使用教科書から始まっている教科書なので、1991年発行の教科書目録よりあたらしい発行者一覧を一律に採用するであれば、Excel的には楽なのでやりやすいとは思います。
その場合、教科書レコードがない発行者が若干混じる可能性はあるかもしれません。

**Comment by yegusa** [comment]
教科書レコードがなくても、あってもいいのではと、個人的には思いますが。教科書レコードは、あくまでも、最初の使用年のものだけへリンクを張る感じになるので。

**Comment by yegusa** [comment]
発行者情報全体のttl生成方式の変更は #368 を参照のこと。こちらのissue は　秀文--> 秀文館 （発行者番号：214）のみを扱うissueとする。

**Comment by masao** [comment]
修正を反映しました。

**Comment by yegusa** [comment]
確認しましたので、クローズします。
