### ISSUE TITLE
textbook.ttl 大阪書籍・日文例外処理：textbook:publisher/2009/日文 対応

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#345]
例の大阪書籍・日文例外処理が、発行者URIに対応できていないようです。

![linked open data lod](https://user-images.githubusercontent.com/1328499/44675733-512e9f80-aa6c-11e8-83d9-0f3f941ea590.png)

https://w3id.org/jp-textbook/高等学校/2004/書III/002
https://w3id.org/jp-textbook/中学校/2005/地理/709
https://w3id.org/jp-textbook/小学校/2004/国語/115
https://w3id.org/jp-textbook/小学校/2004/国語/215
https://w3id.org/jp-textbook/小学校/2004/国語/116
https://w3id.org/jp-textbook/中学校/2005/書写/710
https://w3id.org/jp-textbook/中学校/2005/書写/810
https://w3id.org/jp-textbook/中学校/2005/数学/708
https://w3id.org/jp-textbook/中学校/2005/数学/808
https://w3id.org/jp-textbook/中学校/2005/数学/908
https://w3id.org/jp-textbook/小学校/2004/国語/216
https://w3id.org/jp-textbook/小学校/2004/国語/315
https://w3id.org/jp-textbook/小学校/2004/国語/316
https://w3id.org/jp-textbook/小学校/2004/国語/415
https://w3id.org/jp-textbook/小学校/2004/国語/416
https://w3id.org/jp-textbook/小学校/2004/国語/515
https://w3id.org/jp-textbook/小学校/2004/国語/516
https://w3id.org/jp-textbook/小学校/2004/国語/615
https://w3id.org/jp-textbook/小学校/2004/国語/616
https://w3id.org/jp-textbook/高等学校/2007/書II/009

（ #331 のチェックにて思い出した）

**Comment by yegusa** [comment]
参考：最近も、別の出版社で同様のパターンあるんだね。

右文書院　→ 文英堂
https://w3id.org/jp-textbook/高等学校/2014/古A/309
https://w3id.org/jp-textbook/高等学校/2014/古A/311
https://w3id.org/jp-textbook/高等学校/2013/古B/319

**Comment by masao** [comment]
修正しました。

**Comment by yegusa** [comment]
確認しました。クローズします。

![linked open data lod 1](https://user-images.githubusercontent.com/1328499/45138978-3a651700-b1e9-11e8-99fb-1101ba9625d1.png)
