### ISSUE TITLE
HTML: 教科書の「掲載教科書目録」への複数リンク

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#347]
#81 （教科書目録リソースページから教科書へリンク）とも関連します。

#81 で全ての教科書目録のページに、初掲載の教科書だけでなく、
当該教科書目録に載っている全教科書がリストされていることが前提ですが、
発行者リソースの「同一発行者」のような感じで、
一番下に「同一使用年教科書」（ラベルは工夫の余地あり）とでもして、
実際の使用年から全ての教科書目録へのページへリンクがあったらいいなあと思います。
こんな感じで。

同一使用年教科書
[2013](https://w3id.org/jp-textbook/catalogue/高等学校/2012) [2014](https://w3id.org/jp-textbook/catalogue/高等学校/2013) [2015](https://w3id.org/jp-textbook/catalogue/高等学校/2014) [2016](https://w3id.org/jp-textbook/catalogue/高等学校/2015)

（関連 #346 使用年を開始・終了のデータにする）

**Comment by yegusa** [comment]
位置は赤四角のあたりか？

https://w3id.org/jp-textbook/高等学校/2012/国総/301
![linked open data lod 1](https://user-images.githubusercontent.com/1328499/44702179-1a3ca600-aacd-11e8-9850-d62a6c02854f.png)

**Comment by masao** [comment]
https://jp-textbook.github.io/curriculum/%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1/2013/%E5%9B%BD%E8%AA%9E/%E5%9B%BD%E8%AA%9E%E7%B7%8F%E5%90%88 ではダメ？

**Comment by masao** [comment]
では、「初出教科書目録」として詳細にのせるのをやめて、「教科書目録」として掲載部分をすべてリンクするだけでOK.

**Comment by yegusa** [comment]
こんなイメージ

使用年度 2011-2012 (平成23年-平成24年)
掲載教科書目録（発行年）　2010 (平成22年)　2011 (平成23年)

もしくは、URIとずれるけど

使用年度 2011-2012 (平成23年-平成24年)
掲載教科書目録（使用年度）　2011 (平成23年)　2012 (平成24年)

**Comment by masao** [comment]
リンクを追加しました。

**Comment by yegusa** [comment]
できていることを確認しました。いいですね〜。

![linked open data lod 1](https://user-images.githubusercontent.com/1328499/48981320-24476280-f117-11e8-8864-2d66aee020ee.png)
