### ISSUE TITLE
textbook.ttl 使用年度が「2017」（2017-2017 or 2017- or 2017-2018のどれかのはず）

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#348]
- [x] 教育図書館に連絡（2018-10-04）
- [x] 修正
- [x] 確認
- [x] データ入手

使用年度が「2017」（2017-2017 or 2017- or 2017-2018のどれかのはず）
https://w3id.org/jp-textbook/高等学校/2014/古A/309
https://w3id.org/jp-textbook/高等学校/2014/古A/311
https://w3id.org/jp-textbook/高等学校/2013/古B/319

https://nieropac.nier.go.jp/ebopac/EB20036186
https://nieropac.nier.go.jp/ebopac/EB20036188
https://nieropac.nier.go.jp/ebopac/EB20036190

**Comment by yegusa** [comment]
平成29年度使用教科書目録に載っているので、「2017-」ですね。

http://www.mext.go.jp/a_menu/shotou/kyoukasho/__icsFiles/afieldfile/2017/05/29/1384989_003_2.pdf#page=15
http://www.mext.go.jp/a_menu/shotou/kyoukasho/__icsFiles/afieldfile/2017/05/29/1384989_003_2.pdf#page=17

**Comment by yegusa** [comment]
> https://nieropac.nier.go.jp/ebopac/EB20036186

-->修正された

> https://nieropac.nier.go.jp/ebopac/EB20036188

-->修正ミス？　確認中

> https://nieropac.nier.go.jp/ebopac/EB20036190

--> 修正された

**Comment by yegusa** [comment]
https://nieropac.nier.go.jp/ebopac/EB20036188

-->修正確認

**Comment by yegusa** [comment]
修正されたのを確認しました。データはまだもらっていません。

**Comment by yegusa** [comment]
教育図書館からデータを入手しました。2018-10-25付のデータです。list_EB20181025.txt です。まだ、学習指導要領URIをつけるなどの作業はしていません。

**Comment by yegusa** [comment]
学習指導要領URI付与しました。10.5系/textbook-NIER20181108由来_JTRC20180622由来.xls にデータを置いておきます。

**Comment by masao** [comment]
修正を反映させました。

**Comment by yegusa** [comment]
確認したので、クローズします。
