### ISSUE TITLE
ファビコンを設定してほしい

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#349]
「ファビコンデータ」フォルダにデータを置いておきました
16, 32,128, 152 マルチサイズのファイルです。

favicon.ico

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
こんな感じ
![2018-08-30 2 40 26](https://user-images.githubusercontent.com/1328499/44805035-19576180-abfe-11e8-9772-3d553653c32f.png)

**Comment by yegusa** [comment]
できるようになりました！クローズします。

![2018-08-30 11 45 09](https://user-images.githubusercontent.com/1328499/44826491-2ef27880-ac4a-11e8-9da1-2171323c646e.png)
