### ISSUE TITLE
英語版ページからのTurtleリンクが切れている

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#356]
単にPath指定を間違えているので、要修正。

**Comment by masao** [comment]
リンク切れを修正しました。また、リンクチェック用スクリプトを追加しました。

**Comment by yegusa** [comment]
en/about.html, en/index.html の
*.ttl へのリンクだよね？

ちゃんと辿れることを確認しましたので、クローズします。
