### ISSUE TITLE
クラスやプロパティのページへのリンクをaboutからはる

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#357]
#182 からの派生です。

http://w3id.org/jp-textbook/Textbook
http://w3id.org/jp-textbook/school

などがどこからもリンクが貼られていないので、about からリンクを貼る

**Comment by yegusa** [comment]
こんだけありますね。

https://w3id.org/jp-textbook/Catalogue
https://w3id.org/jp-textbook/CurriculumGuideline
https://w3id.org/jp-textbook/Publisher
https://w3id.org/jp-textbook/School
https://w3id.org/jp-textbook/SubjectType
https://w3id.org/jp-textbook/Textbook
https://w3id.org/jp-textbook/SubjectArea
https://w3id.org/jp-textbook/Subject
https://w3id.org/jp-textbook/authorizedYear
https://w3id.org/jp-textbook/catalogue
https://w3id.org/jp-textbook/catalogueYear
https://w3id.org/jp-textbook/curriculum
https://w3id.org/jp-textbook/grade
https://w3id.org/jp-textbook/hasSubject
https://w3id.org/jp-textbook/hasSubjectArea
https://w3id.org/jp-textbook/item
https://w3id.org/jp-textbook/publisherAbbreviation
https://w3id.org/jp-textbook/publisherNumber
https://w3id.org/jp-textbook/school
https://w3id.org/jp-textbook/sourceOfEnglishName
https://w3id.org/jp-textbook/subject
https://w3id.org/jp-textbook/subjectArea
https://w3id.org/jp-textbook/subjectType
https://w3id.org/jp-textbook/textbookNumber
https://w3id.org/jp-textbook/textbookSymbol
https://w3id.org/jp-textbook/usageYear

**Comment by yegusa** [comment]
どう書いたらいいか迷っています。
 
ここのリソースごとに、
```html
          <p><small><span class="glyphicon glyphicon-link"></span> <a href="https://w3id.org/jp-textbook/Textbook">https://w3id.org/jp-textbook/Textbook</a></small></p>
```
こんな感じでつけるのだろうか。プロパティはどうしようか。。。

と悩んでいます。

とりあえず、いつまでも、どこからもリンクないのはいかがなものかと思うので、about の最後の方に、「独自語彙のスキーマ」として、いっぺんにリストであげておきますね。

**Comment by masao** [comment]
ひとまずリンクはされているのでクローズします。
あとは #359 を実施してから、それから自動生成する方向で考えましょう。
