### ISSUE TITLE
アプリケーションプロファイルを記述する

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#359]
現行のスキーマは単なる RDF スキーマレベルの語彙を定義しているだけなので、教科書LODが使用している外部語彙も含んだ全体のメタデータアプリケーションプロファイルを記述しておく。
これができれば、おそらく about ページの説明は全てそちらから自動生成できるはず。。。

具体的には、Description Set Profile の記述を追加したい。。

参考：
* アプリケーションプロファイルのためのシンガポールフレームワーク:
  * http://www.ndl.go.jp/jp/dlib/standards/translation/singapore.htm （和訳 by NDL）
  * http://dublincore.org/documents/singapore-framework/ （オリジナル文書）
* Description Set Profiles: A constraint language for Dublin Core Application Profiles: http://dublincore.org/documents/dc-dsp/
* 事例：
  * http://www.ukoln.ac.uk/repositories/digirep/index/SWAP (Scholarly Works Application Profile; ePrints)
  * http://colab.mpdl.mpg.de/mediawiki/ESciDoc_Application_Profiles (Escidoc Application Profiles)
  * https://pro.europeana.eu/page/edm-documentation (Europeana Data Model Documentation)
  * https://pro.dp.la/hubs/metadata-application-profile (DPLA Application Profile)

**Comment by yegusa** [comment]
とりあえず、ttlで、テキトーに作っちゃいましょう。あとで、正式な書き方がわかったらそれに変換するって作戦で良いのじゃないかなあ。aboutを書くのがだんだん辛くなってきましたので。あと、aboutの英語化もこれができればやりやすくなる気がするので。

**Comment by yegusa** [comment]
ttlで書くのは難しそうなので、インデントしただけの、適当な描きやすいフォーマットで、まずは書いてみるというのが良さそうだと 2018-11-27 FRBR&RDA勉強会にて。

**Comment by masao** [comment]
SHACLの記述を追加しました: https://jp-textbook.github.io/shape-20181214.ttl

**Comment by yegusa** [comment]
すごい！いいと思います。クローズします。
