### ISSUE TITLE
ISBN紐付けデータ作成方法の文書化

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#361]
#166 #167 等で、ISBNをキーとして自動的にCiNii BooksやNDLへのリンクを追加するスクリプトを作ったため、これを動作させる手順について文書化しておくこと。

**Comment by masao** [comment]
https://github.com/jp-textbook/jp-textbook.github.io/wiki Wikiのトップに並べておくこと。

**Comment by masao** [comment]
https://github.com/jp-textbook/jp-textbook.github.io/wiki#isbn%E3%81%A8%E3%81%9D%E3%81%AE%E4%BB%96%E8%AD%98%E5%88%A5%E5%AD%90%E3%81%A8%E3%81%AE%E9%96%A2%E9%80%A3%E4%BB%98%E3%81%91 追記しました。

**Comment by yegusa** [comment]
確認しました。クローズします。
