### ISSUE TITLE
使用年データの誤り： 小学校/2004/理科/421

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#365]
- [x] 教育図書館に連絡
- [x] 修正
- [x] 確認
- [x] データ入手

#346 の処理中に見つけた誤りデータ。

https://w3id.org/jp-textbook/小学校/2004/理科/421
```
  textbook:usageYear "2005-2001";
```
使用年の終了は2011の誤字とか？？

**Comment by yegusa** [comment]
教育図書館に連絡して、教育図書館のシステムの方は、
2005-2010
に修正されました。

まだ、データはもらっていません。

**Comment by yegusa** [comment]
教育図書館からデータを入手しました。2018-10-25付のデータです。list_EB20181025.txt です。まだ、学習指導要領URIをつけるなどの作業はしていません。

**Comment by yegusa** [comment]
学習指導要領URI付与しました。10.5系/textbook-NIER20181108由来_JTRC20180622由来.xls にデータを置いておきます。

**Comment by masao** [comment]
修正を確認しました。

**Comment by yegusa** [comment]
確認しましたのでクローズします。
