### ISSUE TITLE
教科書リソースにある「発行者リソースの「年」」の生成方法について確認・修正？

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#366]
教科書リソースにある「発行者リソースの「年」」の生成方法について確認する。

教育図書館が入力した、
「初出教科書目録の発行年」（元データの列タイトル：「★教科書目録掲載年度」）
を使っていないか確認する。

#346 #360 で、「使用年度」から「教科書目録の発行年」を計算することになったことの影響の確認が必要。

例えば、以下の教科書リソースでは、
https://w3id.org/jp-textbook/小学校/2010/国語/101

以下のようになっている：

- 使用年度：2011-2014 (平成23年-平成26年)
- 検定年：2010(平成22年)
- 初出教科書目録の発行年：2010 (平成22年)

これの、発行者リソースは
https://w3id.org/jp-textbook/publisher/2010/東書

となっている。
この2010/東書の2010を、使用年度の最初の年-1 とする必要があることに注意

現在、どのように生成しているか確認し、修正が必要そうなら修正すること。

**Comment by masao** [comment]
https://github.com/jp-textbook/jp-textbook.github.io/blob/master/xlsx2ttl.rb#L87
はい、「初出教科書目録の発行年」（元データの列タイトル：「★教科書目録掲載年度」）を使ってますね。

**Comment by yegusa** [comment]
じゃあ、「最初の使用年-1」を使うように変更する必要がありますね。

**Comment by masao** [comment]
修正しました。

**Comment by yegusa** [comment]
どう確認したらよいかわからんけど、まあ、ええと思います。クローズします。
