### ISSUE TITLE
publisher.ttl生成方式の変更

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#368]
#344 からの派生。<s> 発行者情報のTurtleデータはExcelから自動生成するように方法を変更する。
（不要な発行者情報をフィルタリングすること）</s>

**Comment by yegusa** [comment]
先ほどの話しあいにて、教科書レコードにひもづく、発行者レコードのみを残すのではなくて、1991年発行の教科書目録よりあたらしい発行者一覧を一律に採用することにしました（現在の対象教科書は、1992年使用教科書から始まっている教科書なので）。

Excel的に、作成が楽なので、この方式とすることとしました。
その場合、教科書レコードがない発行者が若干混じる可能性はあるのは注意です。

**Comment by yegusa** [comment]
1991年発行の教科書目録よりあたらしい発行者一覧にあるものだけを抜き出したpublisher-20181123.ttlを作成しました。10.5系フォルダに入れておきます。よろしく。

**Comment by masao** [comment]
修正を反映しました。

**Comment by yegusa** [comment]
diff見た感じだと、1991年のが増えた感じですね。まあ、シャーないかな。いいと思います。確認しましたので、クローズします。
