### ISSUE TITLE
HTML：トップページに学習指導要領へのページへのリンクを貼るはどうか

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#371]
今だと、学習指導要領に辿りづらい。

トップページの、教科書のリンクの下あたりに、
以下のようなリンクがあると嬉しい。

----
### 学習指導要領

- 小学校
  - [2008年3月告示（2011年4月施行）](https://w3id.org/jp-textbook/curriculum/小学校/2011)
  - [1998年3月告示（2002年4月施行）](https://w3id.org/jp-textbook/curriculum/小学校/2002)
  - [1989年3月告示（1992年4月施行）](https://w3id.org/jp-textbook/curriculum/小学校/1992)
- 中学校
  - リンク
  - リンク
  - リンク
- 高等学校
  - リンク
  - リンク
  - リンク

**Comment by masao** [comment]
ひとまず、アスタリスクかアイコンなどでリンクをはること。
以下、アスタリスク部分からリンクが張られるイメージ：

* 小学校 [*] 
  * 国語 書写 社会 地図 算数 理科 生活 音楽 図画工作 家庭 保健 道徳
* 中学校 [*]
  * 国語 書写 社会(地理的分野) 社会(歴史的分野) 社会(公民的分野) 地図 数学 理科 音楽(一般) 音楽(器楽合奏) 美術 保健体育 技術・家庭(技術分野) 技術・家庭(家庭分野) 英語

**Comment by yegusa** [comment]
こんなアイコンを使うのでもいいかも？

http://icooon-mono.com/15943-%E8%BE%9E%E6%9B%B8%E3%82%A2%E3%82%A4%E3%82%B3%E3%83%B31/

**Comment by masao** [comment]
以下のような感じでしょうか。やはりアイコンだけでもよいかな。。。
![linked open data lod](https://user-images.githubusercontent.com/38825/51297234-d853d280-1a62-11e9-9758-019733c98fbd.png)

**Comment by yegusa** [comment]
いいと思います。学習指導要領って書いてあったほうが。

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
いいですね！確認しましたのでクローズします。
