### ISSUE TITLE
HTML：トップページに教科書目録へのページへのリンクを貼るはどうか

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#372]
#81 （教科書目録ページから教科書へのリンクを追加する）が終わった後で良いと思いますが、以下のようなリンクがトップページにあると非常に便利だと思います。
教科書目録のアンカーは発行年がいいか、教科書の使用年がいいかは微妙かな。
なんとなく、使用年がいいような気がする。

----

### 教科書目録

以下のリンクは掲載教科書の使用年度を表しています。

- 小学校　[2018](https://w3id.org/jp-textbook/catalogue/小学校/2017) [2017](https://w3id.org/jp-textbook/catalogue/小学校/2016)		2016	2015	2014	2013	2012	2011	2010	2009	2008	2007	2006	2005	2004	2003	2002	2001	2000	1999	1998	1997	1996	1995	1994	1993	1992	1991
- 中学校　2018	2017	2016	2015	2014	2013	2012	2011	2010	2009	2008	2007	2006	2005	2004	2003	2002	2001	2000	1999	1998	1997	1996	1995	1994	1993	1992	1991
- 高等学校　2018	2017	2016	2015	2014	2013	2012	2011	2010	2009	2008	2007	2006	2005	2004	2003	2002	2001	2000	1999	1998	1997	1996	1995	1994	1993	1992	1991

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
以下の教科書はないんですけど、ま、いいか。

- 中学校 1992年度使用 https://w3id.org/jp-textbook/catalogue/中学校/1991
- 高等学校 1992年度使用 https://w3id.org/jp-textbook/catalogue/高等学校/1991
- 高等学校 1993年度使用 https://w3id.org/jp-textbook/catalogue/高等学校/1992

いい感じだと思います、クローズします。
