### ISSUE TITLE
HTML(教科書目録ページ)：高校の教科書は学習指導要領ごとに表示してほしい

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#373]
#81 からの派生です。

高校は年次進行なので、複数の学習指導要領が混じっていますので、
学習指導要領ごとに分けて表示してあると嬉しいです。

https://w3id.org/jp-textbook/catalogue/高等学校/2015

以下のような感じで、古い学習指導要領対応のほうが下かな。

----

### 高等学校 学習指導要領 (2013年度以降) 

- 化学基礎 (東京書籍株式会社) （2012-2016）
- 新編化学基礎 (東京書籍株式会社) （2012-2016）
- 化学基礎 (実教出版株式会社) （2012-2016）
- 新版化学基礎 (実教出版株式会社) （2012-2016）
- 高校化学基礎 (実教出版株式会社) （2012-2016）
- 化学基礎 (株式会社 新興出版社啓林館) （2012-2017）
- 化学基礎 (数研出版株式会社) （2012-2016）
・・・・・・省略

### 高等学校 学習指導要領 (2003年度以降)
 
- ビジネス基礎 -よりよい社会人をめざして- (暁出版株式会社) （2003-2017）
- Information Technology for Business 情報処理 (暁出版株式会社) （2003-2017）
- 情報A Living in IT World (暁出版株式会社) （2003-2017）
- 商業技術 : ビジネス社会で活かそう (暁出版株式会社) （2004-2017）
- 農業経営 (社団法人 農山漁村文化協会) （2004-2017）
- 経済活動と法 -くらしに役立つ法律- (暁出版株式会社) （2005-2017）
- 畜産 (社団法人 農山漁村文化協会) （2005-2017）
- 世界を学ぶ 高校生の地理A 最新版 (株式会社帝国書院) （2007-2016）
- 新生活技術 ともに生きる くらしをつくる (教育図書株式会社) （2007-2017）
- 新版フードデザイン COOKING & ARRANGEMENT (教育図書株式会社) （2008-2017）
- 書III (教育図書株式会社) （2009-2017）

(メモ：2013年以降のはずなのに、2012年があるのは、先行実施があるからだと思われます。これも学習指導要領に備考で書いておいたほうがいいかもね。別issueにします。)

**Comment by masao** [comment]
指導要領ごとの区分を表示するように変更しました。

**Comment by yegusa** [comment]
#384 の関係ですね。教科書レコードの方に使用年度の終了年がないのでそうなっているっぽいですね。

**Comment by yegusa** [comment]
このissue自体はできているので，クローズします。
