### ISSUE TITLE
HTML(教科書目録ページ)：教科書のソート方法を工夫してほしい

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#374]
#81 からの派生です。
HTML(教科書目録ページ)：教科書のソート方法を工夫してほしい
		
ソートのキーですが
		
第1キー：トップページと同様の教科・種目の順
第2キー：出版社
第3キー：検定年
		
あたりが理想かなあ。

（開発面倒そうだけど）

**Comment by masao** [comment]
修正してみました。

**Comment by yegusa** [comment]
いいと思います！クローズします。
