### ISSUE TITLE
教科書目録リンク先誤り: 高等学校/2010

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#376]
https://w3id.org/jp-textbook/catalogue/高等学校/2010 のリンク先が　http://www.mext.go.jp/component/a_menu/education/detail/__icsFiles/afieldfile/2013/02/18/1293921_1.pdf となっているが、これは支援学校用なので、別URLと混じってしまっている模様。。。

**Comment by yegusa** [comment]
修正して11.1系フォルダにcatalogue-20181130.ttl作成しておきました。

**Comment by masao** [comment]
修正しました。

**Comment by yegusa** [comment]
確認しました。のでクローズします。
