### ISSUE TITLE
発行者情報の不整合： 2009/自由社

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#377]
#366 に関連して。#366 にて指摘を受けた方式で発行者情報へのリンク生成方式を変更しようとしましたが。

リンク先が不整合になる現象アリ。要確認。

例： https://w3id.org/jp-textbook/中学校/2009/歴史/717
発行者リソースのリンク先が、使用年情報によれば、 https://w3id.org/jp-textbook/publisher/2009/自由社 になるはずだが、この発行者リソースはリンク先が存在しない。

目録の問題か、もとの教科書情報の問題か？

**Comment by yegusa** [comment]
教育図書館システムにのみ関係：「元データの「初出教科書目録発行年」＝　使用年度の最初の年 - 1」となっていないデータが大量にある #360

が影響しているのではないかと思われます。

発行者情報は、もともと、教育図書館のレコードから、元データの「初出教科書目録発行年」を使って
大元のデータを作って、そのあとブラッシュアップするという手順をとったので。。。

#360 のをみて、
publisher.ttl 発行者情報のデータを作り直すのが良いと思います。

**Comment by yegusa** [comment]
#360 のをみて、これで変わってしまうレコードのもののうち、発行者情報がないものを追加しました。これで多分大丈夫なはず。　11.1系フォルダに publisher-20181130.ttlを作って置いておきました。

### 新規追加

- textbook:publisher/1991/医教研
- textbook:publisher/1991/文教社
- textbook:publisher/1995/文教社
- textbook:publisher/1999/開隆堂
- textbook:publisher/1999/学研
- textbook:publisher/1999/文教社

### 2008のレコードを2009に修正

- textbook:publisher/2009/自由社  

（もともと、元データを作った時に「教科書目録2008年には発行者一覧に掲載されてなかったので、2011年の発行者一覧の情報による。]」とあったので、2008を2009に修正した）

**Comment by masao** [comment]
修正を反映させました。

**Comment by yegusa** [comment]
上記、7つの発行者情報が見れることを確認しましたので、クローズします。
