### ISSUE TITLE
データ入力：高校の専門の「種目」を書名から類推して入力してはどうか？

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#390]
数件（1桁）の例外を除いては，
書名からかなり確実に類推できそうです。

せっかくなので，追加してもいいかなと思います。

教科を絞った上で，種目名の最長一致をすればほぼ全件できそうだということはわかりました。

**Comment by yegusa** [comment]
とりあえず，「建築設計製図」は例外として処理して，スクリプトでできるかやってみる。
（スクリプト作成後，人手でやったデータと一応，確認はすることとして）

**Comment by yegusa** [comment]
「経営」も最長一致ではないので例外ですね。

**Comment by masao** [comment]
一通り追加してみました。

例外部分はコードに埋め込んでしまっています...:
https://github.com/jp-textbook/jp-textbook.github.io/blob/master/xlsx2ttl.rb#L129

**Comment by yegusa** [comment]
素敵！いい感じじゃないですかああ。
これは、目玉な修正だと、個人的には思います。
できているようなので、クローズします。


 https://w3id.org/jp-textbook/高等学校/2012/商業/312
これに、種目「プログラミング」が入っている

https://w3id.org/jp-textbook/curriculum/高等学校/2013/商業/プログラミング
これに、教科書リストが一覧される
