### ISSUE TITLE
about 教科書リソースの数をupdate

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#393]
> 2017年1月現在、約7000タイトルの教科書情報

7575件？ なので，

2018年12月現在、約7500タイトルの教科書情報 でしょうか？

@masao 数えてもらえませんか？

**Comment by masao** [comment]
はい、7548タイトルというので正しいようです。

**Comment by masao** [comment]
一応、SPARQLでも同じ数になることを確認しました：

```ruby
require "sparql"
require_relative "util.rb"
include Textbook
f = find_turtle("all.ttl")
q = SPARQL.parse("SELECT (count(distinct ?s) as ?count ) where { ?s a <https://w3id.org/jp-textbook/Textbook>. } ")
data = RDF::Repository.load(f)
q.execute(data)

=> [#<RDF::Query::Solution:0x3fa4fd6c3428({:count=>#<RDF::Literal::Integer:0x3fa4fcf1396c("7548"^^<http://www.w3.org/2001/XMLSchema#integer>)>})>]
```

**Comment by yegusa** [comment]
ありがとう。aboutの修正って，今まで通り，about.htmlを修正しても大丈夫？

**Comment by masao** [comment]
template/about.*.erb を修正する必要があります。もしくは、shape-yyyymmdd.tyl か。

**Comment by yegusa** [comment]
about.htmlの更新方法がわからなかったので，template/about.*.erb のみを修正しました。

**Comment by masao** [comment]
更新しました。

**Comment by masao** [comment]
https://github.com/jp-textbook/jp-textbook.github.io/wiki#about%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88%E3%83%9A%E3%83%BC%E3%82%B8%E3%81%AE%E6%9B%B4%E6%96%B0%E6%89%8B%E9%A0%86 更新手順についてはWikiのほうに書いておきました。

**Comment by yegusa** [comment]
ありがとー。aboutも更新方法も確認しましたので，クローズします。
