### ISSUE TITLE
SHACLファイルの作り方を検討する

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#396]
#359 #395 からの派生です

手で，SHACLファイルを書くのは面倒なので，
入力するデータは，Excelでしょうか？

Excel -- ruby --> ttl　？

**Comment by yegusa** [comment]
後回し。

**Comment by masao** [comment]
入れ子（ブランクノード）になっているものがExcel方式では書きづらいのが難点。
良い案は思いうかばないので、ペンディング。

**Comment by yegusa** [comment]
ブランクノードだけは、別Excelに書いて処理ってのがいいのじゃないかなあ。

**Comment by masao** [comment]
Excelシートごとに一つのShape情報をかけるようにしました。

**Comment by masao** [comment]
また、ブランクノードにもURIを振るようにしました。

**Comment by yegusa** [comment]
書き方はどこを見ればわかりますか？

**Comment by masao** [comment]
ttlの元データ\13.2系 のフォルダに置いてあります:
マニュアルをどこかに書いておく必要アリですが...（未了）

![image](https://user-images.githubusercontent.com/38825/76691702-f6ca5380-6690-11ea-9191-33584a07e903.png)

**Comment by masao** [comment]
Excelファイルの作り方：

## ヘッダ

第1行目はヘッダとして扱う。
ただし、一番左のセルにはそのシートが表すShapeの名称としてURIを書く。
その右側には、それぞれの列内容を表すSHACLの要素になるものを書いておく：

```
 sh:path  sh:name@ja  sh:name@en  sh:description@ja  sh:description@en  skos:example 
 sh:maxCount  sh:minCount  sh:class  sh:datatype  sh:node  sh:nodeKind  sh:languageIn 
 sh:uniqueLang
```

このうち、`@en`, `@ja` が末尾に置かれた列は、それぞれの言語に対応する項目となる。つまり、`sh:name@ja`の場合、この列に書かれた情報は sh:name プロパティに対応するデータ内容に言語タグ付きの文字列として表現される（以下の例の sh:name プロパティを参照のこと）。

```turtle
 sh:property [
    sh:path textbook:CurriculumGuideline;
    sh:name "名称"@ja;
    sh:name "Name"@en;
  ];
```

## 各行の情報

Shape情報は基本的にはプロパティの様式を示すため、`sh:property` 行から構成される。
`sh:property` 行以外では `sh:targetClass` プロパティだけに対応している。
`sh:targetClass` 行ではその隣のセルに該当する対象クラスURIを記述する。

## TODO

`@prefix` を書く場所がないため、`sh:` 名前空間を除くすべてのURIはフルURIとして書き込む必要がある。

現状のExcelファイルに存在するフィールド以外には対応していないため、それ以外のケースに対応すべきか検討が必要となる。

**Comment by yegusa** [comment]
ありがとうございます。確認しました。

クローズします。
