### ISSUE TITLE
about: subjectTypeリソースの説明を追加

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#399]
- [x] subjectType のリソースの表　教科書リソースなどと合わせて，説明を追加する
- [x] 種目リソースのプロパティの説明を詳細に
- [x] 教科リソースのプロパティの説明を詳細に

**Comment by masao** [comment]
#395 のときに追加済み。内容を確認したらクローズしてよいと思います。

**Comment by yegusa** [comment]
「教科・種目種別をあらわすリソース」ですね。説明があることを確認したのでクローズします。
