### ISSUE TITLE
ISBN情報のデータ入力（教育図書館のデータにないデータ）

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#4]
現在はレコード情報として採録していないので、入力する方法から要検討。

**Comment by yegusa** [comment]
例：isbnをいれるとつながるもの

http://ci.nii.ac.jp/ncid/BA8579666X
http://iss.ndl.go.jp/books/R100000002-I000009370252-00

**Comment by yegusa** [comment]
教育図書館と相談してみました。CiNiiやNDLsearchとつながるのは良さそうだということで、入力を検討してもらえることになりました。

**Comment by yegusa** [comment]
3242件ほど（検定年2002年以降から入っているようです）、ISBNデータ入りの教科書書誌データを教科書研究センターからいただきました。5.2系のフォルダーにひとまずExcelデータを置いておきます。

**Comment by yegusa** [comment]
#152 を先にやる必要があります。

**Comment by yegusa** [comment]
2017-11-16 教育図書館から新しいデータ入手しました(list_EB20171116.txt)。このデータと教科書センターからいただいたデータの接合はまだやっていません。

**Comment by yegusa** [comment]
ttlにできる準備終了。 6.0系フォルダにいれておきました。

**Comment by masao** [comment]
ひとまず #152 とあわせて、教科書センターデータは追加するようにしました。

**Comment by yegusa** [comment]
こんなかんじですね。いいと思います。確認しましたので、クローズします。

入力例：

<https://w3id.org/jp-textbook/中学校/2005/保体/704> a schema:Book;
  textbook:item [
  textbook-rc:callNumber "B2|600|H17/18";
  textbook-rc:recordID "220050110"
  ];
  schema:isbn "4-487-12120-5".
