### ISSUE TITLE
タイトル修正：電子機器新訂版　→　電気機器新訂版

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#403]
- [x] 教育図書館に連絡
- [x] NIEROPAC修正
- [x] NIEROPAC確認
- [x] データ入手

#390 より派生

タイトル修正：電子機器新訂版　→　電気機器新訂版
https://w3id.org/jp-textbook/%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1/1998/%E5%B7%A5%E6%A5%AD/727

**Comment by yegusa** [comment]
NIEROPACのデータ修正は済んでいます。まだデータはもらっていません。

**Comment by yegusa** [comment]
データもらってます。20200302入手データはすでに反映されたものです。

**Comment by masao** [comment]
12.0として公開しました。

**Comment by yegusa** [comment]
確認しました。クローズします。
