### ISSUE TITLE
aboutの英語版のtextbook resources のプロパティの表の学校種別のdescriptionがない

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#408]
https://jp-textbook.github.io/en/about#textbook-resource

![about japanese textbook linked open data lod](https://user-images.githubusercontent.com/1328499/53857444-a0581d00-4019-11e9-878b-4daa9508188e.png)

**Comment by yegusa** [comment]
shape.ttl に 

sh:name "Type of schools"@en;

が抜けているみたいですね。

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
確認しました。クローズします。
