### ISSUE TITLE
中学校の教科「道徳」が必要

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#415]
#410 からの派生。

**Comment by yegusa** [comment]
追加しました。

12.0系フォルダに入れておきました。

subjectArea_20190620.ttl
subject_20190620.ttl

本当は，道徳は，先行実施なので，
次の学習指導要領として入れる必要がありますが，
次の学習指導要領の分はまだ入力していないので，
ただし，2011の学習指導要領として入れていることに注意が必要です。
（小学校の道徳も同様の状況）

**Comment by masao** [comment]
ひとまず追加しました。

**Comment by yegusa** [comment]
https://jp-textbook.github.io/curriculum/%E4%B8%AD%E5%AD%A6%E6%A0%A1/2012/%E9%81%93%E5%BE%B3/%E9%81%93%E5%BE%B3

中学校の道徳があることを確認したので、クローズします。
