### ISSUE TITLE
取り下げデータの扱い

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#418]
#417 からの派生。

EB20080272 のような取り下げデータ「[目次サンプル]精選現代文[改訂版]   (現文044)」にも指導要領URIが付いているので、取り下げデータの扱いを決める必要がある。

取り下げデータを判別するフィールド列を決めるか、もしくは、単純に指導要領URIを付けずにスキップできるようにする。

**Comment by yegusa** [comment]
学習指導要領URIがついていて、かつ、「公開レベル名称」列があるので、それを参照して、「表示する」となっているものだけを教科書LODの対象となり得るレコードにするというのがいいかなあ。

**Comment by yegusa** [comment]
教育図書館に聞いてきました。「状態区分名称」が「取り下げ」となっているものがテストデータなので、教科書LODに使わないでほしいとのことでした。こちらの列を参照して、「取り下げ」となっているのは、除外するのが良さそうです。

**Comment by masao** [comment]
コードは直しました。あとでまとめてチェックしましょう。

**Comment by yegusa** [comment]
EB20080272 が all-20200302.ttl にないことを確認したので、クローズします。
