### ISSUE TITLE
種目: 商業 のデータ

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#421]
#417 からの派生。

EB10026112 などで、種目が <https://w3id.org/jp-textbook/curriculum/高等学校/2003/商業/> となっている。これは種目がもともとないはずなので、なぜかついている点がバグか。

**Comment by masao** [comment]
原因がわかりました。旧システムでは「検索用種目」に「商業」がはいっていて、これと教科名が同一の場合に、種目は出力しないようにしていました。この検索用種目フィールドが新システムではなくなったので、ロジックを一部変更する必要あり。

**Comment by masao** [comment]
変更しました。

**Comment by yegusa** [comment]
> EB10026112 などで、種目が https://w3id.org/jp-textbook/curriculum/高等学校/2003/商業/ となっている。これは種目がもともとないはずなので、なぜかついている点がバグか。

https://w3id.org/jp-textbook/高等学校/2003/商業/012

の種目に「商業」がないことを確認したので、クローズします。
