### ISSUE TITLE
教育図書館メタデータID、教科書LODのURI、教科書センターへのURLのデータを作成するスクリプトが欲しい

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#422]
確認作業やデータ修正連絡などで、何かと必要になるので、毎回、Excelで作るのは辛いので、

- 教育図書館メタデータID
- 教育図書館OPACのURI
- 教科書LODのURI
- 教科書センターへのURL

のTSVデータを出力するスクリプトを開発してもらえると大変助かります。

**Comment by masao** [comment]
一部の教科書で 書誌と所蔵が 1対多 になっているのが面倒かもしれません。
特に、教育図書館と教科書センターの所蔵同士の対応関係はもっていないので、そこを出すのが無理そうです。

**Comment by masao** [comment]
うーん、次の問題。
#300 にある通り、教科書センターは直接リンクができません。。。

**Comment by masao** [comment]
Dropbox\FRBR勉強会\FRBR研究会\戦後教科書_LOD\ttlの元データ\issueチェック用 

にて、tsv-20200340.txt を置いておきました。参考まで。

**Comment by yegusa** [comment]
そうだった！じゃあ、

textbook-rc:recordID

の列を増やしてくれるのでもいいや。それでも十分助かります！

**Comment by masao** [comment]
そういう意味では、既に作ったスクリプトで十分かと。

以下のような形式のタブ区切りテキストです（抜粋）：

教育図書館メタデータID | 教育図書館OPACのURI | 教科書LODのURI | 教科書センター レコードID
--|--|--|--
EB10012620	|https://nieropac.nier.go.jp/ebopac/EB10012620	|https://w3id.org/jp-textbook/中学校/1992/保体/701	
EB10012535	|https://nieropac.nier.go.jp/ebopac/EB10012535	|https://w3id.org/jp-textbook/中学校/1992/保体/702	
EB10026175	|https://nieropac.nier.go.jp/ebopac/EB10026175	|https://w3id.org/jp-textbook/高等学校/2003/古典/025	|320030053
EB10026112	|https://nieropac.nier.go.jp/ebopac/EB10026112	|https://w3id.org/jp-textbook/高等学校/2003/商業/012	|320030313
EB10026111	|https://nieropac.nier.go.jp/ebopac/EB10026111	|https://w3id.org/jp-textbook/高等学校/2003/商業/013	|320030314, 320090003

**Comment by yegusa** [comment]
うん、それで良いです。
スクリプトってどこにあるの？
使い方は？

**Comment by yegusa** [comment]
あと、新しいURLは

https://nieropac.nier.go.jp/lib/database/TEXTBOOK/EB10026111/

って感じになります。
（リダイレクトされるけど）

**Comment by masao** [comment]
スクリプトのほうの使い方は以下のコマンド起動だけで最新の all-yyyymmdd.ttl を読み込んで出力します。

> ruby ttl2tsv.rb

もしくは、必要なら、ファイル名を指定して出力もできるはず。

> ruby ttl2tsv.rb textbook-20200302.ttl	textbook-rc-20180916.ttl	

のように。

**Comment by yegusa** [comment]
> https://nieropac.nier.go.jp/lib/database/TEXTBOOK/EB10026111/

これの件は、新しいissue立てます。

**Comment by yegusa** [comment]
```sh
$ ruby ttl2tsv.rb 
Traceback (most recent call last):
	4: from ttl2tsv.rb:3:in `<main>'
	3: from ttl2tsv.rb:3:in `require_relative'
	2: from /Volumes/Sensitive/github/jp-textbook.github.io/util.rb:4:in `<top (required)>'
	1: from /Users/yuka/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/yuka/.rbenv/versions/2.6.5/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rdf/turtle (LoadError)
```

やってみたけど、こんなエラーが出て、実行できない。

**Comment by masao** [comment]
最初に bundle update してから実行してください

**Comment by yegusa** [comment]
できました！
確認できたのでクローズします。
