### ISSUE TITLE
教科書LODのgit管理をmacでやる場合のHDD関係のTips

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#424]
教科書LODでは、ファイル名で、大文字・小文字を区別しないといけないため（大文字・小文字を区別しないと同じファイル扱いになってしまうものがある）、macのデフォルトのHDDのフォーマットのAPFSのママだとうまくいきません。

確か、仮想的に、同じHDD上に別のフォーマットのドライブを作ってうまくできるようにした記憶があるのですが、どうやったか思い出せません。

なので、現在、gitで編集作業ができない状態です。

やり方を一緒に思い出してもらえると助かります。

（次回も同様になったときのために、issueとして記録しておきます。）

**Comment by masao** [comment]
https://stackoverflow.com/a/49133889 このあたりでしょうか。仮想ディスクを case-sensitive 設定でつくって、そのマウント先に作業フォルダを展開する。

**Comment by yegusa** [comment]
こんな感じですな。

### ディスクユーティリティを立ち上げる

- Finder をアクティブにする
- 上部メニューの「移動」→「ユーティリティ」
- ディスクユーティリティ.app をダブルクリック

### ディスクユーティリティでやること

- 「ボリューム」のところの、HDDに+がついたアイコン をクリック
- APFSボリュームをコンテナに追加しますか？というポップアップが出る
- 「名前」(name)を「Sensitive」(なんでもいいわかりやすいのを)入力
- 「フォーマット」(Format)をAPFS（大文字/小文字を区別）（APFS (Case-Sensitive)）を選ぶ(図参照)
- 「追加」(Add)をクリック
- /Volumes/Sensitive というので参照できるようになる。
- あとはその下にgitでcloneしてきたものをおいて作業すると良い。

![スクリーンショット 2020-03-05 17 01 54](https://user-images.githubusercontent.com/1328499/75960500-7faff500-5f03-11ea-8184-09d5549955b3.png)

**Comment by yegusa** [comment]
できた気がするので、一旦、クローズします。
