### ISSUE TITLE
教育図書館OPACへのURLの変更

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#425]
#422 で思い出したのですが、

 2019-12の教育図書館のOPACシステムのリプレイスに伴い、
OPACへのリンクのURLが変わりました。
リダイレクトしているから、旧リンクでも行きますが、新しいのに変えたほうがいいかなと。

例： https://w3id.org/jp-textbook/中学校/1992/保体/701

旧： https://nieropac.nier.go.jp/ebopac/EB10012620
新： https://nieropac.nier.go.jp/lib/database/TEXTBOOK/EB10012620/

**Comment by masao** [comment]
修正しました。

**Comment by yegusa** [comment]
https://w3id.org/jp-textbook/中学校/1992/保体/701

で確認しました。
できていたので、クローズします。
