### ISSUE TITLE
更新履歴の更新方法を明記

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#427]
indexやaboutでの更新履歴は template/about.html.erb を修正して書き加えること。12.0のリリース時に間違って index.html を直接書き換えてしまったので、注意書きを書いておくこと。

**Comment by masao** [comment]
一応、該当箇所に以下のようなコメントを挿入し、編集すべきファイルを明示するようにしました。

```
 <!-- 更新履歴は template/about.html.erb を修正すること! -->
```

**Comment by yegusa** [comment]
about.html とindex.htmlを見ました

about.htmlにはありましたが、
index.html には見当たりませんでした。

**Comment by masao** [comment]
indexにも追記しました。

**Comment by yegusa** [comment]
index.htmlにもあることを確認しましたので、クローズします。
