### ISSUE TITLE
新規データに対応するNCID, JPNOの追加

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#429]
#423 で教科書センターデータに対応する ttl ファイルを再作成するので。

**Comment by masao** [comment]
追加しました。

**Comment by masao** [comment]
追加されたIDの件数は以下の通り:

* NCID: 168件
* JPNO: 1329件
* NDL-BibID: 1322件

**Comment by yegusa** [comment]
了解です。
https://github.com/jp-textbook/jp-textbook.github.io/commit/4834069dfa7ec558d99f214b1f2cb05312533f32#diff-43b42b567d299e54b814c395ba630bbe

これよね。
どう、確かめたらいいかわからんし、いいと思います。
クローズします。
