### ISSUE TITLE
(poorman系)日付データに xsd:date 型を付ける

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#432]
#431 からの派生。

今のところ SHACL 上は以下の5つが指定されている:

クラス | プロパティ | 値の例
--|--|--
Publisher | textbook:catalogueYear | 2008
Catalogue | schema:datePublished | 2006
CurriculumGuideline | schema:startDate | 2022-04-01
CurriculumGuideline | schema:datePublished | 1998-12-14
CurriculumGuideline(ブランクノード)| schema:datePublished | 1989-03-15

（修正：４つじゃなくて、5つですね。ブランクノードの分が追加）

**Comment by yegusa** [comment]
```ttl
  textbook:catalogueYear "2018"^^xsd:date;
```

こんな感じで書けばいいですか？

**Comment by masao** [comment]
はい、その形式でお願いします。

**Comment by yegusa** [comment]
作成しました。

13.1系フォルダに入れておきました。

catalogue-20200308.ttl
curriculum-20200308.ttl
curriculum-version-20200308.ttl
publisher-20200308.ttl

**Comment by masao** [comment]
確認しました。一点だけ。ついでながら、 usageYear が数値型になっているので、文字列型にしたほうがよさそうです。

現状:
```
  textbook:usageYear 1992;
```

修正後:
```
  textbook:usageYear "1992";
```

**Comment by yegusa** [comment]
上記、usageYearも修正しておきました。

catalogue20200308-2.ttl として置いています。

**Comment by masao** [comment]
あと、Turtleの @prefix を追加しないとダメそうです（以下の1行）。

```turtle
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
```

**Comment by yegusa** [comment]
追加しました。

以下のファイルにしています。
catalogue-20200308-3.ttl
curriculum-20200308-2.ttl
curriculum-version-20200308-2.ttl
publisher-20200308-2.ttl

**Comment by masao** [comment]
確認しました。クローズします。
