### ISSUE TITLE
(ruby系) 日付データに xsd:date 型を付ける

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#433]
#431 #432 から派生

1箇所だけです。
使用年は、文字列型のままです。

開発? | リソース | プロパティ | ラベル | 例 | どうするか
-- | -- | -- | -- | -- | --
開発 | 教科書リソース | textbook:authorizedYear | 検定年 | 2001 | 日付型にする
なし | 教科書リソース | textbook:usageYear | 使用年 | 2005-2005 | 文字列型のまま

**Comment by masao** [comment]
一通り修正しました。

**Comment by yegusa** [comment]
all-20200308.ttl で

```ttl
  textbook:authorizedYear "1992"^^xsd:date;
```

というようになっていたのを確認しましたので、クローズします。
