### ISSUE TITLE
aboutに記入：高校の専門の「種目」を書名から類推して入力

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#434]
#390 からの派生です。

高校の専門の「種目」を書名から類推して入力してはどうか？ #390

が実現されたので、ドキュメントとして、その旨をaboutでわかるようにしといたほうが良いかと。

**Comment by yegusa** [comment]
shape-20200308.ttlの576行目あたりの

```ttl
          sh:description "<code>textbook:curriculum/<var>学校種別</var>/<var>学習指導要領施行年</var>/<var>教科</var>/<var>科目</var></code>として示される種目（科目）リソースと関連付ける。"@ja;
```

textbook:subjectTypeがSpecialの場合、少数の例外を除いて、プログラムによって書名から種目名の最長一致で、種目を類推して追加したものであり、教育図書館が追加したデータではないことに注意。最長一致で解決できない例外については、江草・高久によって追加。


Note that if the textbook:subjectType is Special, with a few exceptions, the longest match of the Subject name from the title of the textbook will be added by analogy to the Subject, not the data added by the Library of Education. Exceptions that cannot be resolved by the longest match are added by Egusa and Takaku

こんな感じでどうでしょうか？

**Comment by masao** [comment]
表現をすこし調整しましたが、確認したのでクローズします。
