### ISSUE TITLE
ISBNチェックをする

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#436]
#435 に関連

簡易的に、ISBNをチェックするために、
ハイフンを抜いた桁数を確認してみたら、10,13桁以外の桁数のものが8件ほどありました。

ついでにチェックデジットも使ってチェックをして、不正な値があれば、修正の依頼を出すと良いかなと思いました。

rubyでチェックするスクリプトを書いてもらえると助かります。

**Comment by masao** [comment]
https://honno.info/vslip/multi.html このあたりのツールでよいのではないかと。。。

**Comment by yegusa** [comment]
たくさんできないからさあ。全部チェックして欲しいのよ。

**Comment by masao** [comment]
https://isbn-bulk-checker.herokuapp.com/ ここにおきました。

**Comment by yegusa** [comment]
ありがとうございます！いい感じです。
クローズします。
