### ISSUE TITLE
ISBNのあるものについて教科書センターのレコードIDと請求記号とISBNを入れる

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#442]
ISBNのあるものについて教科書センターのレコードIDと請求記号とISBNを入れる

新しいフォーマットになったので。

**Comment by yegusa** [comment]
#435 に関連

**Comment by yegusa** [comment]
#435 の時に、入手したデータは、**過去分のISBNが入った教科書全てのレコード分**がある。
また、

- ISBN
- 教科書センターのレコードID
- 教科書センターの請求記号

があるので、
これらを反映する作業。

前回、教科書センターからいただいたデータとフォーマットが違うので、プログラムの再開発が必要と思われる。

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
いくつか確認しました。できていると思うので、クローズします。
