### ISSUE TITLE
データセットがGithubに置いてあるという情報を記録したい

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#449]
C4Ljp 2020での大向コメントより。

**Comment by masao** [comment]
Data Catalog Vocabulary https://www.w3.org/TR/vocab-dcat/ でデータセットのメタデータを構造化して記述する方向で。

**Comment by masao** [comment]
DCATによるデータセットのモデル化例：
![image](https://user-images.githubusercontent.com/38825/86514120-c1699180-be4a-11ea-9400-210b231ab871.png)

**Comment by masao** [comment]
さらに拡張して、複数のバージョンと複数のデータファイルの関係を dct:hasVersion, dct:hasPart などで表現するようにしたモデルです：

### バージョン関係

* Dataset -- dct:hasVersion --> Dataset (v15.0)
* Dataset -- dct:hasVersion --> Dataset (v14.0)

### 配布ファイル

* Dataset (v15.0) -- dcat:distribution --> Distribution (all)
  * Distribution (all) -- dct:hasPart --> Distribution (textbook)
  * Distribution (all) -- dct:hasPart --> Distribution (textbook-rc)
  * Distribution (all) -- dct:hasPart --> Distribution (curriculum)
  * ...


![image](https://user-images.githubusercontent.com/38825/86527633-f671f480-bedb-11ea-8613-9b83f0d7d573.png)

**Comment by masao** [comment]
データカタログの記述であるDCAT語彙よりも、RDFデータセットの記述用語彙VoIDとバージョニング語彙PAVを使うように修正して、バージョンごとの表現力をあげたうえで、シンプルに書けるようにしてみた。ひとまず、これで書いてみることにする。
* https://www.w3.org/TR/void/ 
* https://pav-ontology.github.io/pav/

![image](https://user-images.githubusercontent.com/38825/86608528-a4b59100-bfe5-11ea-8b1c-b989a4231b1f.png)

**Comment by masao** [comment]
データセットに関するメタデータ記述を https://jp-textbook.github.io/dataset-20200712.ttl として追加しました。

**Comment by yegusa** [comment]
すごい！良さそうに思います！

クローズします。
