### ISSUE TITLE
教科書の使用年をリピータブルなデータとして作成する

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#451]
SPARQLでクエリーを書いた時など、何年に使用された教科書って探せるようにしたい

**Comment by yegusa** [comment]
こんな感じで変更はどうでしょうか？

現在：

プロパティ名 | 説明 | プロパティ値の例 | 必須・省略の別繰り返しの有無 | 備考
-- | -- | -- | -- | --
textbook:usageYear | 使用年 | 2005-2005 | 必須繰り返し無し | "yyyy-yyyy" もしくは "yyyy-" となる。"yyyy-" の場合は、終了年が未定のことを示す。

案：

プロパティ名 | 説明 | プロパティ値の例 | 必須・省略の別繰り返しの有無 |備考
-- | -- | -- | -- | --
textbook:usageYear | 使用年 | 2005 | 必須繰り返し有り | "yyyy"　複数年ある場合は、繰り返す。
textbook:usageYearRange | 使用年の区間 | 2005-2005 | 必須繰り返し無し | "yyyy-yyyy" もしくは "yyyy-" となる。"yyyy-" の場合は、終了年が未定のことを示す。

**Comment by masao** [comment]
修正しました。

**Comment by yegusa** [comment]
確かめました。いいと思います！

```ttl
  <https://w3id.org/jp-textbook/usageYear> "2011"^^<http://www.w3.org/2001/XMLSchema#date>, "2012"^^<http://www.w3.org/2001/XMLSchema#date>, "2013"^^<http://www.w3.org/2001/XMLSchema#date>, "2014"^^<http://www.w3.org/2001/XMLSchema#date>;
  <https://w3id.org/jp-textbook/usageYearRange> "2011-2014" .
```

**Comment by yegusa** [comment]
クローズします。
