### ISSUE TITLE
ドキュメントの更新：教科書の使用年をリピータブルに

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#452]
#451 のSHACLの更新、aboutの更新

**Comment by masao** [comment]
更新しました。

**Comment by yegusa** [comment]
取り急ぎ、図を作っておきました。

日本語

![ja](https://user-images.githubusercontent.com/1328499/86339616-c41f8780-bc8e-11ea-9bce-600322e4eadf.png)

英語

![en](https://user-images.githubusercontent.com/1328499/86339625-caadff00-bc8e-11ea-9350-b70bd9ac1982.png)

**Comment by masao** [comment]
修正を反映させました。

**Comment by yegusa** [comment]
良いと思います。クローズします。
