### ISSUE TITLE
about の独自語彙のスキーマのリストに、usageYearRangeがない

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#454]
#453 を確認した時に気づきました。

about の独自語彙のスキーマのリストに、usageYearRangeがないです。

これも、自動生成するようになっていると取りこぼしがなくなるのでいいですね。

**Comment by masao** [comment]
独自語彙を追加した際に自動的に表示するようにしました。

**Comment by yegusa** [comment]
いい感じです！確認しましたのでクローズします。
