### ISSUE TITLE
法人インフォのリンク先変更への対応

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#457]
https://info.gbiz.go.jp/

**Comment by masao** [comment]
URIの形式は以下: https://info.gbiz.go.jp/hojin/ichiran?hojinBango=7010001020270

Excelから作り直すこと。

**Comment by yegusa** [comment]
修正前： https://hojin-info.go.jp/hojin/ichiran?hojinBango=7010001020270
修正後： https://info.gbiz.go.jp/hojin/ichiran?hojinBango=7010001020270

つまり、hojin-info.go.jp　を  info.gbiz.go.jp に変える感じね。

こんな感じで直書きしてるから、

```ttl
rdfs:seeAlso <https://hojin-info.go.jp/hojin/ichiran?hojinBango=9011501016310>;
```

Excelのほうを変えないとですね。

頻繁にかわるようなら、
dcterms:identifier とかつかって、法人番号だけttlに出すようにして、
HTMLのときにりんくにするほうがいいのかなあ。

**Comment by yegusa** [comment]
5.2系フォルダにデータを作っておきました。

**Comment by masao** [comment]
修正を反映させました。

**Comment by yegusa** [comment]
何個かの教科書の出版社のページを確認しました。

修正されていると思いますので、クローズします。
