### ISSUE TITLE
著者名がエスケープ表記されてしまうものあり

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#46]
- [x] 教育図書館に連絡(2017-05-03)
- [x] 元データ入手（2017-06-01)

「有馬◆UF929◆人 」のように、外字表記のようにExcel上で記述されてしまっているものあり。
教育図書館のシステム上では表記できているため、一括出力時の問題と思われる。要確認。
![image](https://cloud.githubusercontent.com/assets/38825/25646924/2c03628a-2ff8-11e7-9c66-9edd51ca0b1a.png)
https://nieropac.nier.go.jp/ebopac/EB16209195

**Comment by yegusa** [comment]
教育図書館からいただいた「2017-04-27版のデータ」で初出の現象のようですね。
（「2016-07-06版のデータ」では普通に字が表示されています。）

以下のレコードがそのような状況のようです。

EB16209195	有馬◆UF929◆人 ほか42名
EB16209196	有馬◆UF929◆人 ほか42名
EB16209197	有馬◆UF929◆人 ほか42名
EB16209198	有馬◆UF929◆人 ほか42名
EB16209199	有馬◆UF929◆人 ほか42名
EB16209200	有馬◆UF929◆人 ほか42名
EB16209201	有馬◆UF929◆人 ほか42名
EB16209357	有馬◆UF929◆人 ほか56名
EB16209358	有馬◆UF929◆人 ほか56名
EB16209359	有馬◆UF929◆人 ほか56名
EB16240885	磯◆UFA11◆行雄 江里口良治 ほか9名

**Comment by yegusa** [comment]
2017-05-24版でも修正されていなかったので、再度、教育図書館に連絡済み。

**Comment by masao** [comment]
元データが修正されない場合に備えて、変換スクリプト側でUnicodeコードでエスケープを戻すような処理を加えるようにしました。

**Comment by yegusa** [comment]
2017-06-01入手のデータで問題ないこと確認済み。

**Comment by yegusa** [comment]
サイトでも問題ないことを確認したのでクローズする

書誌ID	修正事項	https://w3id.org/jp-textbook/学校種別/検定年/教科書記号/教科書番号
EB16209195	有馬◆UF929◆人 ほか42名	https://w3id.org/jp-textbook/小学校/2010/理科/302
EB16209196	有馬◆UF929◆人 ほか42名	https://w3id.org/jp-textbook/小学校/2010/理科/402
EB16209197	有馬◆UF929◆人 ほか42名	https://w3id.org/jp-textbook/小学校/2010/理科/403
EB16209198	有馬◆UF929◆人 ほか42名	https://w3id.org/jp-textbook/小学校/2010/理科/502
EB16209199	有馬◆UF929◆人 ほか42名	https://w3id.org/jp-textbook/小学校/2010/理科/503
EB16209200	有馬◆UF929◆人 ほか42名	https://w3id.org/jp-textbook/小学校/2010/理科/602
EB16209201	有馬◆UF929◆人 ほか42名	https://w3id.org/jp-textbook/小学校/2010/理科/603
EB16209357	有馬◆UF929◆人 ほか56名	https://w3id.org/jp-textbook/中学校/2011/理科/722
EB16209358	有馬◆UF929◆人 ほか56名	https://w3id.org/jp-textbook/中学校/2011/理科/822
EB16209359	有馬◆UF929◆人 ほか56名	https://w3id.org/jp-textbook/中学校/2011/理科/922
EB16240885	磯◆UFA11◆行雄 江里口良治 ほか9名	https://w3id.org/jp-textbook/高等学校/2013/地学/301
