### ISSUE TITLE
教科リソースの作成 subjectArea-*.ttl (2020年度～2022年　小学校・中学・高校の使用教科書分)

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#461]
新しい学習指導要領の教科リソースの作成 subjectArea-*.ttl

- 2020年度　小学校
- 2021年度　中学校
- 2022年度　高等学校

量もすくないので、以下、一度にやる。

 （まとめ #460 ）

**Comment by yegusa** [comment]
つくりました。

subject-20201030.ttl として　16.0系フォルダにいれています

**Comment by masao** [comment]
追加しました。
例：
https://w3id.org/jp-textbook/curriculum/小学校/2020/道徳
https://w3id.org/jp-textbook/curriculum/中学校/2021/理科
https://w3id.org/jp-textbook/curriculum/高等学校/2022/公民

**Comment by yegusa** [comment]
確認しました。クローズします。
