### ISSUE TITLE
教科書目録リソースの作成 catalogue-*.ttl (2020年度　小学校・中学・高校の使用教科書分)

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#463]
新しい学習指導要領対応の種目リソースの作成 catalogue-*.ttl

2020年度　小学校
2020年度　中学校
2020年度　高等学校

一度に3学校種別分やる。

（まとめ #460 ）

**Comment by yegusa** [comment]
作成しました。

16.0系フォルダにいれてあります。

**Comment by masao** [comment]
ファイル内容が subject 相当のものになってしまっているようです。ご確認ください。

**Comment by yegusa** [comment]
ありゃ、失礼しました。直しておきました。

**Comment by masao** [comment]
追加しました：
https://w3id.org/jp-textbook/catalogue/高等学校/2019
https://w3id.org/jp-textbook/catalogue/中学校/2019
https://w3id.org/jp-textbook/catalogue/小学校/2019

**Comment by yegusa** [comment]
確認しました。クローズします。
