### ISSUE TITLE
新指導要領における種目「保健体育」が存在しない

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#466]
#462 からの派生。
新指導要領における種目「保健体育」が存在しないようです。科目「保健体育」は定義されているので、subject-20201031.ttl の問題のようです。

**Comment by yegusa** [comment]
小学校のことかな？

以下の理由により、修正の必要はないと思うのですが。。。

参考までに、関連する、学校種別と教科と科目の組み合わせとしては、以下のような感じ。

### 教科書受理種目表
https://www.mext.go.jp/a_menu/shotou/kyoukasho/kentei/1411318.htm

学校 | 教科 | 種目
-- | -- | --
小学校 | 体育 | 保健
中学校 | 保健体育 | 保健体育
高等学校 | 保健体育 | 保健体育

なので、以下のリソースがあればいいはず：

- subjectArea
-- https://w3id.org/jp-textbook/curriculum/小学校/2020/体育
-- https://w3id.org/jp-textbook/curriculum/中学校/2021/保健体育
-- https://w3id.org/jp-textbook/curriculum/高等学校/2022/保健体育

- subject
-- https://w3id.org/jp-textbook/curriculum/小学校/2020/体育/保健
-- https://w3id.org/jp-textbook/curriculum/中学校/2021/保健体育/保健体育
-- https://w3id.org/jp-textbook/curriculum/高等学校/2022/保健体育/保健体育

で、作ったデータには、ありますよね？

ちなみに、学習指導要領では、以下のような感じ。

### 学習指導要領
https://www.mext.go.jp/a_menu/shotou/new-cs/1384661.htm

学校 | 教科 | 科目
-- | -- | --
小学校 | 体育 | （小学校は科目はない）
中学校 | 保健体育 | （中学校は科目はない　体育分野、保険分野があるよう）
高等学校 | 保健体育 （共通科目）| 体育
高等学校 | 保健体育 （共通科目）| 保健
高等学校 |体育（専門科目）|  スポーツ概論，スポーツⅠ，...などいくつかあり

保健体育は、教科・科目と微妙に違うのでややこしいのですよねえ。

**Comment by masao** [comment]
おっと、見間違えていたようです。いったんクローズします。
