### ISSUE TITLE
[新指導要領] subjectType-xxxxxxxx.ttl 教科・種目種別をあらわすリソースが必要

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#467]
subjectType-xxxxxxxx.ttl にて <https://w3id.org/jp-textbook/curriculum/高等学校/2022/Common> などのリソースが必要になりそうです。

**Comment by yegusa** [comment]
#259 で作成したやつですね。了解です。

**Comment by yegusa** [comment]
16.0系フォルダに作っておきました。

**Comment by masao** [comment]
学校種別と指導要領のプロパティが無くなっているようです。。。

```turtle
-  textbook:school <https://w3id.org/jp-textbook/school/高等学校>;
-  textbook:curriculum <https://w3id.org/jp-textbook/curriculum/高等学校/1994>;
```

**Comment by yegusa** [comment]
ありゃ、最新じゃない元ファイルから作成してしまっていました。

作成しなおしましたので、再度チェックよろしく。

**Comment by masao** [comment]
追加しました：
https://w3id.org/jp-textbook/curriculum/高等学校/2022/Common
https://w3id.org/jp-textbook/curriculum/高等学校/2022/Special

**Comment by yegusa** [comment]
確認しました。クローズします。
