### ISSUE TITLE
教育図書館へのレコードIDを使ったリンク修正

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#469]
#425 の派生。
教育図書館蔵書へのリンクURLが、教科書とそれ以外とで異なる気がします。

特に、教科書目録と指導要領の所蔵リンクで使っている形式を検討する必要があります：

たとえば教科書目録情報：
https://w3id.org/jp-textbook/catalogue/小学校/2018 内の教育図書館へのリンク：
https://nieropac.nier.go.jp/lib/database/TEXTBOOK/BB00014905/ （リンク切れ…）
おそらく、こちらが正しい： https://nieropac.nier.go.jp/opac/opac_link/bibid/BB00014905

**Comment by yegusa** [comment]
おおう。確かにそうです。

**Comment by masao** [comment]
一応、学習指導要領と教科書目録は修正しました。

**Comment by yegusa** [comment]
リンク切れなくつながっていることを確認しましたのでクローズします。
