### ISSUE TITLE
年データの型指定を変更

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#474]
現在、使用年や検定年など、「年」をxsd:date （日付型）にて表現しているが、これは適切ではなく、gYear（グレゴリアン年型）に変更したほうがよいかも。

#473 からの派生。

**Comment by yegusa** [comment]
はい、いいと思います。しゃーないね。

**Comment by masao** [comment]
一通り修正しました。

**Comment by yegusa** [comment]
サブissueがクローズされたし、クローズしますね。
