### ISSUE TITLE
教科書目録リソースの「使用年度」に型がない

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#477]
#475 できづいたのですが、

  textbook:usageYear "1992";

これですが、型がないのですが、

  textbook:usageYear "1992";^^xsd:gYear;

ってかんじにすべき？

正確には、「掲載している教科書の使用年度を表す。」と年度なのですが、、、
バリデートするという用途では、xsd:gYearでもいいのかなあと。

参考：現在の、教科書目録リソースの例

<https://w3id.org/jp-textbook/catalogue/小学校/1991> a <https://w3id.org/jp-textbook/Catalogue>;
  schema:datePublished "1991"^^xsd:gYear;
  textbook:school <https://w3id.org/jp-textbook/school/小学校>;
  textbook:usageYear "1992";
  schema:name "小学校用教科書目録(平成4年度使用)"@ja;
  schema:name "しょうがっこうようきょうかしょもくろく（へいせい4ねんどしよう）"@ja-Hira;
  schema:name "Textbook Catalogue for Elementary School of 1992 School Year"@en;
  rdfs:seeAlso <http://id.ndl.go.jp/jpno/00051356>;
  rdfs:seeAlso <https://ci.nii.ac.jp/ncid/AN10586997>;
  nier:itemID "971429616";
  nier:callNumber "375.9||27||'92";
  nier:recordID "BB00014905".

**Comment by yegusa** [comment]
本当は、年度をあらわす型？があるといいんですけどねえ。なんか、いいのないのかな。

**Comment by masao** [comment]
とりあえず ^^xsd:gYear を付ける方向でよいのではないでしょうか。

**Comment by yegusa** [comment]
いいと思います！

**Comment by masao** [comment]
お手数ですが、最新の教科書目録リソースの型修正版を作ってもらえますか。

**Comment by yegusa** [comment]
作っておきました。 catalogue-20201215.ttlです

**Comment by masao** [comment]
更新しました。

**Comment by yegusa** [comment]
確認しました。クローズします。
