### ISSUE TITLE
使用年の区間を形式化して検証可能にする

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#478]
textbook:usageYearRangeは現状、ただの文字列だけど、基本的には以下のいずれかのパターンしかとらないので、検証できるようにしてしまう。
* \d\d\d\d
* \d\d\d\d-
* \d\d\d\d-\d\d\d\d

**Comment by masao** [comment]
追加しました。複数の出版社にわかれるケースがあったので、結局以下のような正規表現で表現することにしました：

```
/^(\\d\\d\\d\\d|\\d\\d\\d\\d-(\\d\\d\\d\\d)?)(, (\\d\\d\\d\\d|\\d\\d\\d\\d-(\\d\\d\\d\\d)?))*$/
```

**Comment by yegusa** [comment]
どうチェックすればええかわからんけど、よさそうです。クローズします。
