### ISSUE TITLE
学年記載ミス

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#48]
- [x] 教育図書館に連絡（2017-05-03に連絡済み）(2017-05-26 再度連絡）
- [x] 教育図書館データ修正(1度目確認：2017-05-08)　（残：EB16219851　2017-05-26)
- [x] 元データ入手　(2017-06-01)

「小学 こくご 4下」の書名なので、4年生向けと思われるが、書誌情報には1年との記載。
https://nieropac.nier.go.jp/ebopac/EB16219847 
データ誤りを確認すること。

**Comment by masao** [comment]
同様に、以下も誤りと思われる：

* https://nieropac.nier.go.jp/ebopac/EB16219842
* https://nieropac.nier.go.jp/ebopac/EB16219843
* https://nieropac.nier.go.jp/ebopac/EB16219844
* https://nieropac.nier.go.jp/ebopac/EB16219845
* https://nieropac.nier.go.jp/ebopac/EB16219846
* https://nieropac.nier.go.jp/ebopac/EB16219847
* https://nieropac.nier.go.jp/ebopac/EB16219848
* https://nieropac.nier.go.jp/ebopac/EB16219849
* https://nieropac.nier.go.jp/ebopac/EB16219850
* https://nieropac.nier.go.jp/ebopac/EB16219851

**Comment by masao** [comment]
20170524版データにて、以下の誤りがまだ残存（これ1件のみになったと思われる）：

* WARN: https://w3id.org/jp-textbook/小学校/2004/国語/616 duplicates! [EB10010098/EB16219851] (2005-2010 vs 2009-2010)
  schema:publisher: 大阪書籍 vs 日本文教出版
  schema:name: 小学校 国語 6下 vs 小学 こくご 6下
  textbook:grade: 6 vs 1

**Comment by yegusa** [comment]
https://nieropac.nier.go.jp/ebopac/EB16219851

のほうの学年が間違いですね。

教育図書館に再度連絡しておきました。

**Comment by yegusa** [comment]
https://nieropac.nier.go.jp/ebopac/EB16219851

修正されました、修正確認しました。

**Comment by yegusa** [comment]
2017-06-01入手のデータで問題ないこと確認済み。

**Comment by yegusa** [comment]
サイトでも問題ないことを確認したのでクローズする

書誌ID	修正事項	https://w3id.org/jp-textbook/学校種別/検定年/教科書記号/教科書番号
EB16219847	学年ミス	https://w3id.org/jp-textbook/小学校/2004/国語/416
EB16219842	学年ミス	https://w3id.org/jp-textbook/小学校/2004/国語/215
EB16219843	学年ミス	https://w3id.org/jp-textbook/小学校/2004/国語/216
EB16219844	学年ミス	https://w3id.org/jp-textbook/小学校/2004/国語/315
EB16219845	学年ミス	https://w3id.org/jp-textbook/小学校/2004/国語/316
EB16219846	学年ミス	https://w3id.org/jp-textbook/小学校/2004/国語/415
EB16219847	学年ミス	https://w3id.org/jp-textbook/小学校/2004/国語/416
EB16219848	学年ミス	https://w3id.org/jp-textbook/小学校/2004/国語/515
EB16219849	学年ミス	https://w3id.org/jp-textbook/小学校/2004/国語/516
EB16219850	学年ミス	https://w3id.org/jp-textbook/小学校/2004/国語/615
EB16219851	学年ミス	https://w3id.org/jp-textbook/小学校/2004/国語/616
