### ISSUE TITLE
publisher-*.ttl への出版者リソース追加 (2020)

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#486]
新しい教科書の中学校だけでよいので、作る。

**Comment by yegusa** [comment]
やはり、小学校、中学校、高等学校の分、つくりました。

18.0 系にデータ置いています。

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
https://w3id.org/jp-textbook/publisher/2020/東書

無事、↑ができているみたいなので、クローズします。
