### ISSUE TITLE
教科書記号の空白

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#488]
#483 に派生。
一部の教科書記号において、全角空白がはいっているところあり。
<https://w3id.org/jp-textbook/中学校/2020/国語　/701> など。

面倒なので、空白は機械的に除去するような仕組みを作って対応する。

**Comment by masao** [comment]
対応しました。

**Comment by yegusa** [comment]
以下のですね。全角空白がはいってるんですね。

EB20080688
EB20080689
EB20080690
EB20080691
EB20080692
EB20080693
EB20080694
EB20080695
EB20080696
EB20080697
EB20080698
EB20080699

**Comment by yegusa** [comment]
一応、教育図書館には、その書誌IDを知らせておきました。

**Comment by yegusa** [comment]
教育図書館のデータのほうは、直したそうです！データはもらわなくていいよね。

**Comment by yegusa** [comment]
https://w3id.org/jp-textbook/中学校/2020/国語/701

無事、↑のリンク先ができていて、参照できたので、クローズします。
