### ISSUE TITLE
教科書図書館OPACへのリンク修正

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#489]
OPACシステムの変更があったのか、フォーム/JavaScriptを通じたリンクが効かなくなっているので、修正対応すること。

ex. https://w3id.org/jp-textbook/小学校/2010/家庭/501

**Comment by masao** [comment]
修正して https でリンクできるようにしました。

**Comment by yegusa** [comment]
無事、リンク先に行けたのでクローズします。
