### ISSUE TITLE
単元LOD関連のURIに使うIDについて

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#492]
記録のため、issueとして挙げておく

本プロジェクトで独自のIDを連番でふり、このIDをメンテナンスすることにした。

- 単元リソースID：AA + 12桁の数字（最初を1に）(例：AA100000000001）
- 発展内容リソースID：AB  + 12桁の数字（最初を1に）(例：AB100000000001）
- 編修趣意書リソースID：AC+ 12桁の数字（最初を1に）(例：AC100000000001）
- URIはhttps://w3id.org/jp-textbook/ID とする。
- URI例：https://w3id.org/jp-textbook/AA100000000001
- IDは新規作成ごとに連番で作成する（注：一見、ID連番の順とソート順序が連動しているようにもみえるが、新規作成の都合上そうなっているだけなので、順序は「order」属性を使うこと！）
- 削除レコードのIDは再利用しない

とすることにした。

主な理由：

- 教科書LODのように、なにかをくみあわせてよいID/URIになるものがない
- 日本語を使ったURIじゃないほうが望ましい
- 意味のあるURIじゃないほうが望ましい
-  / がたくさんあるURIじゃないほうが望ましい（？）
- 連番IDだとソートに使えそうなどと勘違いしてしまって紛らわしいので、ランダムや、歯抜けIDも検討したが、IDメンテナンスが大変そうなのでやめた
- 12桁にしたのはなんとなくそんなもん的な、深い意味はない。

今後のメンテナンスの方針：
- IDをソートして、最後のIDを新規IDにすること（ID予約して空行を用意しておけばいいかな？やりかたは要検討）
- なので、素敵な並び順とIDの順のあいだに、でかめのID（新規IDのレコード）がはいることがまれにあるのので気を付けること。
- 削除IDに気を付けること
- ソート用のorder 属性を付けて、こちらをソートに使う用にする、ドキュメントにも書いておく

**Comment by yegusa** [comment]
これ、いいよね。一応確認して、クローズよろ。 → @masao

**Comment by masao** [comment]
Ok.
クローズします。
