### ISSUE TITLE
schema-yyyymmdd.ttl は直接作成している？

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#493]
おしえてください。

単元LODの関係で、あたらしい独自クラスとプロパティをつくるので、
schema-yyyymmdd.ttl を更新するのだとおもうのだけど、
これって、Excel -> TTL （Poorman’s Linked Data Toolkit ）じゃなくて、
直接、TTLを書いてるのかな？
それなら、それでもいいのだけど。

**Comment by masao** [comment]
これまでのところ、手で書いています。

**Comment by yegusa** [comment]
だよね。了解
