### ISSUE TITLE
URIの書式を書く場所をおしえて

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#494]
HTMLに直書きしてるっていってたきがするけど、どこを編集してるのだっけ？

教科書をあらわすリソースは以下のようなURIにより表現されます。
https://w3id.org/jp-textbook/学校種別/検定年/教科書記号/教科書番号

↑のようなやつ。

**Comment by masao** [comment]
#520 でOkかと。

**Comment by yegusa** [comment]
ですね。クローズします。
