### ISSUE TITLE
教科書番号の誤り 小学校/2019/国語/508 → 607

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#506]
https://w3id.org/jp-textbook/小学校/2019/国語/508 は光村出版の小学校国語6年生向け教科書だけど、これは教科書目録によれば、教科書番号は 607 のはずなので、元の書誌情報における番号のつけ間違いと思われる。

**Comment by yegusa** [comment]
教育図書館に連絡しておきました。

**Comment by yegusa** [comment]
https://nierlib.nier.go.jp/lib/database/TEXTBOOK/EB20080350/

教育図書館の本体システムのデータ607に修正されました。
軽微な修正なので、データもらいなおしてないです。

かわりに、手元のデータも直した、以下のファイルを作っておきました。

20220621_TEXTBOOK_all_issue506修正後.txt

**Comment by yegusa** [comment]
19.0系フォルダにExcelファイルを作っておいておきましたのでよろしく。

**Comment by yegusa** [comment]
あれ？直ってない。20220621_TEXTBOOK_all_issue506修正後.xlsx このファイルをつかってください。

**Comment by masao** [comment]
#523 の修正にあわせて修正されました

**Comment by yegusa** [comment]
確認しました。
