### ISSUE TITLE
教科の年ミス: curriculum/小学校/2019/算数

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#507]
textbook:AC100000000090 において教科として https://w3id.org/jp-textbook/curriculum/小学校/2019/算数 が指定されているが、これは年が違っており、``2020`` を使うべき。

**Comment by masao** [comment]
種目 subject も同様と思われる。

**Comment by yegusa** [comment]
AA-body, AB,AC のttlを修正しておきました。

**Comment by masao** [comment]
修正を確認したのでクローズします
