### ISSUE TITLE
教科書へのリンクがおかしな単元

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#508]
textbook:AC100000000217 における教科書指定が https://w3id.org/jp-textbook/小学校/2019// を指しており、なんらかの理由で値が抜けている模様。

**Comment by yegusa** [comment]
存在しない2番目の教科書があることになっていました。
修正しました。ttlも作り直しました。

**Comment by masao** [comment]
修正を確認したのでクローズします
