### ISSUE TITLE
単元LODのURI実装

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#513]
https://w3id.org/jp-textbook/AA100000000589 のような14桁のIDを使って単元URIを構成している。

通常のディレクトリに展開すると、1ディレクトリで格納できる限界を超えていく可能性があるため、学習指導要領LODで実施したようなマッピングを行う：

/AA100000000589 → /AA/100000000/589 となるように、頭2桁 + 中間9桁 + 末尾3桁の構成とすることが第一候補。

**Comment by yegusa** [comment]
いいと思いまーす。やってみましょう！

**Comment by masao** [comment]
https://github.com/perma-id/w3id.org/pull/2879 がマージされて設定完了。

**Comment by yegusa** [comment]
できたね！クローズします。
