### ISSUE TITLE
スペルミス: pagenation

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#514]
schema.org/pagenation は https://schema.org/pagination のスペル間違い

**Comment by yegusa** [comment]
直しました。

compilingProspectus-20220814_1.ttl
teachingUnit-AA-body-20220814_1.ttl
teachingUnit-AB-20220814_1.ttl

**Comment by masao** [comment]
Shapeの以下のプロパティにも残っているようなので、修正必要：

* <https://w3id.org/jp-textbook/ChapterCPShape>
* <https://w3id.org/jp-textbook/ChapterLUShape>

**Comment by yegusa** [comment]
Shapeは盲点だったー。直しました。

**Comment by masao** [comment]
修正を確認したのでクローズします
