### ISSUE TITLE
ブランクノードのクラス指定

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#516]
以下の2つのリソースがクラス指定を行っていないブランクノードとなっているため、できれば Class を追加しておきたい：
ShapeとSchemaにも追加が必要。

- https://w3id.org/jp-textbook/CurriculumGuidelineVersion （学習指導要領の改訂版の情報）
- https://w3id.org/jp-textbook/SourceOfEnglishName （英語名称表記の出典情報）

**Comment by yegusa** [comment]
### a)  教科と種目のttlにクラス指定をいれる

- subjectArea-yyyymmdd.ttl
- subject-yyyymmdd.ttl

に対して、以下のような感じで、「a の行を追加」する。

```ttl
  textbook:sourceOfEnglishName [
    a <https://w3id.org/jp-textbook/SourceOfEnglishName>;
    schema:name "小学校学習指導要領英訳版（仮訳）(平成20年3月)"@ja;
    schema:name "Elementary School Curriculum Guideline English Version (Tentative Translation) (2008-03)"@en;
    textbook:curriculum <https://w3id.org/jp-textbook/curriculum/小学校/2011>;
    rdfs:seeAlso <http://www.mext.go.jp/a_menu/shotou/new-cs/youryou/eiyaku/1261037.htm>;
  ];

```

これ、やりました。

**Comment by yegusa** [comment]
### b) Schema に追加
schema-yyyymmdd.ttl 

に、以下の行を追加

```ttl
textbook:CurriculumGuidelineVersion a rdfs:Class;
        rdfs:label "学習指導要領の改訂版"@ja, "Curriculum Guideline Version"@en;
        rdfs:comment "学習指導要領の改訂版の情報を表現するクラス。"@ja.

textbook:SourceOfEnglishName a rdfs:Class;
        rdfs:label "英語名称表記の出典情報"@ja, "Source Of English Name"@en;
        rdfs:comment "英語名称表記の出典情報を表現するクラス。"@ja.
```

これやりました。

**Comment by yegusa** [comment]
### c) Shape を更新

shapes-yyyymmdd.xlsx を更新

- SourceOfEnglishName: SubjectArea シート　sourceOfEnglishNameプロパティの　sh:class を追加
- SourceOfEnglishName: Subject シート　sourceOfEnglishNameプロパティの　sh:class を追加
- SourceOfEnglishName: SourceOfEnglishNameのシートはすでにあった（のでなにもしてない）
- CurriculumGuidelineVersion: CurriculumGuidelineシート　hasVersionプロパティのsh:class を追加
- CurriculumGuidelineVersion: CurriculumGuidelineVersionのシートはすでにあった（のでなにもしてない）

これやりました。

**Comment by yegusa** [comment]
### d) 学習指導要領の別バージョンのttlにクラス指定を入れる

curriculum-versions-yyyymmdd.ttl

に、以下のように、 a　の行を追加する。

```ttl

<https://w3id.org/jp-textbook/curriculum/中学校/2012>
  dct:hasVersion [
  a <https://w3id.org/jp-textbook/CurriculumGuidelineVersion>;
  schema:name "平成27年3月 一部改正"@ja;
  schema:name "2015-03 Notification of Partial Revision"@en;
  schema:datePublished "2015-03-27"^^xsd:date;
  schema:citation "『平成27年 文部科学省告示第六十一号』（官報. 平成27年3月27日, 号外第69号, pp.57-59）"@ja;
  schema:citation "\"Notification No. 61 in 2015 of the Ministry of Education, Culture, Sports, Science and Technology\" (Official Gazette, 2015-03-27, Extra Edition No. 69, pp.57-59)"@en;
  schema:url <http://www.mext.go.jp/a_menu/shotou/new-cs/youryou/1356251.htm>;
  ].

```

これやりました。

**Comment by yegusa** [comment]
たぶん、これで、私ができるところはやったんじゃないかな。あとは、 @masao よろしく。

**Comment by masao** [comment]
SourceOfEnglishName クラスは、もしあれば rdfs:seeAlso プロパティがつけられているようだけど、SourceOfEnglishNameShapeに追加されていないようです。

例: [https://w3id.org/jp-textbook/curriculum/中学校/2021/社会](https://w3id.org/jp-textbook/curriculum/%E4%B8%AD%E5%AD%A6%E6%A0%A1/2021/%E7%A4%BE%E4%BC%9A)

**Comment by masao** [comment]
CurriculumGuidelineVersionクラスのほうは targetClass が指定されていないように見えます。

**Comment by yegusa** [comment]
- 「SourceOfEnglishName」シートに、seeAlsoのプロパティを追加しておきました。（なぜ、この行なくなってたんだろう。不思議。前はあったっぽい）
- 「CurriculumFuidelineVersion」シートに、sh:targetClassの行を追加しておきました。

**Comment by masao** [comment]
SourceOfEnglishNameシートにも sh:targetClass の追加が必要そうです。

**Comment by yegusa** [comment]
書いときました。

**Comment by masao** [comment]
https://jp-textbook.github.io/about#SourceOfEnglishNameShape の説明文が表示されるようになったことを確認しました。
