### ISSUE TITLE
単元の該当ページへの参照を示すChapterLUShapeにおけるページ数は数値

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#517]
<http://schema.org/numberOfPages> のデータ型を ``xsd:integer`` で表現しているが、これは小数点を含まない整数値型なので、半ページなどを示す "0.5" などを挿入するためには  ``xsd:decimal`` が必要。

**Comment by yegusa** [comment]
shapes-yyyymmdd.xlsx の ChapterLU のnumberOfPagesプロパティの型をintegerからdecimalに変えました。

これでいいんだよね？

**Comment by masao** [comment]
ひとまず修正を確認しました。クローズします。
