### ISSUE TITLE
編集趣意書の各章種別には別クラスを与えるべき

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#518]
``ChapterCPShape``と``ChapterLUShape``が 同一の``schema:Chapter``クラスを元にしているため、SHACL検証上は区別がつかない状態になっている。

schame:Chapter のサブクラスとして定義しなおして使った方がよさそう。

**Comment by yegusa** [comment]
やり方がわからん。

**Comment by yegusa** [comment]
じゃあ、編修趣意書のChapterの方を独自クラス使う用にしますね！

- shapes-*.xlsx: Shape の　ChapterCPシートのsh:targetClassを独自クラスのCompilingProspectusChapter に変更
- shapes-*.xlsx: Shape の　CompilingProspectusシートのhasPartプロパティのsh:classをCompilingProspectusChapter に変更
- compilingProspectus-*.ttl: ChapterをCompilingProspectusChapterに変更
- schema-*.ttl: CompilingProspectusChapterを追加

をやっておきました。

**Comment by masao** [comment]
ひとまず修正は確認したのでクローズします。
