### ISSUE TITLE
表示文字列に指定言語を示す

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#519]
以下のように、言語名を表示文字列の後ろに追記する。

<dl>
<dt>教科名</dt>
<dd>英語</dd>
<dd>English Language</dd>
</dl>

↓

<dl>
<dt>教科名</dt>
<dd>英語 <span style="font-size:smaller;color:green;">@ja</span></dd>
<dd>English Language <span style="font-size:smaller;color:green;">@en</span></dd>
</dl>

**Comment by masao** [comment]
ttl2html 2.0.0でリニューアルして表示されるようになりました。

**Comment by yegusa** [comment]
例えば、こんなかんじね。OK

![image](https://user-images.githubusercontent.com/1328499/186937500-4e4bc872-626a-49ec-80e9-a57d80a26d72.png)
