### ISSUE TITLE
学習指導要領のタイトルの表示がおかしい

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#52]
["高等学校学習指導要領"]

https://jp-textbook.github.io/curriculum/%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1/2013.html

![image](https://cloud.githubusercontent.com/assets/1328499/25658720/4cbf560e-303f-11e7-8d67-8386013c5b9f.png)

**Comment by masao** [comment]
修正したのでクローズします。
