### ISSUE TITLE
単元LODの説明

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#522]
#495 に関連して。
以下のあたりに、単元LODの説明が必要。

トップの説明：
現在：教科書LODプロジェクトでは、初等教育、中等教育で使われている学習指導要領と現行使用教科書の出版情報を Linked Open Data (LOD) として公開します。

Aboutの説明：
1992年施行の学習指導要領以降の検定教科書を対象として、書誌事項と教科等の関連情報をLOD化しています。 2018年12月現在、約7500タイトルの教科書情報を公開しています。

（また、LODモデル図についても更新が必要。図は #524 へ）

**Comment by yegusa** [comment]
トップの説明：
現在：教科書LODプロジェクトでは、初等教育、中等教育で使われている学習指導要領と現行使用教科書の出版情報、単元情報、編集趣意書情報などを Linked Open Data (LOD) として公開します。

Aboutの説明：
1992年施行の学習指導要領以降の検定教科書を対象として、書誌事項、単元情報、編集趣意書情報および教科等の関連情報をLOD化しています（注：ただし、単元情報と編修趣意書情報については小学校の2019年度使用教科書のみあります）。 2018年12月現在、約7500タイトルの教科書および関連情報を公開しています。


最新のタイトル数については、 @masao よろしく。

**Comment by yegusa** [comment]
注：ただし、単元情報と編修趣意書情報については小学校の2019年度使用教科書のみあります。

**Comment by masao** [comment]
説明を追加しました。

**Comment by yegusa** [comment]
日英確認しました。いいかんじですね。クローズします。
