### ISSUE TITLE
単元のLODモデル図を追加する

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#524]
- [x] 日
- [x] 英

#522 に関連

**Comment by yegusa** [comment]
NHK for Schoolの結果がある学習指導要領コードのある単元を例にするといいかなと。

以下あたりにしようかと。

https://w3id.org/jp-textbook/AA100000003499

https://w3id.org/jp-cos/8260243251100000

**Comment by yegusa** [comment]
こんな感じでどうでしょう？

![tu-lod](https://user-images.githubusercontent.com/1328499/185984572-0d78e815-4985-45e7-8654-c85501ff5ff9.png)

**Comment by yegusa** [comment]
![tu-lod_en](https://user-images.githubusercontent.com/1328499/185986037-98518988-b56f-4fb7-ae7b-217a9e2f0e80.png)

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
キャプションがどっちかわからんから、ちょっと、枠付けてみる？

**Comment by masao** [comment]
枠付けた。

**Comment by yegusa** [comment]
すまん、編集→編修だた。
![tu-lod](https://user-images.githubusercontent.com/1328499/187013228-5ba6fb40-1b75-41cb-b3d0-7c6b6cd0a9d1.png)

**Comment by masao** [comment]
日本語版の画像をさしかえました

**Comment by yegusa** [comment]
OKです。
