### ISSUE TITLE
単元リソースページでNHK for school への検索結果へ行けるようにする

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#525]
学習指導要領リソースへ行くまでもなく、単元リソースのページから直接いけるようにする

例： https://w3id.org/jp-textbook/AA100000003236 ここにNHK for School の検索結果にいけるイメージ。

![image](https://user-images.githubusercontent.com/1328499/186859858-6da44c46-f240-408c-b08c-96db2e006bb1.png)

**Comment by masao** [comment]
一通り実装を追加しました

**Comment by yegusa** [comment]
良いと思います！
