### ISSUE TITLE
単元リソースページのパンくずリストの「Home」がnot found

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#527]
例：https://w3id.org/jp-textbook/AA100000003425 の Home のリンク先： https://jp-textbook.github.io/AA/100000003/ となってる
![image](https://user-images.githubusercontent.com/1328499/187008876-b79cb382-c3f6-4357-8aab-fb31b72850d7.png)

**Comment by masao** [comment]
修正しました。

**Comment by yegusa** [comment]
確認しました。クローズします。
