### ISSUE TITLE
単元ページ内の指導要領URIにはテキストも表示したい

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#528]
現在はURIのみなので、細かなテキストがタイトルとして表示されるとよいかも。。

![image](https://user-images.githubusercontent.com/38825/187017755-d0422ffa-1dee-4b71-a2c8-d81beb55fe09.png)
cf. https://w3id.org/jp-textbook/AA100000001985

**Comment by yegusa** [comment]
どうやって実現するの？

**Comment by yegusa** [comment]
Javascript で https://w3id.org/jp-textbook/AA100000001985.ttl をとってきて、学習指導要領テキストを抜いて表示ってやるかんじね？

**Comment by masao** [comment]
個別にLODデータをロードするようなスクリプトを追加しました。
![image](https://user-images.githubusercontent.com/38825/187058994-333f4972-1370-4c38-bac2-86b5d6f2f462.png)

**Comment by yegusa** [comment]
おお～。確認しました。クローズします。
