### ISSUE TITLE
ブランクノードのラベルと説明文

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#529]
#516 と関連して。
以下のブランクノード用のShape説明について、ラベルや説明を表示できていないので要修正。
https://jp-textbook.github.io/about#ItemNIERShape
https://jp-textbook.github.io/about#ItemTextbookRCShape
https://jp-textbook.github.io/about#SourceOfEnglishNameShape

**Comment by masao** [comment]
SourceOfEnglishNameShape は #516 で解消予定。
ほかの2クラスはオリジナルクラスを使うことにして、ラベル・説明文を追記することにする。

**Comment by yegusa** [comment]
- [x] shape-yyyymmdd.xlsx Itemシートの sh:targertClass http://id.loc.gov/ontologies/bibframe/Item の行を消す
- [x] shape-yyyymmdd.xlsx ItemNIERシートのsh:targetclassの行を追加
- [x] shape-yyyymmdd.xlsx ItemTextbookRCシートのsh:targetclassの行を追加
- [x] schema-yyyymmdd.ttl のItemNIERクラスを追加
- [x] schema-yyyymmdd.ttl のItemTextbookRCクラスを追加

**Comment by yegusa** [comment]
shape と schemaの修正はやりました。 Textbookリソースの  a についての修正は @masao お願い。

**Comment by masao** [comment]
https://jp-textbook.github.io/about#ItemTextbookRCShape
https://jp-textbook.github.io/about#ItemNIERShape
などのラベルがうまく表示されるようになりました。

**Comment by yegusa** [comment]
できているかと思います。また、no title でてきちゃったてのは、別issue #533 にしておきました。
こちらはクローズします。
