### ISSUE TITLE
aboutのno title（itemクラス）

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#533]
#529 から派生

教育図書館と教科書センター資料をあらわすクラスの件を解決したら出てきた問題。
（一つクリアすると他のがでるね）

itemshape の問題だとおもわれる。

どう解決するかまずは考えましょう。

**Comment by yegusa** [comment]
no title はワーニングだして、出力しないってすればいいのじゃあ？

**Comment by masao** [comment]
出力すべきプロパティ一覧の表データが存在しない場合は出力しないことにします。

**Comment by masao** [comment]
ItemShapeについてはaboutページから除外しました。

**Comment by yegusa** [comment]
良いと思います。これでおもいだしたけど、Chapterとかはどうするかねえ。別issue立てます。
