### ISSUE TITLE
謝辞情報の追加

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#535]
単元・編集科研費データベース公開の助成を受けたこと、元データとしてNIER ERIDへのリンクなどを追加すること。

https://erid.nier.go.jp/SHUISHO/index.html

**Comment by masao** [comment]
> 本研究は，JSPS 科研費JP21HP8016 の助成を受けたものである

**Comment by masao** [comment]
謝辞は「概要」節の末尾に入れる（お知らせの前）

**Comment by masao** [comment]
fb93db1c600ea0cbb54abef3863ff2ef9556b4df ひとまず概要の文章内に入れました。

**Comment by yegusa** [comment]
よいとおもいます。
