### ISSUE TITLE
Shape内のHTMLにエラー

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#537]
* ChapterTypeShapeの ``schema:name`` の備考：
  * https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fjp-textbook.github.io%2Fabout#l1157c94

* SourceOfEnglishNameShapeの ``rdfs:seeAlso`` の備考：
  * https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fjp-textbook.github.io%2Fabout#cl1990c59

* TeachingUnitTypeShape の ``schema:name`` の備考:
  * https://validator.w3.org/nu/?showsource=yes&doc=https%3A%2F%2Fjp-textbook.github.io%2Fabout#l2450c94

**Comment by yegusa** [comment]
直しました。

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
確認しました。
