### ISSUE TITLE
何かリンクがおかしい

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#541]
例： [https://w3id.org/jp-textbook/高等学校/2006/理B/016](https://w3id.org/jp-textbook/%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1/2006/%E7%90%86B/016)

![image](https://user-images.githubusercontent.com/1328499/188283631-847df276-5177-4be1-9cdd-416f4d46b961.png)

#164 と関係あるか？

**Comment by masao** [comment]
aタグのマークアップに誤りが含まれていたようでした。修正しました

**Comment by yegusa** [comment]
直ってるとおもいます
