### ISSUE TITLE
出版社リソースの不足: publisher-*.ttl の修正（2021年分）

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#542]
下記のリソースが2021年度使用教科書の出版社情報としてリンクされているが、現状では未定義：

<https://w3id.org/jp-textbook/publisher/2021/CUP>
<https://w3id.org/jp-textbook/publisher/2021/TAC>
<https://w3id.org/jp-textbook/publisher/2021/いいずな>
<https://w3id.org/jp-textbook/publisher/2021/オーム>
<https://w3id.org/jp-textbook/publisher/2021/コロナ>
<https://w3id.org/jp-textbook/publisher/2021/チアーズ>
<https://w3id.org/jp-textbook/publisher/2021/ネット>
<https://w3id.org/jp-textbook/publisher/2021/三省堂>
<https://w3id.org/jp-textbook/publisher/2021/二宮>
<https://w3id.org/jp-textbook/publisher/2021/光村>
<https://w3id.org/jp-textbook/publisher/2021/友社>
<https://w3id.org/jp-textbook/publisher/2021/啓林館>
<https://w3id.org/jp-textbook/publisher/2021/増進堂>
<https://w3id.org/jp-textbook/publisher/2021/大修館>
<https://w3id.org/jp-textbook/publisher/2021/実教>
<https://w3id.org/jp-textbook/publisher/2021/山川>
<https://w3id.org/jp-textbook/publisher/2021/帝国>
<https://w3id.org/jp-textbook/publisher/2021/教出>
<https://w3id.org/jp-textbook/publisher/2021/教図>
<https://w3id.org/jp-textbook/publisher/2021/教芸>
<https://w3id.org/jp-textbook/publisher/2021/数研>
<https://w3id.org/jp-textbook/publisher/2021/文英堂>
<https://w3id.org/jp-textbook/publisher/2021/日文>
<https://w3id.org/jp-textbook/publisher/2021/明成社>
<https://w3id.org/jp-textbook/publisher/2021/明治>
<https://w3id.org/jp-textbook/publisher/2021/東書>
<https://w3id.org/jp-textbook/publisher/2021/東法>
<https://w3id.org/jp-textbook/publisher/2021/桐原>
<https://w3id.org/jp-textbook/publisher/2021/海文堂>
<https://w3id.org/jp-textbook/publisher/2021/清水>
<https://w3id.org/jp-textbook/publisher/2021/第一>
<https://w3id.org/jp-textbook/publisher/2021/筑摩>
<https://w3id.org/jp-textbook/publisher/2021/開隆堂>
<https://w3id.org/jp-textbook/publisher/2021/電機大>

**Comment by yegusa** [comment]
あー、これ、2021年使用分の出版者リストつくらないといけませんね。それで解決するはず。

**Comment by yegusa** [comment]
#412 にあるように、教科書があるかないかにかかわらず、教科書目録にあるすべての出版者情報を追加します。

**Comment by yegusa** [comment]
つくりました。

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
確認しました。ただ、dbpedia が落ちてて、ちゃんとできてるかチェックできてはない。
