### ISSUE TITLE
外国語科目の名称ミス

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#543]
以下の外国語科目を指定しているデータがいくつかあり、名称ミスがあると思われる：

* https://w3id.org/jp-textbook/curriculum/高等学校/2022/外国語/論理・表現
* https://w3id.org/jp-textbook/curriculum/高等学校/2022/外国語/英語コミュニケーション

実際には、「論理・表現I」「論理・表現II」「英語コミュニケーションI」「英語コミュニケーションII」「英語コミュニケーションIII」のいずれかが指定されるべき。

例：<https://w3id.org/jp-textbook/高等学校/2021/CI/712>

**Comment by yegusa** [comment]
元データの修正が必要のようですね。教育図書館に連絡して直してもらいますね。

- NG：元データの /ITEM#1 の列に「論理・表現」と入っている（/TXSIGN#1の列が論I）
- OK：元データの /ITEM#1 の列に「論理・表現I」と入っている（/TXSIGN#1の列が論I）
- NG：元データの /ITEM#1 の列に「英語コミュニケーション」と入っている（/TXSIGN#1の列がCI）
- OK：元データの /ITEM#1 の列に「英語コミュニケーションI」と入っている （/TXSIGN#1の列がCI）

**Comment by yegusa** [comment]
教育図書館にメールで知らせておきました。

**Comment by yegusa** [comment]
修正されたと連絡きたのですが、一部修正漏れがあったので、再度連絡したので、少々おまちを。

**Comment by yegusa** [comment]
まだ修正されてないですが、まあ、すぐに修正されるかと思いますので、手元で修正したものを20.1系にデータをおいておきました。

**Comment by yegusa** [comment]
教育図書館のデータ更新されました。データももらったので、Excelにインポートして作成して、 20.1系フォルダにおいておきました。

**Comment by masao** [comment]
念のためのメモ。一部のデータ（160件ほど）のODATEフィールド（指導要領告示年）が消えていることが分かり、教育図書館に確認いただくことにしました。

**Comment by yegusa** [comment]
はい、教育図書館に連絡しておきました。

**Comment by yegusa** [comment]
修正されました！データももらいましたので、20.1系フォルダに入れています。ちゃんとODATEが160件はいってなかったのが入ったことを確認済みです。

**Comment by masao** [comment]
修正を追加しました

**Comment by yegusa** [comment]
確認しました。
