### ISSUE TITLE
教科「実業」の修正

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#544]
教科として <https://w3id.org/jp-textbook/curriculum/高等学校/2022/実業> が指定されている教科書がいくつかあるが、存在しない教科なので、別のものに修正する必要あり：

以下の73件の教科書が対象：

https://w3id.org/jp-textbook/高等学校/2021/商業/701
https://w3id.org/jp-textbook/高等学校/2021/商業/702
https://w3id.org/jp-textbook/高等学校/2021/商業/703
https://w3id.org/jp-textbook/高等学校/2021/商業/704
https://w3id.org/jp-textbook/高等学校/2021/商業/705
https://w3id.org/jp-textbook/高等学校/2021/商業/706
https://w3id.org/jp-textbook/高等学校/2021/商業/707
https://w3id.org/jp-textbook/高等学校/2021/商業/708
https://w3id.org/jp-textbook/高等学校/2021/商業/709
https://w3id.org/jp-textbook/高等学校/2021/商業/710
https://w3id.org/jp-textbook/高等学校/2021/商業/711
https://w3id.org/jp-textbook/高等学校/2021/商業/712
https://w3id.org/jp-textbook/高等学校/2021/商業/713
https://w3id.org/jp-textbook/高等学校/2021/商業/714
https://w3id.org/jp-textbook/高等学校/2021/商業/715
https://w3id.org/jp-textbook/高等学校/2021/商業/716
https://w3id.org/jp-textbook/高等学校/2021/商業/717
https://w3id.org/jp-textbook/高等学校/2021/家庭/701
https://w3id.org/jp-textbook/高等学校/2021/工業/701
https://w3id.org/jp-textbook/高等学校/2021/工業/702
https://w3id.org/jp-textbook/高等学校/2021/工業/703
https://w3id.org/jp-textbook/高等学校/2021/工業/704
https://w3id.org/jp-textbook/高等学校/2021/工業/705
https://w3id.org/jp-textbook/高等学校/2021/工業/706
https://w3id.org/jp-textbook/高等学校/2021/工業/707
https://w3id.org/jp-textbook/高等学校/2021/工業/708
https://w3id.org/jp-textbook/高等学校/2021/工業/709
https://w3id.org/jp-textbook/高等学校/2021/工業/710
https://w3id.org/jp-textbook/高等学校/2021/工業/711
https://w3id.org/jp-textbook/高等学校/2021/工業/712
https://w3id.org/jp-textbook/高等学校/2021/工業/713
https://w3id.org/jp-textbook/高等学校/2021/工業/714
https://w3id.org/jp-textbook/高等学校/2021/工業/715
https://w3id.org/jp-textbook/高等学校/2021/工業/716
https://w3id.org/jp-textbook/高等学校/2021/工業/717
https://w3id.org/jp-textbook/高等学校/2021/工業/718
https://w3id.org/jp-textbook/高等学校/2021/工業/719
https://w3id.org/jp-textbook/高等学校/2021/工業/720
https://w3id.org/jp-textbook/高等学校/2021/工業/721
https://w3id.org/jp-textbook/高等学校/2021/工業/722
https://w3id.org/jp-textbook/高等学校/2021/工業/723
https://w3id.org/jp-textbook/高等学校/2021/工業/724
https://w3id.org/jp-textbook/高等学校/2021/工業/725
https://w3id.org/jp-textbook/高等学校/2021/工業/726
https://w3id.org/jp-textbook/高等学校/2021/工業/727
https://w3id.org/jp-textbook/高等学校/2021/工業/728
https://w3id.org/jp-textbook/高等学校/2021/工業/729
https://w3id.org/jp-textbook/高等学校/2021/工業/730
https://w3id.org/jp-textbook/高等学校/2021/工業/731
https://w3id.org/jp-textbook/高等学校/2021/工業/732
https://w3id.org/jp-textbook/高等学校/2021/工業/733
https://w3id.org/jp-textbook/高等学校/2021/工業/734
https://w3id.org/jp-textbook/高等学校/2021/工業/735
https://w3id.org/jp-textbook/高等学校/2021/情報/701
https://w3id.org/jp-textbook/高等学校/2021/情報/702
https://w3id.org/jp-textbook/高等学校/2021/情報/703
https://w3id.org/jp-textbook/高等学校/2021/水産/701
https://w3id.org/jp-textbook/高等学校/2021/水産/702
https://w3id.org/jp-textbook/高等学校/2021/水産/703
https://w3id.org/jp-textbook/高等学校/2021/水産/704
https://w3id.org/jp-textbook/高等学校/2021/水産/705
https://w3id.org/jp-textbook/高等学校/2021/水産/706
https://w3id.org/jp-textbook/高等学校/2021/水産/707
https://w3id.org/jp-textbook/高等学校/2021/看護/701
https://w3id.org/jp-textbook/高等学校/2021/福祉/701
https://w3id.org/jp-textbook/高等学校/2021/福祉/702
https://w3id.org/jp-textbook/高等学校/2021/農業/701
https://w3id.org/jp-textbook/高等学校/2021/農業/702
https://w3id.org/jp-textbook/高等学校/2021/農業/703
https://w3id.org/jp-textbook/高等学校/2021/農業/704
https://w3id.org/jp-textbook/高等学校/2021/農業/705
https://w3id.org/jp-textbook/高等学校/2021/農業/706
https://w3id.org/jp-textbook/高等学校/2021/農業/707

**Comment by yegusa** [comment]
元データの /SUBJECT#1 の値が「実業」となっているのがまちがいっぽいです。
同じレコードの /ITEM#1と同じにしないとだめですね。

教育図書館に連絡しておきました。

**Comment by yegusa** [comment]
修正されました。データもらいました。

**Comment by masao** [comment]
修正を追加しました

**Comment by yegusa** [comment]
確認しました。
