### ISSUE TITLE
種目「情報」の修正

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#545]
教科「情報」の種目は「情報I」か「情報II」のいずれかだが、「情報」を指定しているデータがいくつかある：

https://w3id.org/jp-textbook/高等学校/2021/情I/701
https://w3id.org/jp-textbook/高等学校/2021/情I/702
https://w3id.org/jp-textbook/高等学校/2021/情I/703
https://w3id.org/jp-textbook/高等学校/2021/情I/704
https://w3id.org/jp-textbook/高等学校/2021/情I/705
https://w3id.org/jp-textbook/高等学校/2021/情I/706
https://w3id.org/jp-textbook/高等学校/2021/情I/707
https://w3id.org/jp-textbook/高等学校/2021/情I/708
https://w3id.org/jp-textbook/高等学校/2021/情I/709
https://w3id.org/jp-textbook/高等学校/2021/情I/710
https://w3id.org/jp-textbook/高等学校/2021/情I/711
https://w3id.org/jp-textbook/高等学校/2021/情I/712
https://w3id.org/jp-textbook/高等学校/2021/情I/713

教科書記号からは、おそらく「情報I」の誤りかと思われる...

**Comment by yegusa** [comment]
ですね。教育図書館に知らせておきました。

**Comment by yegusa** [comment]
修正されました。データもらいました。

**Comment by masao** [comment]
修正を追加しました

**Comment by yegusa** [comment]
確認しました。
