### ISSUE TITLE
教科「社会」の修正

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#546]
高校教科書のいくつかが教科「社会」が指定されているが、この教科は存在しないのでデータのミスと思われる。
cf. <https://w3id.org/jp-textbook/curriculum/高等学校/2022/社会>

以下の18件：

https://w3id.org/jp-textbook/高等学校/2021/公共/701
https://w3id.org/jp-textbook/高等学校/2021/公共/702
https://w3id.org/jp-textbook/高等学校/2021/公共/703
https://w3id.org/jp-textbook/高等学校/2021/公共/704
https://w3id.org/jp-textbook/高等学校/2021/公共/705
https://w3id.org/jp-textbook/高等学校/2021/公共/706
https://w3id.org/jp-textbook/高等学校/2021/公共/707
https://w3id.org/jp-textbook/高等学校/2021/公共/708
https://w3id.org/jp-textbook/高等学校/2021/公共/709
https://w3id.org/jp-textbook/高等学校/2021/公共/710
https://w3id.org/jp-textbook/高等学校/2021/公共/711
https://w3id.org/jp-textbook/高等学校/2021/公共/712
https://w3id.org/jp-textbook/高等学校/2021/地図/701
https://w3id.org/jp-textbook/高等学校/2021/地図/702
https://w3id.org/jp-textbook/高等学校/2021/地図/703
https://w3id.org/jp-textbook/高等学校/2021/地図/704
https://w3id.org/jp-textbook/高等学校/2021/地図/705
https://w3id.org/jp-textbook/高等学校/2021/地図/706

教科書記号から、「公共」か「地理歴史」のいずれかと思われる。

**Comment by yegusa** [comment]
「公民」か「地理歴史」だね。

教育図書館に連絡しておきました。

**Comment by yegusa** [comment]
修正されました。データもらいました。

**Comment by masao** [comment]
修正を追加しました

**Comment by yegusa** [comment]
確認しました。
