### ISSUE TITLE
芸術教科の種目名の修正

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#547]
2022年度施行の教科「芸術」がもつ種目は 以下のものだが、末尾の番号無しの種目名が登録されているものが見られる。
* 工芸I
* 工芸II
* 工芸III
* 書道I
* 書道II
* 書道III
* 美術I
* 美術II
* 美術III
* 音楽I
* 音楽II
* 音楽III

以下の教科書が該当：

教科書 | 種目
-- | --
https://w3id.org/jp-textbook/高等学校/2021/工I/701 | https://w3id.org/jp-textbook/curriculum/高等学校/2022/芸術/工芸
https://w3id.org/jp-textbook/高等学校/2021/書I/701 | https://w3id.org/jp-textbook/curriculum/高等学校/2022/芸術/書道
https://w3id.org/jp-textbook/高等学校/2021/書I/702 | https://w3id.org/jp-textbook/curriculum/高等学校/2022/芸術/書道
https://w3id.org/jp-textbook/高等学校/2021/書I/703 | https://w3id.org/jp-textbook/curriculum/高等学校/2022/芸術/書道
https://w3id.org/jp-textbook/高等学校/2021/書I/704 | https://w3id.org/jp-textbook/curriculum/高等学校/2022/芸術/書道
https://w3id.org/jp-textbook/高等学校/2021/書I/705 | https://w3id.org/jp-textbook/curriculum/高等学校/2022/芸術/書道
https://w3id.org/jp-textbook/高等学校/2021/美I/701 | https://w3id.org/jp-textbook/curriculum/高等学校/2022/芸術/美術
https://w3id.org/jp-textbook/高等学校/2021/美I/702 | https://w3id.org/jp-textbook/curriculum/高等学校/2022/芸術/美術
https://w3id.org/jp-textbook/高等学校/2021/美I/703 | https://w3id.org/jp-textbook/curriculum/高等学校/2022/芸術/美術
https://w3id.org/jp-textbook/高等学校/2021/音I/701 | https://w3id.org/jp-textbook/curriculum/高等学校/2022/芸術/音楽
https://w3id.org/jp-textbook/高等学校/2021/音I/702 | https://w3id.org/jp-textbook/curriculum/高等学校/2022/芸術/音楽
https://w3id.org/jp-textbook/高等学校/2021/音I/703 | https://w3id.org/jp-textbook/curriculum/高等学校/2022/芸術/音楽
https://w3id.org/jp-textbook/高等学校/2021/音I/704 | https://w3id.org/jp-textbook/curriculum/高等学校/2022/芸術/音楽

施行初年度なので、いずれも工芸I, 書道I, 美術I, 音楽Iとおもわれる。

**Comment by yegusa** [comment]
ですね。 I が足りないようです。教育図書館に連絡しておきました。

**Comment by yegusa** [comment]
修正されました。データもらいました。

**Comment by masao** [comment]
修正分を追加しました。

**Comment by yegusa** [comment]
確認しました。
