### ISSUE TITLE
教科書目録リソースの追加

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#549]
新規出版社リソースが追加されたことにより、以下の教科書目録リソースが必要：

https://w3id.org/jp-textbook/catalogue/小学校/2021
https://w3id.org/jp-textbook/catalogue/中学校/2021
https://w3id.org/jp-textbook/catalogue/高等学校/2021

**Comment by yegusa** [comment]
作っておきました。

**Comment by masao** [comment]
追加しました。

**Comment by yegusa** [comment]
確認しました。
