### ISSUE TITLE
各リソースのページのttl出力にデータタイプがない

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#552]
各リソースのページの下にあるttl出力へのリンクでしゅつりょくされるやつ。 例：https://w3id.org/jp-textbook/%E5%B0%8F%E5%AD%A6%E6%A0%A1/2019/%E5%9B%BD%E8%AA%9E/101.ttl

ツールの方のバグです。

以下のようなかんじでデータタイプがなくなってる。
```
  <https://w3id.org/jp-textbook/authorizedYear> "2019";
  <https://w3id.org/jp-textbook/grade> "1";
```

本当は、以下

```
  <https://w3id.org/jp-textbook/authorizedYear> "2019"^^xsd:gYear;
  <https://w3id.org/jp-textbook/grade> 1;
```

すでにツールで、issue はあがってる。

https://github.com/masao/ttl2html/issues/142

**Comment by masao** [comment]
修正しました

**Comment by yegusa** [comment]
確認しました。
