### ISSUE TITLE
SPARQLエンドポイントの試験公開

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#554]
安定してずーっと公開は難しいかもしれないけど、試験的に公開しますってやりませんか？

* [ ] サーバ自動起動
* [ ] データセット更新手順の文書化
* [ ] HTTPSアクセスの追加

**Comment by yegusa** [comment]
たぶん、
- 認証ポップアップがでる件を修正
- httpsにする？
- 宣伝文言とURL追加

あたりの作業をやれば公開できるはず？

**Comment by masao** [comment]
試験公開: http://edudata.jp:3030/#/dataset/textbook/

あとは HTTPS にする設定を追加する必要があるくらい。。。

**Comment by yegusa** [comment]
あと、更新する方法の確立ですね。

更新用の別サーバーをたてて、公開用に同期する

とかそんなかんじ？

**Comment by masao** [comment]
https://triplydb.com/masao/jp-textbook/sparql/jp-textbook ひとまず、SaaSタイプのサービスに載せました。こちらでよければ、aboutページに載せるようにします。

**Comment by yegusa** [comment]
良いと思います！

**Comment by masao** [comment]
できれば：
* endpoint情報の公開
* [YASUGI](https://triply.cc/docs/yasgui/)などのUIでaboutに埋め込めないか検討する

**Comment by masao** [comment]
二転三転してますが、以下でエンドポイントを公開：https://dydra.com/masao/jp-textbook/sparql

エンドユーザUI:  https://dydra.com/masao/jp-textbook/@query

**Comment by masao** [comment]
<http://rdfs.org/ns/void#sparqlEndpoint> などで全体のデータセット記述にも追加すること。

**Comment by masao** [comment]
トップページとabouitページからもリンクを追加しました。

**Comment by yegusa** [comment]
確認しました。試験的に公開してますってかんじの記述いらないかな？

**Comment by yegusa** [comment]
「試験的に公開してます」は別issueにします。とりあえずクローズします。
