### ISSUE TITLE
cosItemプロパティを修正

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#555]
https://github.com/jp-cos/jp-cos.github.io/issues/82

↑が終わったらになるとおもうけど、

- 単元リソースのプロパティを修正
- shapeを修正

あたりが必要になると思う。

**Comment by yegusa** [comment]
作っておきました。

teachingUnit-AA-body-20221005.ttl
teachingUnit-AB-20221005.ttl
shapes-20221005.xlsx

**Comment by yegusa** [comment]
あと、

schema-20221006.ttl

から、textbook:cosItem を削除しておきました。

**Comment by masao** [comment]
修正を反映しました

**Comment by yegusa** [comment]
確認しました。
