### ISSUE TITLE
FBやtwitterで投稿した時のロゴの変更

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#557]
logo.png は、もともとサイトのヘッダに使ってて、白字の透明画像でFBやtwitterで出るとなんか変なので、画像を別に用意しました。

1) htmlのソースのロゴ画像ファイル名をtextbook-logo-1200x630.pngに修正

```html
    <meta property="og:image" content="https://w3id.org/jp-textbook/logo.png">
```

2) 以下のファイルに。

![textbook-logo-1200x630](https://user-images.githubusercontent.com/1328499/195765469-a865f45a-971b-4f0b-9464-e80e8c1d77e1.png)

なんか、FBだと横長で、twitterだと正方形で真ん中をトリミングされちゃうらしいので。これでちょっとやってみてください。

**Comment by masao** [comment]
現在のツール ttl2html では現在、メインのロゴ画像以外を指定することを想定していないので、何か別の指定方法を考える必要があります。先にそちらの機能を追加してから反映します。 masao/ttl2html#146

**Comment by yegusa** [comment]
はい～。お願いします～。

**Comment by masao** [comment]
上記のロゴ画像を追加しました

**Comment by yegusa** [comment]
https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fw3id.org%2Fjp-textbook%2F

で、ロゴが出ることを確認しました。
