### ISSUE TITLE
教科書リソースにrdfs:labelをつけるのはどうか？

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#559]
教科書リソースへのリンクのアンカーに使われるのを想定。

どれがいいかな。

長くてもいいなら、e) かな。

案：

a)「あたらしい こくご　一上」（東書）
b)「あたらしい こくご　一上」国語|101（東書）
c)「あたらしい こくご　一上」小学校 国語|101（東書）
d)「あたらしい こくご　一上」小学校 1年 国語|101（東書）
e)「あたらしい こくご　一上」小学校 1年 国語|101（東書）2019年検定

[https://w3id.org/jp-textbook/小学校/2019/国語/101](https://w3id.org/jp-textbook/%E5%B0%8F%E5%AD%A6%E6%A0%A1/2019/%E5%9B%BD%E8%AA%9E/101)

**Comment by yegusa** [comment]
[https://w3id.org/jp-textbook/curriculum/小学校/2020/国語/国語](https://w3id.org/jp-textbook/curriculum/%E5%B0%8F%E5%AD%A6%E6%A0%A1/2020/%E5%9B%BD%E8%AA%9E/%E5%9B%BD%E8%AA%9E)

とかで、
教科書リソースのリンクをたどろうとして、地味に辛いので、なんとかしたいのです。それでこの案です。

**Comment by yegusa** [comment]
東書はもし、出版者の名前なら「東京書籍株式会社」になる。

**Comment by masao** [comment]
``dcterms:bibliographicCitation`` あたりで追加するのが良さそう

**Comment by yegusa** [comment]
スクリプトのほうで新しい属性名を追加する方向で対応する。

**Comment by yegusa** [comment]
shape追加しておきました

**Comment by masao** [comment]
追加しました

**Comment by yegusa** [comment]
dct:bibliographicCitation	書誌情報
が追加されているのを確認しました。クローズします。
