### ISSUE TITLE
連絡先・プロジェクト情報を追記する

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#560]
現状、連絡先に江草・高久しか書いていない。
教科書LODのなかに単元LODが加わったこともあり、「教科書LODプロジェクト」の名義に他のメンバーを加えること。
また、連絡先メールアドレスも追記すること。

**Comment by masao** [comment]
追加しました 
https://github.com/jp-textbook/jp-textbook.github.io/commit/966ef29d8597bdb58ec225902b3e4ad65081799a

**Comment by yegusa** [comment]
確認しました。クローズします。
