### ISSUE TITLE
トップページの「最新のお知らせ」の節タイトルを「最新のデータセット」などとする

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#563]
トップページの最下部の最新のお知らせについて

赤四角の部分：

- 最新のお知らせ →　最新のデータセット
- 過去の更新履歴　→　過去のデータセット

あたりにする
（受賞歴などの「お知らせ」と区別するため）

![教科書LOD](https://user-images.githubusercontent.com/1328499/208621575-140a3364-0857-4602-bee2-6deacc002825.png)

**Comment by masao** [comment]
修正しました。

**Comment by yegusa** [comment]
確認しました。クローズします。
