### ISSUE TITLE
html5 validation

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#575]
index.html: https://validator.w3.org/nu/?doc=https%3A%2F%2Fjp-textbook.github.io%2F

* imgタグの alt 属性が必要

教科書ページ: https://validator.w3.org/nu/?doc=https%3A%2F%2Fjp-textbook.github.io%2F%25E5%25B0%258F%25E5%25AD%25A6%25E6%25A0%25A1%2F2019%2F%25E7%2590%2586%25E7%25A7%2591%2F301

* formタグは li 要素の内部に変更する

**Comment by masao** [comment]
気づいたところは直しました

**Comment by yegusa** [comment]
確認しました。クローズします。
