### ISSUE TITLE
中学校、自由社の「新しい歴史教科書」歴史 712の教科書リソース追加など

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#579]
中学校、自由社の「新しい歴史教科書」歴史 712 が購入洩れだったそうで、追加されたので更新が必要です。

データは入手ずみです。

**Comment by masao** [comment]
追加しました。

**Comment by masao** [comment]
cf. [https://w3id.org/jp-textbook/中学校/2021/歴史/712](https://w3id.org/jp-textbook/%E4%B8%AD%E5%AD%A6%E6%A0%A1/2021/%E6%AD%B4%E5%8F%B2/712)

**Comment by yegusa** [comment]
確認しました。
