### ISSUE TITLE
中学校単元LODの入力作業

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#581]
これまでの単元LODは、小学校分だけだったので、中学校分を追加すること。

**Comment by masao** [comment]
細かな作業はアルバイトなどに依頼して作業できるようにすすめること。7月上旬を予定。

**Comment by masao** [comment]
こちらも完了な気がします。

**Comment by yegusa** [comment]
#611 とおなじissueになりますかね。できているのでクローズします。
