### ISSUE TITLE
単元リソースのcosコードが根だった場合に葉をどう入力するか

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#587]
これから入力する中学校の単元リソースについて、
cosコードは書かれたままのを入力することにした。
（つまり、根にあたるcosコードでも葉を全部入れていた）

そこで、根にあたるようなcosコードであった場合、例えば、
cs:cosItemについて、
https://w3id.org/jp-cos/8322203210000000
↑が、単元リソースにつけられていたとする。

中学　社会　歴史的分野の　B(1)
節番号（階層）：第1章 / 第2章 / 第2節 / 第2 / 〔歴史的分野〕 / 2 / B / (1)

例えば、以下の単元リソース：

例：中学校　社会　歴史的分野　帝国書院
https://www.mext.go.jp/content/20200428_mxt_kouhou02_mext_00003_08.pdf

https://w3id.org/jp-textbook/AA100000015394
ページ：14~57
単元名：第 2 部 : 第１章　古代国家の成立と東アジア
学習指導要領の細目（転記）：B(1)
cosコード：8322203210000000
節番号（階層）：第1章 / 第2章 / 第2節 / 第2 / 〔歴史的分野〕 / 2 / B / (1)

こういう単元があったとして、この細目は、下に、
B(1)ア
B(1)ア（ア）
B(1)ア（イ）
B(1)イ
など、葉っぱのcosコードがいっぱいある。

このような葉っぱのcosコードがこのままでは
SPARQLなどでヒットしないことになるので、
これらの葉のcosコードを含めた属性を新規で立てるのがいいのではないか？

案１：根と葉っぱ両方をいれる属性
　　利点：検索のときにもれなくできる
B(1)
B(1)ア
B(1)ア（ア）
B(1)ア（イ）
B(1)イ

案２：葉っぱだけをいれる属性
　　利点：重複情報がないのでメンテが楽（？）
B(1)ア
B(1)ア（ア）
B(1)ア（イ）
B(1)イ

**Comment by yegusa** [comment]
案1 でいく。　属性名　expantedCosItem（仮）とする。

**Comment by masao** [comment]
念のため、ここにメモしておきます。

上位階層のコードだけ入っているものをSPARQL経由で下位のノードも検索対象に含める例がWebNDLAのヘルプに載っています： https://id.ndl.go.jp/information/sparql-11/#s2-2

その例を今回にあてまめると、以下のようなSPARQLが書けるはずです：
```sparql
PREFIX schema: <http://schema.org/>
PREFIX cs: <https://w3id.org/jp-cos/>
select * where { 
cs:8322203210000000 schema:hasPart+ ?child.
?child cs:sectionNumberHierarchy ?sectionnumbers.
?child cs:sectionText ?sectiontext.
} ORDER BY ASC(?child)
```

応答例：

|?child | ?sectionnumbers | ?sectiontext
|-- | -- | --
|https://w3id.org/jp-cos/8322203211000000 | 第1章 / 第2章 / 第2節 / 第2 / 〔歴史的分野〕 / 2 / B / (1) / ア | 次のような知識を身に付けること。
|https://w3id.org/jp-cos/8322203211100000 | 第1章 / 第2章 / 第2節 / 第2 / 〔歴史的分野〕 / 2 / B / (1) / ア / (ア) | 世界の古代文明や宗教のおこり 世界の古代文明や宗教のおこりを基に，世界の各地で文明が築かれたことを理解すること。
|https://w3id.org/jp-cos/8322203211200000 | 第1章 / 第2章 / 第2節 / 第2 / 〔歴史的分野〕 / 2 / B / (1) / ア / (イ) | 日本列島における国家形成 日本列島における農耕の広まりと生活の変化や当時の人々の信仰，大和朝廷(大和政権)による統一の様子と東アジアとの関わりなどを基に，東アジアの文明の影響を受けながら我が国で国家が形成されていったことを理解すること。
|https://w3id.org/jp-cos/8322203211300000 | 第1章 / 第2章 / 第2節 / 第2 / 〔歴史的分野〕 / 2 / B / (1) / ア / (ウ) | 律令《りつりょう》国家の形成 律令《りつりょう》国家の確立に至るまでの過程，摂関政治などを基に，東アジアの文物や制度を積極的に取り入れながら国家の仕組みが整えられ，その後，天皇や貴族による政治が展開したことを理解すること。
|https://w3id.org/jp-cos/8322203211400000 | 第1章 / 第2章 / 第2節 / 第2 / 〔歴史的分野〕 / 2 / B / (1) / ア / (エ) | 古代の文化と東アジアとの関わり 仏教の伝来とその影響，仮名文字の成立などを基に，国際的な要素をもった文化が栄え，それらを基礎としながら文化の国風化が進んだことを理解すること。
|https://w3id.org/jp-cos/8322203212000000 | 第1章 / 第2章 / 第2節 / 第2 / 〔歴史的分野〕 / 2 / B / (1) / イ | 次のような思考力，判断力，表現力等を身に付けること。
|https://w3id.org/jp-cos/8322203212100000 | 第1章 / 第2章 / 第2節 / 第2 / 〔歴史的分野〕 / 2 / B / (1) / イ / (ア) | 古代文明や宗教が起こった場所や環境，農耕の広まりや生産技術の発展，東アジアとの接触や交流と政治や文化の変化などに着目して，事象を相互に関連付けるなどして，アの(ア)から(エ)までについて古代の社会の変化の様子を多面的・多角的に考察し，表現すること。
|https://w3id.org/jp-cos/8322203212200000 | 第1章 / 第2章 / 第2節 / 第2 / 〔歴史的分野〕 / 2 / B / (1) / イ / (イ) | 古代までの日本を大観して，時代の特色を多面的・多角的に考察し，表現すること。


というわけで、SPARQL経由で上記の情報がいつでも入手可能です。

**Comment by yegusa** [comment]
アイデア：逆発想で、originalCosItem として、転記のcosコードだという属性をつくって、そっちに必ず転記とわかるものを入れる。

**Comment by yegusa** [comment]
cosItem には、全てのパターンをいれる（転記した親から全部を入れる）ことにする。「ただし旧データは親が入ってないことがあり、最後の葉だけがあることに注意」としておく。

**Comment by yegusa** [comment]
shape ファイルを修正しました。

shapes-20241231.xlsx

**Comment by masao** [comment]
originalCosCodeの追加に対応しました

**Comment by yegusa** [comment]
追加されているのを確認しました。クローズします。
