### ISSUE TITLE
SPARQLエンドポイントを試験公開しているという文言の追加

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#589]
このデータセットに対するSPARQLエンドポイントは以下のURLからアクセスできます: https://dydra.com/masao/jp-textbook/sparql

修正後案：
このデータセットに対するSPARQLエンドポイントは以下のURLからアクセスできます（試験公開中）: https://dydra.com/masao/jp-textbook/sparql

はどうか？

**Comment by masao** [comment]
修正しました

**Comment by yegusa** [comment]
確認しました。クローズします。
