### ISSUE TITLE
高等学校の「種目」が「空欄」になっているべきところが値が入っている

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#59]
- [x] 教育図書館に連絡済み 2017-05-09 教育図書館では修正しないとのこと

教育図書館ではこの修正はしないとのことなので、プログラムで対応することにする。

例えば、教科：「看護」、には、種目「看護」がはいっているが、
正確には、「（空欄）」であるべき

https://nieropac.nier.go.jp/ebopac/EB10020566

なぜなら、「看護」は専門的な教科であり、教科書目録は、こういう専門「教科」の種目は
個々には記載されておらず、種目の欄は、空欄となっており、「看護」という種目ではないため。

## 高等学校/1994の教科、種目が

- 家庭
- 看護
- 工業
- 商業
- 水産
- 農業

## 高等学校2003の教科、種目が

- 家庭
- 看護
- 工業
- 商業
- 情報
- 水産
- 農業
- 福祉

**Comment by yegusa** [comment]
注：高等学校/1994の教科 は、専門、共通の区別がなく、「家庭」は「共通」にぞくするものがあるとおもわれるが、こちらも、高等学校/1994の場合は、教科書目録には、個別の種目がはいっていないはずなので、「（空欄）」になっているべき。

**Comment by yegusa** [comment]
プログラムとして処理する場合は、

- 高等学校の「種目」で「教科」とまったく同じものは、種目は「（空欄）」にする(種別プロパティを出力しない）
- ただし、種目：「保健体育」（教科「保健体育」）は、例外です。種別「保健体育」を出力すること。

でうまくいくと思います。
（すくなくとも、現在対象としている種目で、教科と科目が全く同じものは、「保健体育」でｓ

注意：

- 高等学校でも、「保健体育」については、教科：「保健体育」、種別：「保健体育」は存在するので、誤って消さないこと！
- 高等学校以外の場合は、教科と種目が同じになっていてもおかしくないので、小学校や中学校の場合は、教科＝種目となっていてもおかしくないので、高等学校以外の種別について誤って消さないこと！

**Comment by masao** [comment]
一通り開発したので確認願います。

**Comment by masao** [comment]
指導要領施行年のかわりに検定年をつかって判定していたので、バグを修正します。

**Comment by yegusa** [comment]
以下、全てOKなことを確認しましたので、クローズします。

## 高等学校/1994の教科、種目が

- 家庭
- 看護
- 工業
- 商業
- 水産
- 農業

## 高等学校2003の教科、種目が

- 家庭
- 看護
- 工業
- 商業
- 情報
- 水産
- 農業
- 福祉
