### ISSUE TITLE
単元入力したExcelファイルからTurtle形式に変換するスクリプト

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#591]
新しい形式の単元情報を入力したExcelファイルを読み込んで、一括でTurtle形式に変換するスクリプトを開発しておくこと。

**Comment by masao** [comment]
Excelから、単に「単元ID, COSコード」の一覧を読み込んで、「単元ID, オリジナルCOSコード, 拡張COSコード」を読み込むようなスクリプトを書くだけにとどめて、実際の単元LODの更新作業はPoorman Toolkitに任せること。

**Comment by masao** [comment]
[単元_中学_渡辺.txt](https://github.com/user-attachments/files/16648411/_._.txt)
変換したファイルの例です。

**Comment by masao** [comment]
こちらは不要になったissueのようなので、クローズしましょうか。

**Comment by yegusa** [comment]
はい、ではクローズします。
