### ISSUE TITLE
編集趣意書の種目名に全角カッコの入力ミス

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#593]
#592 に関連して。
新しい編集趣意書の種目名に誤り。
<https://w3id.org/jp-textbook/curriculum/中学校/2021/社会/社会（公民的分野）> が記録されているが （）かっこが全角なので、要修正。
正確には、
<https://w3id.org/jp-textbook/curriculum/中学校/2021/社会/社会(公民的分野)>

**Comment by yegusa** [comment]
修正しました。

**Comment by masao** [comment]
修正を反映しました

**Comment by yegusa** [comment]
確認しました
