### ISSUE TITLE
高校の専門教科における種目の新しい指導要領分の追加

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#596]
#584 からの派生。
#59 での種目が空となっている専門教科における種目情報が、指導要領単位で指定しているので、指導要領が新しくなったら追加しないといけない。

種目名の追加対象として、下記の指導要領分を追加すること：
[https://w3id.org/jp-textbook/curriculum/高等学校/2022](https://w3id.org/jp-textbook/curriculum/%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1/2022)

**Comment by masao** [comment]
追加しました

**Comment by yegusa** [comment]
確認しました。クローズします。
