### ISSUE TITLE
小学校、中学校、高等学校のラベルがない？

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#598]
![image](https://github.com/user-attachments/assets/0b64e07a-5987-4c2a-a393-24ed9609704f)

**Comment by masao** [comment]
学校種別のラベルを取り出すところで、日本語ラベル（ja）を取り出す際に、 :ja と比較するのか "ja" と比較するのかで差が出てました。:ja が正しいらしい…。

修正しました。

**Comment by yegusa** [comment]
修正されていることを確認しました。クローズします。
