### ISSUE TITLE
重複レコードをチェック

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#6]
- [x] 教育図書館データ修正
- [x] 教育図書館からデータ入手　2017-04-27版
- [ ] ttl作成

同一のURIを持つレコードがいくつか出ている。。。

教育図書館で内容を確認すること。

**Comment by yegusa** [comment]
「重複チェック」列のピンクのセルね。

**Comment by yegusa** [comment]
以下が、同じURIが2件あるもの

1993/物A/502
1999/地図/405
1999/地図/406
2001/英語/904
2002/国総/007
2004/国語/115
2004/国語/116
2004/国語/117
2004/国語/215
2004/国語/216
2004/国語/315
2004/国語/316
2004/国語/415
2004/国語/416
2004/国語/515
2004/国語/516
2004/国語/615
2004/国語/616
2004/書III/002
2005/公民/909
2005/公民/910
2005/書写/710
2005/書写/810
2005/数学/708
2005/数学/808
2005/数学/908
2005/地理/709
2005/歴史/710
2007/書II/009

**Comment by yegusa** [comment]
以下は、高久メモ

要修正候補？

EB10018019 （ほとんどの情報が同一。重複?）
EB10018016

EB10009725 （ほとんどの情報が同一。重複?）
EB10009612

EB10009726 （ほとんどの情報が同一。重複?）
EB10009613

EB10015334 （以下と教科書番号+検定年が同一。こちらは改訂版なので、おそらく検定年がおかしいと思われる）
EB10015324

EB10025505 （以下と教科書番号+検定年が同一。出版者も異なるので、教科書番号がミスと思われる）
EB10025512

EB10010087 （以下と教科書番号+検定年が同一。出版者も異なるので、教科書番号がミスと思われる）
EB16219840

EB10010088 （以下と教科書番号+検定年が同一。出版者も異なるので、教科書番号がミスと思われる）
EB16219841

EB10010219 （以下と教科書番号+検定年が同一。出版者も異なるので、教科書番号がミスと思われる）
EB10010099

EB10010089 （以下と教科書番号+検定年が同一。出版者も異なるので、教科書番号がミスと思われる）
EB16219842

EB10010090 （以下と教科書番号+検定年が同一。出版者も異なるので、教科書番号がミスと思われる）
EB16219843

EB10010091 （以下と教科書番号+検定年が同一。出版者も異なるので、教科書番号がミスと思われる）
EB16219844

EB10010092 （以下と教科書番号+検定年が同一。出版者も異なるので、教科書番号がミスと思われる）
EB16219845

EB10010093 （以下と教科書番号+検定年が同一。出版者も異なるので、教科書番号がミスと思われる）
EB16219846

EB10010094 （以下と教科書番号+検定年が同一。出版者も異なるので、教科書番号がミスと思われる）
EB16219847

EB10010095 （以下と教科書番号+検定年が同一。出版者も異なるので、教科書番号がミスと思われる）
EB16219848

EB10010096 （以下と教科書番号+検定年が同一。出版者も異なるので、教科書番号がミスと思われる）
EB16219849

EB10010097 （以下と教科書番号+検定年が同一。出版者も異なるので、教科書番号がミスと思われる）
EB16219850

EB10010098 （以下と教科書番号+検定年が同一。出版者も異なるので、教科書番号がミスと思われる）
EB16219851

EB16328908 （以下と教科書番号+検定年が同一。出版者も異なるので、教科書番号がミスと思われる）
EB10026307

EB10015376 （出版者と使用年度のみが違う。教科書番号のミス?）
EB16208670

EB10015377 （出版者と使用年度が違う。教科書番号のミス? または検定年のミス?）
EB16208674

EB10015352 （出版者と使用年度が違う。教科書番号のミス?）
EB16208684

EB10015353 （出版者と使用年度が違う。教科書番号のミス?）
EB16208685

EB10015389 （出版者と使用年度が違う。教科書番号のミス?）
EB16208686

EB10015390 （出版者と使用年度が違う。教科書番号のミス?）
EB16208687

EB10015391 （出版者と使用年度が違う。教科書番号のミス?）
EB16208688

EB10015363 （出版者と使用年度が違う。教科書番号のミス?）
EB16208676

EB10015369 （出版者と使用年度が違う。教科書番号のミス?）
EB16208675

EB10026937 （出版者と使用年度が違う。教科書番号のミス?）
EB16239319

EB16209094
EB16209095




EB10015363 （以下と教科書番号+検定年が同一。出版者も使用年度も異なるので、教科書番号がミスと思われる）
EB16208676

**Comment by yegusa** [comment]
上記、高久メモをひとつひとつ調査。

大半は、大阪書籍→日本文教出版　に版権が移動したことによって、起きた現象で、これはこういもの。

これらを除いたものについては、鈴木さんに確認することにした。

**Comment by yegusa** [comment]
<pre>
書誌ID	重複ID	鈴木報告
EB10018016	a01	済み：本家こちらを残し済み
EB10018019	a01	済み：本家こちらを削除済み
EB10009612	a02	これから：重複として
EB10009725	a02	これから：重複として
EB10009613	a03	これから：重複として
EB10009726	a03	これから：重複として
EB10015324	a04	しない：改訂版でも検定しないことはあるため
EB10015334	a04	しない：改訂版でも検定しないことはあるため
EB10025505	a05	これから：教科書記号間違いとして
EB10025512	a05	しない：片方がまちがえのため
EB10010087	a06	しない：大書→日文のため
EB16219840	a06	しない：大書→日文のため
EB10010088	a07	しない：大書→日文のため
EB16219841	a07	しない：大書→日文のため
EB10010099	a08	しない：片方がまちがえのため
EB10010219	a08	これから：教科書記号間違いとして
EB10010089	a09	しない：大書→日文のため
EB16219842	a09	しない：大書→日文のため
EB10010090	a10	しない：大書→日文のため
EB16219843	a10	しない：大書→日文のため
EB10010091	a11	しない：大書→日文のため
EB16219844	a11	しない：大書→日文のため
EB10010092	a12	しない：大書→日文のため
EB16219845	a12	しない：大書→日文のため
EB10010093	a13	しない：大書→日文のため
EB16219846	a13	しない：大書→日文のため
EB10010094	a14	しない：大書→日文のため
EB16219847	a14	しない：大書→日文のため
EB10010095	a15	しない：大書→日文のため
EB16219848	a15	しない：大書→日文のため
EB10010096	a16	しない：大書→日文のため
EB16219849	a16	しない：大書→日文のため
EB10010097	a17	しない：大書→日文のため
EB16219850	a17	しない：大書→日文のため
EB10010098	a18	しない：大書→日文のため
EB16219851	a18	しない：大書→日文のため
EB10026307	a19	しない：大書→日文のため
EB16328908	a19	しない：大書→日文のため
EB10015376	a20	済み：こちらを削除する：使用年がかぶるものがある
EB16208670	a20	済み：こちらを残す：使用年がかぶるものがある
EB10015377	a21	しない：大書→日文のため
EB16208674	a21	しない：大書→日文のため
EB10015352	a22	しない：大書→日文のため
EB16208684	a22	しない：大書→日文のため
EB10015353	a23	しない：大書→日文のため
EB16208685	a23	しない：大書→日文のため
EB10015389	a24	しない：大書→日文のため
EB16208686	a24	しない：大書→日文のため
EB10015390	a25	しない：大書→日文のため
EB16208687	a25	しない：大書→日文のため
EB10015391	a26	しない：大書→日文のため
EB16208688	a26	しない：大書→日文のため
EB10015363	a27,a31	しない：大書→日文のため
EB16208676	a27,a31	しない：大書→日文のため
EB10015369	a28	しない：大書→日文のため
EB16208675	a28	しない：大書→日文のため
EB10026937	a29	しない：大書→日文のため
EB16239319	a29	しない：大書→日文のため
EB16209094	a30	しない；こちらのチェックミス
EB16209095	a30	しない；こちらのチェックミス
</pre>

**Comment by yegusa** [comment]
例外処理が必要そうなもの

◆改訂もの
https://nieropac.nier.go.jp/ebopac/EB10015324	a04	しない：改訂版でも検定しないことはあるため
https://nieropac.nier.go.jp/ebopac/EB10015334	a04	しない：改訂版でも検定しないことはあるため

◆大書→日文
（たくさんあるので省略）

**Comment by yegusa** [comment]
メモ：
鈴木さんにききましたが、副本は請求記号の最後に a がつくそうですが、このデータベースには副本の情報は基本的には載せてないそうです。このデータベースは書誌データベースとなっており、請求記号は、代表的な請求記号という理解をするとのこと。

**Comment by yegusa** [comment]
検定年はかわらずに、修正される一例ですが、
たとえば、「雪国はつらつ条例」を「雪国はつらいよ条例」と間違えていた
そして、検定もすり抜けていたといった場合があるようです。

**Comment by yegusa** [comment]
修正記録。本家では修正ずみ。

> ◆重複しているように見える（まったく同じレコードにみえる）
> EB10009612　→削除
> EB10009725　→イキ


> ◆重複しているように見える（まったく同じレコードにみえる）
> EB10009613　→削除
> EB10009726　→イキ

> ◆教科書記号間違い? 「国総」→「国I」
> EB10025505

国I　に修正

> ◆教科書記号間違い？ 「国語」→「算数」
> EB10010219

算数　に修正

> ◆使用年が被るのみのレコード 重複？・・・先ほど口頭で報告済み
> EB10015376　→削除済
> EB16208670

**Comment by yegusa** [comment]
確認結果をまとめました

<pre>
書誌ID	重複ID	重複処理メモ
EB10018016	a01	なにもしない：重複、こちらを残す
EB10018019	a01	要修正：こちらを削除：重複
EB10009612	a02	要修正：こちらを削除：重複
EB10009725	a02	なにもしない：重複、こちらを残す
EB10009613	a03	要修正：こちらを削除：重複
EB10009726	a03	なにもしない：重複、こちらを残す
EB10015324	a04	要例外処理：改訂版があっても検定するわけでないので
EB10015334	a04	要例外処理：改訂版があっても検定するわけでないので
EB10025505	a05	要修正：教科書記号を国総→国Iに修正
EB10025512	a05	なにもしない：こっちは正しい
EB10010087	a06	要例外処理：大書→日文
EB16219840	a06	要例外処理：大書→日文
EB10010088	a07	要例外処理：大書→日文
EB16219841	a07	要例外処理：大書→日文
EB10010099	a08	なにもしない：こっちは正しい
EB10010219	a08	要修正：教科書記号を国語→算数に修正
EB10010089	a09	要例外処理：大書→日文
EB16219842	a09	要例外処理：大書→日文
EB10010090	a10	要例外処理：大書→日文
EB16219843	a10	要例外処理：大書→日文
EB10010091	a11	要例外処理：大書→日文
EB16219844	a11	要例外処理：大書→日文
EB10010092	a12	要例外処理：大書→日文
EB16219845	a12	要例外処理：大書→日文
EB10010093	a13	要例外処理：大書→日文
EB16219846	a13	要例外処理：大書→日文
EB10010094	a14	要例外処理：大書→日文
EB16219847	a14	要例外処理：大書→日文
EB10010095	a15	要例外処理：大書→日文
EB16219848	a15	要例外処理：大書→日文
EB10010096	a16	要例外処理：大書→日文
EB16219849	a16	要例外処理：大書→日文
EB10010097	a17	要例外処理：大書→日文
EB16219850	a17	要例外処理：大書→日文
EB10010098	a18	要例外処理：大書→日文
EB16219851	a18	要例外処理：大書→日文
EB10026307	a19	要例外処理：大書→日文
EB16328908	a19	要例外処理：大書→日文
EB10015376	a20	要修正：こちらを削除：重複
EB16208670	a20	なにもしない：重複、こちらを残す
EB10015377	a21	要例外処理：大書→日文
EB16208674	a21	要例外処理：大書→日文
EB10015352	a22	要例外処理：大書→日文
EB16208684	a22	要例外処理：大書→日文
EB10015353	a23	要例外処理：大書→日文
EB16208685	a23	要例外処理：大書→日文
EB10015389	a24	要例外処理：大書→日文
EB16208686	a24	要例外処理：大書→日文
EB10015390	a25	要例外処理：大書→日文
EB16208687	a25	要例外処理：大書→日文
EB10015391	a26	要例外処理：大書→日文
EB16208688	a26	要例外処理：大書→日文
EB10015363	a27,a31	要例外処理：大書→日文
EB16208676	a27,a31	要例外処理：大書→日文
EB10015369	a28	要例外処理：大書→日文
EB16208675	a28	要例外処理：大書→日文
EB10026937	a29	要例外処理：大書→日文
EB16239319	a29	要例外処理：大書→日文
EB16209094	a30	なにもしない：問題なし
EB16209095	a30	なにもしない：問題なし
</pre>

**Comment by yegusa** [comment]
教育図書館が修正すべきデータは修正ずみで、2017-04-27データ入手版では反映済みのデータです。のこりについては、 #35 のほうで処理します。ので、マイルストーンは2.0にしてこちらは、いったんクローズにします。
