### ISSUE TITLE
教科・科目「情報」の英訳が異なる

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#600]
新しい教科「情報」と科目「情報 I/II」の訳語は Information Study から Informatics に変更になったようだが、教科書LOD上の情報が古い方の英訳を使っている模様。

**Comment by yegusa** [comment]
平成30年改訂高等校学習指導要領英訳版（仮訳）
https://www.mext.go.jp/a_menu/shotou/new-cs/1417513.htm

こっちを使って英訳を作り直したほうがいいね。

**Comment by yegusa** [comment]
新しくできた「科目」や「教科」があれば上記の英訳を使って作成していたけど、科目名や教科名が旧学習指導要領にあるものは新しい英訳からは英訳を作成していなかったのでこの現象が起きたようです。まさか、同じ教科や科目名で、英訳が変わっていることがあるとは思わなかったので。

**Comment by yegusa** [comment]
いっそのこといまはブランクノードにしているのを、教科英訳出典リソース、科目英訳出典リソースを作るというのも検討中

**Comment by yegusa** [comment]
全学習指導要領（4改定分）やろうとするとくじけるので、まずは、フェーズ1として、最新の学習指導要領だけやりますね。

**Comment by yegusa** [comment]
ていうか、種目はともかく、教科は学習指導要領LODにいれたほうがよくない？

**Comment by yegusa** [comment]
ああ、でも、学習指導要領LODにない古い分がいるか。。。でも、教科・科目データだけつくればええのか？

**Comment by yegusa** [comment]
というか、今、気づいたけど、学習指導要領LODの教科や科目の英語も直さないといけないね。

例：
[https://w3id.org/jp-cos/UpperSecondary/2018/情報](https://w3id.org/jp-cos/UpperSecondary/2018/%E6%83%85%E5%A0%B1)

**Comment by yegusa** [comment]
参考： 高等学校教科「情報」の英文表記について   情報処理学会の提言　2017年4月18日
 https://www.ipsj.or.jp/release/teigen20170418.html#:~:text=%E7%8F%BE%E5%9C%A8%EF%BC%8C%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1%E6%95%99%E7%A7%91%E3%80%8C%E6%83%85%E5%A0%B1,%E3%81%AA%E3%81%A3%E3%81%A6%E3%81%84%E3%81%BE%E3%81%99%5B1%5D%E3%80%82

**Comment by yegusa** [comment]
続報：
私が英訳を作ったのは、2020-10-31に出典を参照して作成していました。
当時は 教科の情報はInformation、情報IはInformation Study だったようです。

いつからしれっと改訂版にさしかわったのかはわかりませんが、ファイル名からしたら、すくなくとも最新版は、20230303版のようですね。。。


https://web.archive.org/web/20201030084424/https://www.mext.go.jp/content/20200616-mxt_kyoiku02-100014466_1.pdf

**Comment by yegusa** [comment]
すくなくとも、2022年12月6日までは、情報はInformation、情報IはInformation Study I だったようです。
https://web.archive.org/web/20221206085903/https://www.mext.go.jp/a_menu/shotou/new-cs/1417513.htm

2023年3月7日には、今と同じ版の仮訳（情報はInformatics、情報IはInformatics I）がのっているようです。
https://web.archive.org/web/20230307075147/https://www.mext.go.jp/a_menu/shotou/new-cs/1417513.htm

**Comment by yegusa** [comment]
修正しました。24.0系にデータ置いておきました。

**Comment by yegusa** [comment]
#606 が関連する。

**Comment by masao** [comment]
修正しました。
ex. [https://w3id.org/jp-textbook/curriculum/高等学校/2022/情報](https://w3id.org/jp-textbook/curriculum/%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1/2022/%E6%83%85%E5%A0%B1)

**Comment by yegusa** [comment]
確認しました。
