### ISSUE TITLE
編集趣意書から対応する教科書へのリンクが変なURIになっているものがある

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#608]
1件だけ、編集趣意書の基本情報で、教科書リソースへのURIが間違えている：

https://w3id.org/jp-textbook/AC100000000316 は [https://w3id.org/jp-textbook/中学校/2020//](https://jp-textbook.github.io/%E4%B8%AD%E5%AD%A6%E6%A0%A1/2020) を指定している（つまり、教科書記号・番号が付いていないURIになっている）。

**Comment by yegusa** [comment]
教科書記号とうに「-」をいれないといけないのを入力ミスしていて、教科書が2冊あるかのようになっていたもよう。修正した。

**Comment by masao** [comment]
修正しました

**Comment by yegusa** [comment]
確認しました。
