### ISSUE TITLE
教科書リソース公開ページに「学習指導要領との対照表と配当授業時数表」へのリンクを追加する

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#610]
たとえば、

「あたらしい こくご　一上」, 小学校1年, 国語|101 (東書) 2019年検定
[https://w3id.org/jp-textbook/小学校/2019/国語/101](https://w3id.org/jp-textbook/%E5%B0%8F%E5%AD%A6%E6%A0%A1/2019/%E5%9B%BD%E8%AA%9E/101)

この教科書に、

「学習指導要領との対照表と配当授業時数表」というプロパティを追加して、以下のURLの値になるかんじ。

https://www.mext.go.jp/component/a_menu/education/micro_detail/__icsFiles/afieldfile/2019/05/16/1416496_001.pdf#page=10

そうすれば、単元情報を入れるのに時間がかかったとしても、
趣意書の情報だけであれば先行していれることはできるので、
それまでの繋ぎにでも、教科書から目次的な情報を参照できてよいとおもう。

プロパティ名は何がいいかも検討事項。

**Comment by masao** [comment]
情報量としてはすでにLOD内部に存在するので、以下のような、編集趣意書のURLとページ番号の情報を抽出しておいて、自動でURLとしてリンクした情報を関連リンクとして貼っておくだけでも良い気がします。

?t | ?url | ?page
-- | -- | --
https://w3id.org/jp-textbook/中学校/2020/国語/901 | https://www.mext.go.jp/content/20200428_mxt_kouhou02_mext_00002_03.pdf | 11
https://w3id.org/jp-textbook/中学校/2020/国語/903 | https://www.mext.go.jp/content/20200428_mxt_kouhou02_mext_00002_09.pdf | 11
https://w3id.org/jp-textbook/中学校/2020/国語/904 | https://www.mext.go.jp/content/20200428_mxt_kouhou02_mext_00002_12.pdf | 11
https://w3id.org/jp-textbook/中学校/2020/公民/905 | https://www.mext.go.jp/content/20200501_mxt_kouhou02_mext_00003_02.pdf | 11-12
https://w3id.org/jp-textbook/中学校/2020/数学/701 | https://www.mext.go.jp/content/20200428_mxt_kouhou02_mext_00004_01.pdf | 11
https://w3id.org/jp-textbook/中学校/2020/数学/702 | https://www.mext.go.jp/content/20200428_mxt_kouhou02_mext_00004_04.pdf | 11
https://w3id.org/jp-textbook/中学校/2020/数学/703 | https://www.mext.go.jp/content/20200428_mxt_kouhou02_mext_00004_07.pdf | 13
https://w3id.org/jp-textbook/中学校/2020/器楽/751 | https://www.mext.go.jp/content/20200428-mxt_kouhou02-000006915_5.pdf | 11
https://w3id.org/jp-textbook/中学校/2020/保体/701 | https://www.mext.go.jp/content/20200428-mxt_kouhou02-000006917_1.pdf | 11-12
https://w3id.org/jp-textbook/中学校/2020/保体/701 | https://www.mext.go.jp/content/20200428-mxt_kouhou02-000006917_2.pdf | 11-12

抽出用のSPARQLは以下の通り：

```SPARQL
PREFIX textbook: <https://w3id.org/jp-textbook/>
PREFIX schema: <http://schema.org/>
select ?t ?url ?page where { 
?t a textbook:Textbook.
?c textbook:textbook ?t.
?c schema:hasPart ?chap.
?chap textbook:chapterType textbook:CPMappingACTable.
?chap schema:pagination ?page.
?c schema:url ?url.
} limit 10
```

**Comment by yegusa** [comment]
データをつくるのではなく、htmlのほうを修正するかんじですね。はい、じゃあ、その方向で行きましょう！

**Comment by masao** [comment]
追加しました

**Comment by yegusa** [comment]
確認しました。

素敵です！

![image](https://github.com/user-attachments/assets/b1e40ca8-1ea6-4c12-bec8-c296f5f5fee4)

一見なんのことかわからないけど、知る人ぞ知る目次っぽいデータってなってるけれども。
