### ISSUE TITLE
リンクできていない出版社リソースがある

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#612]
以下2件の出版社リソースが教科書リソースからリンクされているものの、存在しない。

* 教科書: https://w3id.org/jp-textbook/高等学校/2023/工業/772
  * 出版社: https://w3id.org/jp-textbook/publisher/2023/文部科学省
* 教科書: https://w3id.org/jp-textbook/小学校/1999/保健/518
  * 出版社: https://w3id.org/jp-textbook/publisher/1999/光文

**Comment by yegusa** [comment]
修正しておきました。24.0系にいれてあります。

**Comment by yegusa** [comment]
## [https://w3id.org/jp-textbook/publisher/2023/文部科学省](https://w3id.org/jp-textbook/publisher/2023/%E6%96%87%E9%83%A8%E7%A7%91%E5%AD%A6%E7%9C%81)
こっちは教科書目録の発行者一覧になかったもよう。例外的にデータ作って入れておきました。

当該教科書目録：[https://w3id.org/jp-textbook/catalogue/高等学校/2023](https://w3id.org/jp-textbook/catalogue/%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1/2023)


## [https://w3id.org/jp-textbook/publisher/1999/光文](https://w3id.org/jp-textbook/publisher/1999/%E5%85%89%E6%96%87)
こっちは教科書目録が古くてWebやアーカイブにはないので、現物の紙をみないといけないので
発行者一覧に載っていたかどうかは確認してません。
私の入力ミスかもしれません。
教科書は存在しているし、発行者の入力ミスというわけでもなさそうなので、
データを作っておきました。

あとで、以下の現物は確認しておきます。
小学校用教科書目録(平成12年度使用)
 https://w3id.org/jp-textbook/catalogue/小学校/1999

**Comment by masao** [comment]
追加しました

**Comment by yegusa** [comment]
https://w3id.org/jp-textbook/publisher/1999/光文
こちら確認しました。

https://w3id.org/jp-textbook/publisher/2023/文科省

が正しいようです。
で、これもできていることを確認しました。

教科書: https://w3id.org/jp-textbook/高等学校/2023/工業/772
出版社: https://w3id.org/jp-textbook/publisher/2023/文部科学省

これは、教科書のメタデータのほうがまちがっているので、別issueでやります。

このissueはクローズします。

**Comment by yegusa** [comment]
> あとで、以下の現物は確認しておきます。
> 小学校用教科書目録(平成12年度使用)
> [https://w3id.org/jp-textbook/catalogue/小学校/1999](https://w3id.org/jp-textbook/catalogue/%E5%B0%8F%E5%AD%A6%E6%A0%A1/1999)

現物確認しました。208 光文 ありました。
