### ISSUE TITLE
編修趣意書基本情報　ページがない（-）のものはデータをつくらないようにする

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#614]
#607 で気づいた

https://w3id.org/jp-textbook/AC100000000560

    <http://schema.org/pagination> "-";
    <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <https://w3id.org/jp-textbook/CompilingProspectusChapter>;
    <https://w3id.org/jp-textbook/chapterType> <https://w3id.org/jp-textbook/CPMappingTUTable>

こういうのをttlとして出力しないようにしたほうがいいよね

**Comment by yegusa** [comment]
データを作って、 compilingProspectus-20241229_2.ttl ってファイルで置いておきました。

**Comment by masao** [comment]
修正しました

**Comment by yegusa** [comment]
確認しました。
