### ISSUE TITLE
趣意書基本情報で、高等学校の専門科目リソースへのリンクに修正が必要

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#615]
以下の編集趣意書リソース：

textbook:AC100000001090
textbook:AC100000001091
textbook:AC100000001089
textbook:AC100000001095
textbook:AC100000000857
textbook:AC100000000856
textbook:AC100000001092
textbook:AC100000001096
textbook:AC100000001093
textbook:AC100000001094

科目リソースは <https://w3id.org/jp-textbook/curriculum/高等学校/2022/家庭/フードデザイン> ではなく <https://w3id.org/jp-textbook/curriculum/高等学校/2022/家庭(専門)/フードデザイン> とする必要あり。

**Comment by yegusa** [comment]
修正しました。 20241230のファイルのものです

**Comment by masao** [comment]
登録反映しました

**Comment by yegusa** [comment]
確認しました。
