### ISSUE TITLE
編修趣意書から教科書へのリンクにいくつか誤りがある

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#618]
例えば、以下の教科書は2つの編修趣意書が紐づいているが、片方は出版社が異なるため、誤って紐づけていると思われる。

[https://w3id.org/jp-textbook/中学校/2020/保体/701](https://w3id.org/jp-textbook/%E4%B8%AD%E5%AD%A6%E6%A0%A1/2020/%E4%BF%9D%E4%BD%93/701)

**Comment by masao** [comment]
手元で確認した感じだと、少なくとも以下が該当する：

https://w3id.org/jp-textbook/AC100000000305
https://w3id.org/jp-textbook/AC100000000313
https://w3id.org/jp-textbook/AC100000000315
https://w3id.org/jp-textbook/AC100000000317
https://w3id.org/jp-textbook/AC100000000798
https://w3id.org/jp-textbook/AC100000000799
https://w3id.org/jp-textbook/AC100000000807
https://w3id.org/jp-textbook/AC100000000808

**Comment by masao** [comment]
参考：編修趣意書と教科書発行者とで、発行者略称が異なるものを抜き出すSPARQLクエリ：

```sparql
PREFIX t: <https://w3id.org/jp-textbook/>
select * where {
?c a t:CompilingProspectus.
?c t:textbook ?t.
?t <http://schema.org/publisher> ?p.
?c t:publisherAbbreviation ?cabbr.
?p t:publisherAbbreviation ?pabbr.
filter (?cabbr != ?pabbr)
}
```

**Comment by yegusa** [comment]
上から順番に、以下のように修正しました。
20241230_2 というファイル名です。

教科書番号を751->752
教科書番号を701->702
教科書記号703->704
教科書記号を701->702
趣意書には啓林だが、正しくは：啓林館
趣意書からの出版者略称転記ミス（教研→数研）
趣意書からの出版者略称転記ミス（教研→数研）
趣意書からの出版者略称転記ミス（教研→数研）

**Comment by masao** [comment]
修正を反映しました

**Comment by yegusa** [comment]
確認しました
