### ISSUE TITLE
大単元、中単元、小単元、極小単元はどういうプロパティにするか

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#619]
今回、大単元、中単元、小単元、極小単元を入力してみたけど、
どういうプロパティにしてデータにしましょうか？

**Comment by masao** [comment]
案1: 意味を残すなら largeUnitName, middleUnitName, smallUnitName, tinyUnitName

案2: ものすごく単純にやるなら unit1, unit2, unit3, unit4, ... とするのでもよい（HTMLの見出しタグっぽく）。

案3: もしくは、tex風に unitName, subUnitName, subsubUnitName, subsubsubUnitName か。これはsubの個数を数え間違えそうなので、やめたほうが良さそうだが。。。

**Comment by yegusa** [comment]
案2でいいきがするなあ。ちょっとデータとshapeファイル作ってみる。

**Comment by yegusa** [comment]
データをshapeファイルを作っておきました。

**Comment by masao** [comment]
反映しました

**Comment by yegusa** [comment]
https://w3id.org/jp-textbook/AA100000016271

こんなかんじですよね。
できているようなのでクローズします。
