### ISSUE TITLE
拡張cosコードを作る方法でバグ？

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#620]
こんなデータがありました。

AA100000016059 | 83A0213121100000,83A0213121200000,,83A0213311000000,83A0213312000000 | ,83A0213121100000,83A0213121200000,83A0213311000000,83A0213312000000
-- | -- | --
AA100000016060 | 83A0213121100000,83A0213121200000,,83A0213311000000,83A0213312000000 | ,83A0213121100000,83A0213121200000,83A0213311000000,83A0213312000000

**Comment by masao** [comment]
一応、修正しました

**Comment by yegusa** [comment]
ありがとうございます。
これ、バグというよりは、「,,」があるのが問題だったのですよね。データのほうは直しておきました。
とりあえず、クローズします。
