### ISSUE TITLE
単元リソースの学習指導要領の細目を最後に表示するようにする

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#621]
#611 を確認して気づいたのですが、

学習指導要領の細目
originalcositem

は、長くなることがあるので最後に表示した方がいいかもと思いました。

ついでに質問：
Webの公開ページでの、プロパティごとの表示順ってどうやって制御するのですか？

**Comment by masao** [comment]
うーん、変ですね。プロパティの表示順は、グラフシェイプSHACLで記載してある sh:order の順になるのですが、その通りになってないですね。。。ttl2htmlのバグかもしれません。

**Comment by masao** [comment]
バグではなく、Shapeのプロパティ順に表示するので、そちらを修正してください。ExcelからShapeを生成しているので、Excel上でプロパティを並べたい順序に入れておいて頂ければ。。

**Comment by yegusa** [comment]
順序にそんな意味があるなんて知りませんでした！了解しました。
TeachingUnit シートを修正して 20241231_3というshapeファイルを作りました。

**Comment by masao** [comment]
反映しました

**Comment by yegusa** [comment]
できているようなのでクローズします。

https://w3id.org/jp-textbook/AA100000017690
