### ISSUE TITLE
種目をソートするためのキーが欲しい

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#64]
教科のissue #63 と同様です

**Comment by yegusa** [comment]
#63 と同様に、以下のような感じでttlデータつくっておきました。


@prefix schema: <http://schema.org/>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.
@prefix textbook: <https://w3id.org/jp-textbook/>.
@prefix qb: <http://purl.org/linked-data/cube#>.
<https://w3id.org/jp-textbook/curriculum/小学校/1992/国語/国語> a <https://w3id.org/jp-textbook/curriculum/Subject>;
  schema:name "国語";
  qb:order 1;
  schema:citation "『教科用図書検定申請受理種目』平成元年6月9日文部省告示第89号".
<https://w3id.org/jp-textbook/curriculum/小学校/1992/国語> textbook:hasSubject <https://w3id.org/jp-textbook/curriculum/小学校/1992/国語/国語>.
<https://w3id.org/jp-textbook/curriculum/小学校/1992/国語/書写> a <https://w3id.org/jp-textbook/curriculum/Subject>;
  schema:name "書写";
  qb:order 2;
  schema:citation "『教科用図書検定申請受理種目』平成元年6月9日文部省告示第89号".
<https://w3id.org/jp-textbook/curriculum/小学校/1992/国語> textbook:hasSubject <https://w3id.org/jp-textbook/curriculum/小学校/1992/国語/書写>.

**Comment by masao** [comment]
プロパティとしては追加されたのでひとまずクローズします。
