### ISSUE TITLE
教科のよみがあるとよいかもしれない

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#65]
ブラウジングリストを表示する際や、結果表示の際に、50順でソートしたいなどのニーズのため。

**Comment by yegusa** [comment]
順序については、べつのプロパティで対応することにしたので、いい。

**Comment by yegusa** [comment]
ひらがなだけ？ローマ字は、ひらがなからジェネレート？

**Comment by yegusa** [comment]
読みがあるとよい利点は、

- 日本語インタフェースでも、ルビなどの可能性がひろがる
- 英語インタフェースに対応できそう

**Comment by yegusa** [comment]
「ひらがな」だけで、とりあず、よいことにする。

**Comment by masao** [comment]
ひとまず言語属性で対応させる：

```
<https://w3id.org/jp-textbook/curriculum/高等学校/2013/地理歴史>
  schema:name "地理歴史"@ja;
  schema:name "ちりれきし"@ja-Hira.
```

**Comment by yegusa** [comment]
作成しました。
5.0系フォルダにいれておきましたので、確認ください。

**Comment by masao** [comment]
確認しました。ひとまずクローズします。
