### ISSUE TITLE
フッタに about ページへのリンクを貼る

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#67]
教科書詳細ページにジャンプしてきた訪問者に、このデータの責任者等を伝えられるようにしたほうがよさそう。

**Comment by yegusa** [comment]
フッターの「© 2017 教科書LODプロジェクト」 の　「 教科書LODプロジェクト」にリンクをはる。

**Comment by masao** [comment]
フッターにリンクを追加したのでクローズします。
