### ISSUE TITLE
教科、種目から学校種別を示すプロパティがあるとよい

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#68]
- [x] ttl作成
- [ ] HTML作成

#59 に関連して。教科や種目のプロパティに、学校種別が紐づいていないのはおかしいので、追加すること。

**Comment by yegusa** [comment]
教科 -- textbook:school --> dbpedia:中学校
　　小学校、高等学校も同様。

というようなかんじでつけますね。

**Comment by yegusa** [comment]
教科、種目ともに、ttl 作っておきました。

**Comment by masao** [comment]
追加されたことを確認したのでクローズします。
