### ISSUE TITLE
プロパティの検討、開発：ページ数・大きさのプロパティをttlに追加

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#7]
教育図書館のデータにあるので、ttlに追加するのみ

-ページ数・大きさ
-例：130;A5

**Comment by masao** [comment]
プロパティとしては、BIBFRAMEモデルから extent, dimensions に分けて記入するようにすること。

```
textbook:小学校/2010/保健/301 -- bf:extent --> 130
textbook:小学校/2010/保健/301 -- bf:dimensions --> "B5"
```

cf. http://id.loc.gov/ontologies/bibframe.html#p_extent, http://id.loc.gov/ontologies/bibframe.html#p_dimensions

**Comment by yegusa** [comment]
これは、簡単。すぐできそう。

**Comment by yegusa** [comment]
ttlの作成ですよね。html表示も必要ですよね。

![image](https://user-images.githubusercontent.com/1328499/31113647-37921094-a855-11e7-8078-977a263eef3f.png)

できていることを確認しましたので、クローズします。
HTML表示の分は別issueにします。
