### ISSUE TITLE
種目名称の違い： 理科(第一/第二分野) と 理科(第1/第2分野) が混在している

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#70]
- [x] ttl作成
- [x] HTML作成

subject-*.ttl では、理科(第1分野) となっているが、 textbook-*.ttl では 理科(第一分野) となっているので対応していない。

* https://w3id.org/jp-textbook/curriculum/中学校/1993/理科/理科(第一分野)

**Comment by yegusa** [comment]
元データ（教科図書申請受理種目）でも、漢字だったので、漢字で統一でよさそう。
じゃあ、subject-.ttlのほうを漢字になるように修正することにします。

**Comment by yegusa** [comment]
以下になるように subject-.ttl のほうを修正しました

https://w3id.org/jp-textbook/curriculum/中学校/1993/理科/理科(第一分野)
https://w3id.org/jp-textbook/curriculum/中学校/1993/理科/理科(第二分野)
https://w3id.org/jp-textbook/curriculum/中学校/2002/理科/理科(第一分野)
https://w3id.org/jp-textbook/curriculum/中学校/2002/理科/理科(第二分野)

**Comment by masao** [comment]
修正を確認したのでクローズします。
