### ISSUE TITLE
種目データ存在せず：古典講読

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#71]
- [x] ttl作成（@yeugsa)
- [x] HTML作成(@masao)

subject-20170606.ttl にて、 https://w3id.org/jp-textbook/curriculum/高等学校/1994/国語/古典講読 が見当たらない。textbook-20170606.ttl には存在するため、要確認。

**Comment by yegusa** [comment]
- 教科書リソースには「古典講読」がある
- 種目リソースには「古典講読」がない

ことについて、原因を究明すること

**Comment by yegusa** [comment]
データ作成のタイポのようです。
（官報データベースの当該種目のタイポのようです）

https://w3id.org/jp-textbook/curriculum/高等学校/1994/国語/古典購読

購読が貝のほうになってました。

種目のttlファイルを修正しておきました

**Comment by masao** [comment]
更新されたことを確認したのでクローズします。
