### ISSUE TITLE
教科書見当たらず：コミュニケーション英語IIなど複数

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#74]
- [x] 教育図書館に報告　2017-06-11
- [x] データ修正
- [x] データ確認
- [x] データ入手

コミュニケーション英語I と コミュニケーション英語III は存在するので、何らかのエラーと推測される。

* https://w3id.org/jp-textbook/curriculum/高等学校/2013/外国語/コミュニケーション英語II

**Comment by yegusa** [comment]
#75 も同様です。

調べてみました。

II の呪い的な。

少なくとも、以下の教科書のデータがのっていないようです。

- [ ] 音楽II p.22
- [ ] 美術II p.23
- [ ] 工芸II p.23
- [ ] 書道II p.24
- [ ] コミュニケーション英語II p.28
- [ ] 英語表現II p.30

p.xxは教科書目録2013年度発行のページ数です。

教育図書館に連絡しておきました。

**Comment by yegusa** [comment]
教育図書館から連絡あり、入力ミスだそうです。
入力完了したら連絡するとのこと。

他に、数学IIIのもあったそうです。

**Comment by yegusa** [comment]
データがもらえていないので、再度、教育図書館に連絡（2017-09-16に連絡）

**Comment by yegusa** [comment]
こちらは残すほうなので、duplicate ラベルは削除しました

**Comment by yegusa** [comment]
データを教育図書館から入手したので、あとは、作業するのみ

**Comment by yegusa** [comment]
2017-10-03に入手したデータのなかに以下のような感じで、IIのデータがはいっていたのでOKかとおもいます。


textbook:高等学校/2013/コII/301
textbook:高等学校/2013/コII/302
textbook:高等学校/2013/コII/303
textbook:高等学校/2013/コII/304
textbook:高等学校/2013/コII/305
textbook:高等学校/2013/コII/306
textbook:高等学校/2013/コII/307
textbook:高等学校/2013/コII/308
textbook:高等学校/2013/コII/309
textbook:高等学校/2013/コII/310
textbook:高等学校/2013/コII/311
textbook:高等学校/2013/コII/312
textbook:高等学校/2013/コII/313
textbook:高等学校/2013/コII/314
textbook:高等学校/2013/コII/315
textbook:高等学校/2013/コII/316
textbook:高等学校/2013/コII/317
textbook:高等学校/2013/コII/318
textbook:高等学校/2013/コII/319
textbook:高等学校/2013/コII/320
textbook:高等学校/2013/コII/321
textbook:高等学校/2013/コII/322
textbook:高等学校/2013/コII/323
textbook:高等学校/2013/コII/324
textbook:高等学校/2013/コII/325
textbook:高等学校/2015/コIII/324
textbook:高等学校/2013/英II/301
textbook:高等学校/2013/英II/302
textbook:高等学校/2013/英II/303
textbook:高等学校/2013/英II/304
textbook:高等学校/2013/英II/305
textbook:高等学校/2013/英II/306
textbook:高等学校/2013/英II/307
textbook:高等学校/2013/英II/308
textbook:高等学校/2013/英II/309
textbook:高等学校/2013/英II/310
textbook:高等学校/2013/英II/311
textbook:高等学校/2013/英II/312
textbook:高等学校/2013/英II/313
textbook:高等学校/2013/英II/314
textbook:高等学校/2013/音II/301
textbook:高等学校/2013/音II/302
textbook:高等学校/2013/音II/303
textbook:高等学校/2013/音II/304
textbook:高等学校/2013/音II/305
textbook:高等学校/2013/音II/306
textbook:高等学校/2013/工II/301
textbook:高等学校/2013/書II/301
textbook:高等学校/2013/書II/302
textbook:高等学校/2013/書II/303
textbook:高等学校/2013/書II/304
textbook:高等学校/2013/数III/314
textbook:高等学校/2013/美II/301
textbook:高等学校/2013/美II/302

**Comment by masao** [comment]
#117 にあわせて一通り入手済み。クローズします。
