### ISSUE TITLE
教科書見当たらず：音楽II

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#75]
- [x] 教育図書館に報告　2017-06-11
- [ ] データ修正
- [ ] データ確認
- [ ] データ入手

音楽I と 音楽III は存在するので、何かのミスがあると思われる。

* https://w3id.org/jp-textbook/curriculum/高等学校/2013/芸術/音楽II

**Comment by yegusa** [comment]
進捗は、 #74 のほうをご覧ください

**Comment by masao** [comment]
#74 のほうで管理することにするので、こちらはクローズします。
