### ISSUE TITLE
教科書目録リソースの詳細ページを追加する

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#8]
- [x] 教科書目録ttlのためのデータ入力(Excel)
- [x] 教科書目録ttlの作成
- [x] プログラム開発

**Comment by yegusa** [comment]
参考：教育図書館所蔵の教科書目録（すべての学校種目の合本として作成のためNACSISには登録していない）
https://nieropac.nier.go.jp/webopac/BB00014905

**Comment by yegusa** [comment]
https://w3id.org/jp-textbook/catalogue/学校種別/教科書目録発行年

**Comment by masao** [comment]
一通り必要な開発は完了したので確認願います。

**Comment by yegusa** [comment]
スタートとしては、良いと思います。
要望は別issueでやります。
クローズします。
