### ISSUE TITLE
教科書目録ページから教科書へのリンクを追加する

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#81]
戻るリンクを追加するとうれしいシーンも多いかも。
※ただし、教科書目録を知らない人には誤解を与えそう？？

**Comment by yegusa** [comment]
全ての教科書目録のページに、初掲載の教科書だけでなく、
当該目録に載っている全ての教科書がリストアップされていると良いと思います。
一応、個々の教科書リソースの「使用年」で 各使用年の「使用年-1」が教科書目録の発行年なので、逆算してリストは作れるはず（教育図書館は逆の作業をして、使用年を作成しています）。

（関連 #347 教科書の同一使用年のものをリンク）
（関連 #346 使用年を開始・終了のデータにする）

**Comment by masao** [comment]
リンクを追加しました。

**Comment by yegusa** [comment]
第一フェーズとして、いいと思います！

が、全部見たわけじゃないですが、出ないやつがありました。

- NG：https://w3id.org/jp-textbook/catalogue/小学校/2015

https://w3id.org/jp-textbook/小学校/2014/国語/131

こういうのとか、色々リストアップされないとおかしいよね？

以下は、少なくとも何らかのリストはでてたことは確認しました。

- OK: https://w3id.org/jp-textbook/catalogue/中学校/2015
- OK: https://w3id.org/jp-textbook/catalogue/高等学校/2015

また、ソート方法など、よりよくするための提案については、 #373 #374 の別issueにしておきました。

**Comment by yegusa** [comment]
確かめ用リンク

### 小学校

- [ ]   https://jp-textbook.github.io/catalogue/小学校/1991
- [ ]   https://jp-textbook.github.io/catalogue/小学校/1992
- [ ]   https://jp-textbook.github.io/catalogue/小学校/1993
- [ ]   https://jp-textbook.github.io/catalogue/小学校/1994
- [ ]   https://jp-textbook.github.io/catalogue/小学校/1995
- [ ]   https://jp-textbook.github.io/catalogue/小学校/1996
- [ ]   https://jp-textbook.github.io/catalogue/小学校/1997
- [ ]   https://jp-textbook.github.io/catalogue/小学校/1998
- [ ]   https://jp-textbook.github.io/catalogue/小学校/1999
- [ ]   https://jp-textbook.github.io/catalogue/小学校/2000
- [ ]   https://jp-textbook.github.io/catalogue/小学校/2001
- [ ]   https://jp-textbook.github.io/catalogue/小学校/2002
- [ ]   https://jp-textbook.github.io/catalogue/小学校/2003
- [ ]   https://jp-textbook.github.io/catalogue/小学校/2004
- [ ]   https://jp-textbook.github.io/catalogue/小学校/2005
- [ ]   https://jp-textbook.github.io/catalogue/小学校/2006
- [ ]   https://jp-textbook.github.io/catalogue/小学校/2007
- [ ]   https://jp-textbook.github.io/catalogue/小学校/2008
- [ ]   https://jp-textbook.github.io/catalogue/小学校/2009
- [ ]   https://jp-textbook.github.io/catalogue/小学校/2010
- [ ]   https://jp-textbook.github.io/catalogue/小学校/2011
- [ ]   https://jp-textbook.github.io/catalogue/小学校/2012
- [ ]   https://jp-textbook.github.io/catalogue/小学校/2013
- [ ]   https://jp-textbook.github.io/catalogue/小学校/2014
- [ ]   https://jp-textbook.github.io/catalogue/小学校/2015
- [ ]   https://jp-textbook.github.io/catalogue/小学校/2016
- [ ]   https://jp-textbook.github.io/catalogue/小学校/2017

### 中学校 

- [ ]   https://jp-textbook.github.io/catalogue/中学校/1992
- [ ]   https://jp-textbook.github.io/catalogue/中学校/1993
- [ ]   https://jp-textbook.github.io/catalogue/中学校/1994
- [ ]   https://jp-textbook.github.io/catalogue/中学校/1995
- [ ]   https://jp-textbook.github.io/catalogue/中学校/1996
- [ ]   https://jp-textbook.github.io/catalogue/中学校/1997
- [ ]   https://jp-textbook.github.io/catalogue/中学校/1998
- [ ]   https://jp-textbook.github.io/catalogue/中学校/1999
- [ ]   https://jp-textbook.github.io/catalogue/中学校/2000
- [ ]   https://jp-textbook.github.io/catalogue/中学校/2001
- [ ]   https://jp-textbook.github.io/catalogue/中学校/2002
- [ ]   https://jp-textbook.github.io/catalogue/中学校/2003
- [ ]   https://jp-textbook.github.io/catalogue/中学校/2004
- [ ]   https://jp-textbook.github.io/catalogue/中学校/2005
- [ ]   https://jp-textbook.github.io/catalogue/中学校/2006
- [ ]   https://jp-textbook.github.io/catalogue/中学校/2007
- [ ]   https://jp-textbook.github.io/catalogue/中学校/2008
- [ ]   https://jp-textbook.github.io/catalogue/中学校/2009
- [ ]   https://jp-textbook.github.io/catalogue/中学校/2010
- [ ]   https://jp-textbook.github.io/catalogue/中学校/2011
- [ ]   https://jp-textbook.github.io/catalogue/中学校/2012
- [ ]   https://jp-textbook.github.io/catalogue/中学校/2013
- [ ]   https://jp-textbook.github.io/catalogue/中学校/2014
- [ ]   https://jp-textbook.github.io/catalogue/中学校/2015
- [ ]   https://jp-textbook.github.io/catalogue/中学校/2016
- [ ]   https://jp-textbook.github.io/catalogue/中学校/2017
 
### 高等学校

- [ ]   https://jp-textbook.github.io/catalogue/高等学校/1993
- [ ]   https://jp-textbook.github.io/catalogue/高等学校/1994
- [ ]   https://jp-textbook.github.io/catalogue/高等学校/1995
- [ ]   https://jp-textbook.github.io/catalogue/高等学校/1996
- [ ]   https://jp-textbook.github.io/catalogue/高等学校/1997
- [ ]   https://jp-textbook.github.io/catalogue/高等学校/1998
- [ ]   https://jp-textbook.github.io/catalogue/高等学校/1999
- [ ]   https://jp-textbook.github.io/catalogue/高等学校/2000
- [ ]   https://jp-textbook.github.io/catalogue/高等学校/2001
- [ ]   https://jp-textbook.github.io/catalogue/高等学校/2002
- [ ]   https://jp-textbook.github.io/catalogue/高等学校/2003
- [ ]   https://jp-textbook.github.io/catalogue/高等学校/2004
- [ ]   https://jp-textbook.github.io/catalogue/高等学校/2005
- [ ]   https://jp-textbook.github.io/catalogue/高等学校/2006
- [ ]   https://jp-textbook.github.io/catalogue/高等学校/2007
- [ ]   https://jp-textbook.github.io/catalogue/高等学校/2008
- [ ]   https://jp-textbook.github.io/catalogue/高等学校/2009
- [ ]   https://jp-textbook.github.io/catalogue/高等学校/2010
- [ ]   https://jp-textbook.github.io/catalogue/高等学校/2011
- [ ]   https://jp-textbook.github.io/catalogue/高等学校/2012
- [ ]   https://jp-textbook.github.io/catalogue/高等学校/2013
- [ ]   https://jp-textbook.github.io/catalogue/高等学校/2014
- [ ]   https://jp-textbook.github.io/catalogue/高等学校/2015
- [ ]   https://jp-textbook.github.io/catalogue/高等学校/2016
- [ ]   https://jp-textbook.github.io/catalogue/高等学校/2017

**Comment by yegusa** [comment]
全部チェックしてみました。以下のような状況でした。

- 小学校：2件NG
  - https://jp-textbook.github.io/catalogue/小学校/2015
  - https://jp-textbook.github.io/catalogue/小学校/2016
- 中学校：2件NG
  - https://jp-textbook.github.io/catalogue/中学校/2016
  - https://jp-textbook.github.io/catalogue/中学校/2017
- 高等学校：全てのページに教科書リストが表示

**Comment by yegusa** [comment]
#375 のissueが原因でうまくできていない気がします。 #375 を直せば直るのじゃないかなと思います。

**Comment by masao** [comment]
修正したはず。。

**Comment by yegusa** [comment]
確かめました。全部何らかの教科書がリストアップされていることを確認しましたので、クローズします。
