### ISSUE TITLE
情報、家庭等の専門教科リソースURIを別に立てる

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#83]
- [ ] 教科ttl
  - [x] ttlたたき台作成
  - [ ] about
  - [x] HTML
- [ ] 種目ttl
  - [x] ttlたたき台作成
  - [ ] about
  - [x] HTML
- [x] 教科書ttl
  - [x] ruby開発
  - [x] HTML

高校教科のうち、「情報」と「家庭」は一般教科と専門教科の双方に同一名称があるため、切り分けることができない。

そこで、専門課程のほうを 
https://jp-textbook.github.io/curriculum/高等学校/2013/情報(専門)
などの形式で別URIとすることで区別できるようにする。

**追記：当初、機械判別できないかもと思っていたが、よく調べたら、書名や教科書記号を駆使すればできそうなことが判明したのでプログラムで可能であるのでぜひやりましょう。**

**Comment by yegusa** [comment]
教育図書館からもらっている書誌レコードのほうに、その区別がつけられそうなデータがないので、難しいかとおもいます。
3つの年代の学習指導要領のうち、最近のものは、種別がはいっている情報や家庭の場合は、一般教科のほうという区別は一応できますが、のこり2つの年代のほうは、区別ができないと思います。教科書記号も同じですし。

**Comment by masao** [comment]
最新の指導要領分だけやっておきますか。。。

**Comment by yegusa** [comment]
最新の指導指導要領の分（2013施行分)の場合は、
- 教科：情報で、種目：「社会と情報」 or 種目「情報の科学」が入っていた場合は、一般
- 教科：情報で、種目：「情報」 or 「（空欄）」の場合は、専門

**Comment by yegusa** [comment]
最新の指導指導要領の分（2013施行分)の場合は、
教科：家庭で、種目：「家庭基礎」 or 種目「家庭総合」or「生活デザイン」が入っていた場合は、一般
教科：家庭で、種目：「家庭」 or 「（空欄）」の場合は、専門

**Comment by yegusa** [comment]
古い指導要領2期分については、この区別もつけられない。なぜなら、「種目」が入っていないか、どれも、「教科」とおなじ「種目」が入力されているから。

**Comment by yegusa** [comment]
対策案：
- 新しい指導要領の教科書リソースは、教科書番号で区別できるので、教育図書館のデータから機械的に対応可
- 古い指導要領の教科書リソース分は、今後増えないだろうし、こちらで推定したデータを作っておいてそれを使う

つまり、毎年、新しい教科書レコードを追加する際に、学習指導要領URIを付与する作業と、この作業が増える感じ。

**Comment by yegusa** [comment]
2003施行学習指導要領の家庭と情報は、共通と専門が区別されて載っているので、共通の方だけ、種別を入れて欲しいとお願いするのもありな気がしてきました。

**Comment by yegusa** [comment]
関連issue #59

**Comment by yegusa** [comment]
#233 で例外2件の書名の修正を教育図書館でお願いしておきました。

**Comment by yegusa** [comment]
#233 の例外2件について、書名に種目が入りましたので、例外がなくなりました。

**Comment by yegusa** [comment]
教科

subjectArea-20181130.ttlを11.1系の作業フォルダに作って置いておきました。

関連のある教科：

- https://w3id.org/jp-textbook/curriculum/高等学校/1994/外国語
- https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭
- https://w3id.org/jp-textbook/curriculum/高等学校/1994/外国語(専門)
- https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭(専門)
- https://w3id.org/jp-textbook/curriculum/高等学校/2003/家庭
- https://w3id.org/jp-textbook/curriculum/高等学校/2003/情報
- https://w3id.org/jp-textbook/curriculum/高等学校/2003/家庭(専門)
- https://w3id.org/jp-textbook/curriculum/高等学校/2003/情報(専門)
- https://w3id.org/jp-textbook/curriculum/高等学校/2013/家庭
- https://w3id.org/jp-textbook/curriculum/高等学校/2013/情報
- https://w3id.org/jp-textbook/curriculum/高等学校/2013/家庭(専門)
- https://w3id.org/jp-textbook/curriculum/高等学校/2013/情報(専門)

**Comment by yegusa** [comment]
種目

subject-20181130.ttlを11.1系の作業フォルダに作って置いておきました。

関連のある種目：

https://w3id.org/jp-textbook/curriculum/高等学校/1994/外国語/英語I
https://w3id.org/jp-textbook/curriculum/高等学校/1994/外国語/英語II
https://w3id.org/jp-textbook/curriculum/高等学校/1994/外国語/オーラル・コミュニケーションA
https://w3id.org/jp-textbook/curriculum/高等学校/1994/外国語/オーラル・コミュニケーションB
https://w3id.org/jp-textbook/curriculum/高等学校/1994/外国語/オーラル・コミュニケーションC
https://w3id.org/jp-textbook/curriculum/高等学校/1994/外国語/リーディング
https://w3id.org/jp-textbook/curriculum/高等学校/1994/外国語/ライティング
https://w3id.org/jp-textbook/curriculum/高等学校/1994/外国語(専門)/ドイツ語
https://w3id.org/jp-textbook/curriculum/高等学校/1994/外国語(専門)/フランス語
https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭/家庭一般
https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭/生活技術
https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭/生活一般
https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭(専門)/家庭情報処理
https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭(専門)/被服
https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭(専門)/食物
https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭(専門)/保育
https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭(専門)/家庭経営
https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭(専門)/住居
https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭(専門)/家庭看護・福祉
https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭(専門)/消費経済
https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭(専門)/被服管理
https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭(専門)/服飾デザイン
https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭(専門)/調理
https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭(専門)/栄養
https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭(専門)/食品
https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭(専門)/食品衛生
https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭(専門)/保育原理・技術
https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭(専門)/小児保健
https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭(専門)/児童心理
https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭(専門)/児童福祉
https://w3id.org/jp-textbook/curriculum/高等学校/2003/家庭/家庭基礎
https://w3id.org/jp-textbook/curriculum/高等学校/2003/家庭/家庭総合
https://w3id.org/jp-textbook/curriculum/高等学校/2003/家庭/生活技術
https://w3id.org/jp-textbook/curriculum/高等学校/2003/情報/情報A
https://w3id.org/jp-textbook/curriculum/高等学校/2003/情報/情報B
https://w3id.org/jp-textbook/curriculum/高等学校/2003/情報/情報C
https://w3id.org/jp-textbook/curriculum/高等学校/2003/家庭(専門)/生活産業基礎
https://w3id.org/jp-textbook/curriculum/高等学校/2003/家庭(専門)/家庭情報処理
https://w3id.org/jp-textbook/curriculum/高等学校/2003/家庭(専門)/消費生活
https://w3id.org/jp-textbook/curriculum/高等学校/2003/家庭(専門)/発達と保育
https://w3id.org/jp-textbook/curriculum/高等学校/2003/家庭(専門)/児童文化
https://w3id.org/jp-textbook/curriculum/高等学校/2003/家庭(専門)/家庭看護・福祉
https://w3id.org/jp-textbook/curriculum/高等学校/2003/家庭(専門)/リビングデザイン
https://w3id.org/jp-textbook/curriculum/高等学校/2003/家庭(専門)/服飾文化
https://w3id.org/jp-textbook/curriculum/高等学校/2003/家庭(専門)/被服製作
https://w3id.org/jp-textbook/curriculum/高等学校/2003/家庭(専門)/ファッションデザイン
https://w3id.org/jp-textbook/curriculum/高等学校/2003/家庭(専門)/フードデザイン
https://w3id.org/jp-textbook/curriculum/高等学校/2003/家庭(専門)/食文化
https://w3id.org/jp-textbook/curriculum/高等学校/2003/家庭(専門)/調理
https://w3id.org/jp-textbook/curriculum/高等学校/2003/家庭(専門)/栄養
https://w3id.org/jp-textbook/curriculum/高等学校/2003/家庭(専門)/食品
https://w3id.org/jp-textbook/curriculum/高等学校/2003/家庭(専門)/食品衛生
https://w3id.org/jp-textbook/curriculum/高等学校/2003/情報(専門)/情報産業と社会
https://w3id.org/jp-textbook/curriculum/高等学校/2003/情報(専門)/情報と表現
https://w3id.org/jp-textbook/curriculum/高等学校/2003/情報(専門)/アルゴリズム
https://w3id.org/jp-textbook/curriculum/高等学校/2003/情報(専門)/情報システムの開発
https://w3id.org/jp-textbook/curriculum/高等学校/2003/情報(専門)/ネットワークシステム
https://w3id.org/jp-textbook/curriculum/高等学校/2003/情報(専門)/モデル化とシミュレーション
https://w3id.org/jp-textbook/curriculum/高等学校/2003/情報(専門)/コンピュータデザイン
https://w3id.org/jp-textbook/curriculum/高等学校/2013/家庭/家庭基礎
https://w3id.org/jp-textbook/curriculum/高等学校/2013/家庭/家庭総合
https://w3id.org/jp-textbook/curriculum/高等学校/2013/家庭/生活デザイン
https://w3id.org/jp-textbook/curriculum/高等学校/2013/情報/社会と情報
https://w3id.org/jp-textbook/curriculum/高等学校/2013/情報/情報の科学
https://w3id.org/jp-textbook/curriculum/高等学校/2013/家庭(専門)/生活産業基礎
https://w3id.org/jp-textbook/curriculum/高等学校/2013/家庭(専門)/生活産業情報
https://w3id.org/jp-textbook/curriculum/高等学校/2013/家庭(専門)/消費生活
https://w3id.org/jp-textbook/curriculum/高等学校/2013/家庭(専門)/子どもの発達と保育
https://w3id.org/jp-textbook/curriculum/高等学校/2013/家庭(専門)/子ども文化
https://w3id.org/jp-textbook/curriculum/高等学校/2013/家庭(専門)/生活と福祉
https://w3id.org/jp-textbook/curriculum/高等学校/2013/家庭(専門)/リビングデザイン
https://w3id.org/jp-textbook/curriculum/高等学校/2013/家庭(専門)/服飾文化
https://w3id.org/jp-textbook/curriculum/高等学校/2013/家庭(専門)/ファッション造形基礎
https://w3id.org/jp-textbook/curriculum/高等学校/2013/家庭(専門)/ファッション造形
https://w3id.org/jp-textbook/curriculum/高等学校/2013/家庭(専門)/ファッションデザイン
https://w3id.org/jp-textbook/curriculum/高等学校/2013/家庭(専門)/フードデザイン
https://w3id.org/jp-textbook/curriculum/高等学校/2013/家庭(専門)/食文化
https://w3id.org/jp-textbook/curriculum/高等学校/2013/家庭(専門)/調理
https://w3id.org/jp-textbook/curriculum/高等学校/2013/家庭(専門)/栄養
https://w3id.org/jp-textbook/curriculum/高等学校/2013/家庭(専門)/食品
https://w3id.org/jp-textbook/curriculum/高等学校/2013/家庭(専門)/食品衛生
https://w3id.org/jp-textbook/curriculum/高等学校/2013/家庭(専門)/公衆衛生
https://w3id.org/jp-textbook/curriculum/高等学校/2013/情報(専門)/情報産業と社会
https://w3id.org/jp-textbook/curriculum/高等学校/2013/情報(専門)/情報の表現と管理
https://w3id.org/jp-textbook/curriculum/高等学校/2013/情報(専門)/情報と問題解決
https://w3id.org/jp-textbook/curriculum/高等学校/2013/情報(専門)/情報テクノロジー
https://w3id.org/jp-textbook/curriculum/高等学校/2013/情報(専門)/アルゴリズムとプログラム
https://w3id.org/jp-textbook/curriculum/高等学校/2013/情報(専門)/ネットワークシステム
https://w3id.org/jp-textbook/curriculum/高等学校/2013/情報(専門)/データベース
https://w3id.org/jp-textbook/curriculum/高等学校/2013/情報(専門)/情報メディア
https://w3id.org/jp-textbook/curriculum/高等学校/2013/情報(専門)/情報デザイン
https://w3id.org/jp-textbook/curriculum/高等学校/2013/情報(専門)/表現メディアの編集と表現

**Comment by yegusa** [comment]
これ、やったら、影響大きいから、メジャーバージョンアップかなあ。

**Comment by yegusa** [comment]
#390 ができたので、こちらもやっちゃいましょう！下準備はできたよ！

**Comment by yegusa** [comment]
14.0系フォルダに、教科と種目のttlファイルを作り直して、置いておきました。

**Comment by masao** [comment]
下記の部分：
```
<https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭> textbook:hasSubject <https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭(専門)/家庭情報処理>
```

主語が <https://w3id.org/jp-textbook/curriculum/高等学校/1994/家庭(専門)> としなければならない気がします。

**Comment by yegusa** [comment]
修正して、14.0系フォルダに、
subject-20200316.ttl として置いておきました。

**Comment by masao** [comment]
一通り追加しました!

**Comment by masao** [comment]
追加した結果、SHACLの検証結果が以下の新指導要領関連のエラーだけになりました!（これまでは家庭と情報の教科のところで盛大に出ていた）

```
Validation Report
Conforms: False
Results (3):
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
        Severity: sh:Violation
        Source Shape: [ sh:class curriculum:SubjectArea ; sh:minCount Literal("1", datatype=xsd:integer) ; sh:name Literal("has a subject area", lang=en), Literal("教科がある", lang=ja) ; sh:order Literal("2", datatype=xsd:integer) ; sh:path textbook:hasSubjectArea ; skos:example Literal("textbook:curriculum/高等学校/1994/国語") ]
        Focus Node: <https://w3id.org/jp-textbook/curriculum/高等学校/2022>
        Result Path: textbook:hasSubjectArea
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
        Severity: sh:Violation
        Source Shape: [ sh:class curriculum:SubjectArea ; sh:minCount Literal("1", datatype=xsd:integer) ; sh:name Literal("has a subject area", lang=en), Literal("教科がある", lang=ja) ; sh:order Literal("2", datatype=xsd:integer) ; sh:path textbook:hasSubjectArea ; skos:example Literal("textbook:curriculum/高等学校/1994/国語") ]
        Focus Node: <https://w3id.org/jp-textbook/curriculum/中学校/2021>
        Result Path: textbook:hasSubjectArea
Constraint Violation in MinCountConstraintComponent (http://www.w3.org/ns/shacl#MinCountConstraintComponent):
        Severity: sh:Violation
        Source Shape: [ sh:class curriculum:SubjectArea ; sh:minCount Literal("1", datatype=xsd:integer) ; sh:name Literal("has a subject area", lang=en), Literal("教科がある", lang=ja) ; sh:order Literal("2", datatype=xsd:integer) ; sh:path textbook:hasSubjectArea ; skos:example Literal("textbook:curriculum/高等学校/1994/国語") ]
        Focus Node: <https://w3id.org/jp-textbook/curriculum/小学校/2020>
        Result Path: textbook:hasSubjectArea
```

**Comment by yegusa** [comment]
種目や、教科の方のaboutはなんか書いたほうがいいかな？

**Comment by yegusa** [comment]
できているようなので、クローズします。

aboutについては別issue #448 にしました。
