### ISSUE TITLE
aboutページの修正：教科書レコードの構造が少し変わった点を修正

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#86]
#82 についてのみ修正。重複レコードのみではなく、全部がこの構造（textbook:itemを使うように）にかわった。

**Comment by masao** [comment]
モデル図については https://github.com/jp-textbook/jp-textbook.github.io/commit/d821a825686c8ac9a4768bde9e1ac0c5468af186 にて修正済み。

**Comment by yegusa** [comment]
about https://jp-textbook.github.io/about.html

の　教科書をあらわすリソース表に一行追加した。
確認よろしく。

以下の行：
textbook:item	所蔵情報	（ブランクリソース）	nier:recordIDとnier:callNumberの2つの所蔵情報のためのプロパティを持つ

**Comment by masao** [comment]
確認したのでクローズします。
