### ISSUE TITLE
英語UIを追加する

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#90]
- [x] トップページ #187
- [x] about #199
- [x] 個別の教科書のページ #188 
- [x] 種目のページ #189 
- [x] 教科のページ #190
- [x] 学習指導要領のページ #191
- [x] 教科書目録のページ #218

海外からの閲覧者用にUIだけでも英語ラベルを用意してみること。
<s>優先度：低</s>

**Comment by masao** [comment]
英語ページは作成可能ではあるが、Github Pagesでは index.html.ja <-> index.html.en といったファイル名での自動的なContent Negotiationでのページ切替が効かないことが判明。。。

index.html <-> index-en.html みたいな明示的なファイル名を使うことを検討する必要あり。

**Comment by masao** [comment]
議論の結果： index.html <-> en/index.html という対応付けにより作成する。

**Comment by masao** [comment]
ひとまず一通りのページを英語化できたと思うので、いったん確認待ちにします。

**Comment by yegusa** [comment]
確認しました。クローズします。
