### ISSUE TITLE
教科書目録リソース：文科省の教科書目録の本文URLへのリンクをschema:urlに変更

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#91]
#80 からの派生。

**Comment by yegusa** [comment]
変更したデータを作成しました。

戦後教科書_LOD\ttlの元データ\4.2系　フォルダ以下に作成したデータをおきましたので、確認ください。 → @masao

**Comment by masao** [comment]
確認したところ、以下のように「rdf:seeAlso」で作られていましたが、これは「rdfs:seeAlso」ですね。。。要再作成。

```
  rdf:seeAlso <https://web.archive.org/web/*/http://www.mext.go.jp/a_menu/shotou/kyoukasho/__icsFiles/afieldfile/2016/04/20/1369944_4.pdf>;
```

**Comment by yegusa** [comment]
修正しました

**Comment by masao** [comment]
修正版を投入しました。

* https://jp-textbook.github.io/catalogue/小学校/2015
* https://jp-textbook.github.io/catalogue/小学校/2016
