### ISSUE TITLE
学習指導要領ページ内にURIを表示する

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#93]
現在、ページ内に固定URLが表記されていないので、教科書や教科のページとあわせるように修正する。

**Comment by yegusa** [comment]
学習指導要領のページにURIが表示されているのを確認したので、クローズする
(リンクもできていることを確認）

![image](https://user-images.githubusercontent.com/1328499/30509704-dee4e540-9af1-11e7-83e2-b55cb6d27fc4.png)
