### ISSUE TITLE
専門教科のうち、種目名が同じと記録されてしまっているものは除去する

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#94]
#59 からの派生。

教科「福祉」に教科書に記録されている種目「福祉」は除去すること。
1994、2003だけでなく、2013年学習指導要領でも有効にすべき。

**Comment by yegusa** [comment]
注意：

- 高等学校の種目のみ
- 教科：「保健体育」、種目：「保健体育」は例外（一般科目だが念のため書いておく）
