### ISSUE TITLE
リンク切れ修正：教科書→教科書一覧

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#95]
#2 での改訂に伴って、教科書一覧ページが廃止になったので、教科書ページからのパンくずリスト内のリンクがリンク切れになっているのを修正する。

**Comment by masao** [comment]
修正しました。確認願います。

**Comment by yegusa** [comment]
確認したのでクローズします。

種目：国語総合　をみているところ　　パンくずリスト上の教科：国語　をクリック
![image](https://user-images.githubusercontent.com/1328499/30509671-50498bc4-9af1-11e7-9010-83884a12b233.png)

問題なく表示された（リンク切れになっていない）
![image](https://user-images.githubusercontent.com/1328499/30509684-7673ef38-9af1-11e7-90df-ca3ef805b402.png)
