### ISSUE TITLE
教科ページ内での教科書一覧

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#96]
高等学校/水産 などの教科では、種目を削除したため、教科書一覧にたどれない状態になってしまう。
適宜処理を追加して、教科書一覧が閲覧できるようにすること。

**Comment by masao** [comment]
以前のように種目が存在しない教科書の存在する教科については、教科書一覧を追加しました。
ひとまずはこれで。

**Comment by yegusa** [comment]
種目が存在しない教科書の「教科」のページに、「教科書一覧」があることを確認しました。
これで、「種目」が「空」であっても、教科書にブラウジングでたどれるようになったことを
確認しました。
ので、クローズします。

例：「教科：水産」のページに、教科書一覧がある
https://jp-textbook.github.io/curriculum/%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1/2013/%E6%B0%B4%E7%94%A3/
![image](https://user-images.githubusercontent.com/1328499/30509612-1b7d6a1a-9af0-11e7-8f6d-0fa64d09bdd2.png)

例2:「種目」が存在している「国語」などは、教科書一覧がない（従来のまま）
https://jp-textbook.github.io/curriculum/%E9%AB%98%E7%AD%89%E5%AD%A6%E6%A0%A1/2013/%E5%9B%BD%E8%AA%9E/
![image](https://user-images.githubusercontent.com/1328499/30509604-ee6cc48a-9aef-11e7-873c-fd9e04961a17.png)
