### ISSUE TITLE
教科書情報の対象学年を明記する

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#97]
対象学年は、ヘッダ部分に表示されているだけなので、詳細情報のセクションにも追加すること。

**Comment by masao** [comment]
修正済み。要確認。

**Comment by yegusa** [comment]
詳細セクションにも表示されていることを確認しましたので、クローズします。

![image](https://user-images.githubusercontent.com/1328499/31113191-019ce79a-a853-11e7-995f-56ecd33f7e6f.png)
