### ISSUE TITLE
トップページに変更履歴へのリンクを追加

### ISSUE THREAD

**Issue by masao** [jp-textbook/jp-textbook.github.io#98]
トップページから変更履歴へのリンクを追加しておきたい。変更が頻繁になってきたので。

**Comment by masao** [comment]
ひとまずリンクを追加しました。

**Comment by yegusa** [comment]
確認しました。リンク先も、ちゃんと、更新履歴のページにいっていることをも確認しました。
ので、クローズします。

![image](https://user-images.githubusercontent.com/1328499/31113807-08209b72-a856-11e7-9a61-b04118aac219.png)
