### ISSUE TITLE
教科種別（Special or Common)のページを作る

### ISSUE THREAD

**Issue by yegusa** [jp-textbook/jp-textbook.github.io#99]
以下のURLに対応するページを作る

https://w3id.org/jp-textbook/curriculum/SubjectArea/Special
https://w3id.org/jp-textbook/curriculum/SubjectArea/Common

**Comment by masao** [comment]
#254 と区別できず、そちらで開発してしまいましたが、こちらも完了のはず。。

**Comment by yegusa** [comment]
あー、URIが変わったってことで、 #254 の重複何でしょうから、こちらは、重複ってことでクローズします。
